/* Challenge forms use the shared exam engine, storage, reflection controls, and backup. */
window.CHALLENGE = (() => {
  const names=['General Security Concepts','Threats, Vulnerabilities, and Mitigations','Security Architecture','Security Operations','Security Program Management and Oversight'];
  const weights=[12,22,18,28,20];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const isChallenge=h=>h?.contentRevision==='challenge-v13'||h?.results?.some(r=>r.question?.revision==='challenge-v13');
  function breakdown(h){return names.map((name,i)=>{
    const rows=(h.results||[]).filter(r=>r.objective?.startsWith((i+1)+'.'));
    const uncertain=r=>!!h.flags?.[r.id]||!!REASONING.get(h,r.id).reasons?.length||['Unsure','Guessing'].includes(REASONING.get(h,r.id).confidence);
    return {domain:i+1,name,total:rows.length,correct:rows.filter(r=>r.credit===1).length,uncertainCorrect:rows.filter(r=>r.credit===1&&uncertain(r)).length,confidentWrong:rows.filter(r=>r.credit<1&&REASONING.get(h,r.id).confidence==='Confident').length,unknown:rows.filter(r=>!REASONING.get(h,r.id).confidence).length};
  });}
  function report(h){if(!isChallenge(h))return '';const seen=h.previouslySeen??null;return `<section class="card challenge-report"><div class="kicker">DOMAIN BREAKDOWN · MCQ ONLY</div><h2>What the total score can hide</h2><div class="table-wrap"><table class="table"><thead><tr><th>Domain</th><th>Score</th><th>Correct but uncertain</th><th>Confident misses</th><th>Confidence unknown</th></tr></thead><tbody>${breakdown(h).filter(d=>d.total).map(d=>`<tr><td>${d.domain} · ${esc(d.name)}</td><td>${d.correct}/${d.total} · ${(100*d.correct/d.total).toFixed(1)}%</td><td>${d.uncertainCorrect}</td><td>${d.confidentWrong}</td><td>${d.unknown}</td></tr>`).join('')}</tbody></table></div><p>One point per correct answer. Unanswered items earn zero. ${h.minutes?`${h.minutes}-minute limit. `:'Untimed practice. '}${SCHOOL.time(h.duration/1000)} elapsed.</p><p>${seen===null?'':`${seen} questions appeared in earlier submitted attempts on this device. `}Correct guesses and flagged answers remain review priorities. This is an original challenge exam, not a calibrated prediction of CompTIA’s scaled score.</p></section>`;}
  function createUI(api){const {getState,startQuiz,go,title,openReview}=api;const $=s=>document.querySelector(s);
    function start(id,minutes=90){const exam=CHALLENGE_EXAMS.find(e=>e.id===id);if(!exam)return;const seen=new Set(getState().history.flatMap(h=>(h.results||[]).map(r=>r.id)));startQuiz(exam.questions,exam.name,minutes,true,{revision:'challenge-v13',examId:id,previouslySeen:exam.questions.filter(q=>seen.has(q.id)).length});}
    function home(){const s=getState();title('Challenge Exams','Two independent 100-question forms · no PBQs');$('#content').innerHTML=`<div class="grid"><section class="card"><div class="kicker">SY0-701 · HIGH-DIFFICULTY PRACTICE</div><h2>Choose your next full exam</h2><p>200 original questions across two fixed, non-overlapping forms. The difficulty target is 8–10/10: competing controls, evidence interpretation, constraints, and BEST/NEXT decisions. Difficulty is an authoring target, not an externally calibrated rating.</p><p>All five domains are mixed. The objective and explanations stay hidden until submission. Each question has one best answer. Questions and choices shuffle on each new attempt; your saved attempt keeps its order.</p><div class="challenge-weights">${names.map((n,i)=>`<div><b>${weights[i]} questions</b><span>Domain ${i+1} · ${esc(n)}</span></div>`).join('')}</div><p class="muted">The 100-question forms use the official domain percentages. The actual exam has a maximum of 90 questions and includes PBQs. <a href="https://comptiacdn.azureedge.net/webcontent/docs/default-source/exam-objectives/comptia-security-sy0-701-exam-objectives-(6-0).pdf?sfvrsn=204179cc_6" target="_blank" rel="noopener">CompTIA blueprint</a></p></section>${s.active?`<section class="card"><h2>Saved attempt</h2><p>${esc(s.active.label)} · question ${s.active.index+1}/${s.active.items.length}</p><button class="btn primary" id="challengeResume">Resume saved attempt</button><p>Starting another attempt asks before replacing unfinished work.</p></section>`:''}<div class="grid two">${CHALLENGE_EXAMS.map(e=>{const hs=s.history.filter(h=>h.examId===e.id&&h.results.length===100);return `<section class="card"><div class="kicker">100 MCQs · NO PBQs</div><h2>${e.name}</h2><p>${hs.length?`${hs.length} completed attempt${hs.length===1?'':'s'} · latest ${hs[0].percent}%. Retakes use the same questions.`:'No completed full attempt on this device.'}</p><label for="time-${e.id}">Time limit</label><select id="time-${e.id}" class="select"><option value="90">90 minutes · pressure practice</option><option value="100">100 minutes · one minute per question</option><option value="0">Untimed · detailed reasoning notes</option></select><div class="btn-row"><button class="btn primary" data-challenge-start="${e.id}">${hs.length?'Retake':'Start'} ${e.name}</button>${hs.length?`<button class="btn secondary" data-challenge-review="${e.id}">Review latest result</button>`:''}</div></section>`}).join('')}</div><section class="card"><h2>Capture your reasoning</h2><p>Use confidence, flag reasons, cross-outs, and notes as you work. Skipping requires acknowledgment. Scores, per-choice explanations, and domain breakdowns appear after final submission. Timed attempts keep running when closed and submit saved answers at expiry.</p><p>Your progress stays on this device and is included in Backup & Install exports. Messer A, B, and C remain separate.</p></section></div>`;
    if($('#challengeResume'))$('#challengeResume').onclick=()=>go('quiz');document.querySelectorAll('[data-challenge-start]').forEach(b=>b.onclick=()=>start(b.dataset.challengeStart,+$('#time-'+b.dataset.challengeStart).value));document.querySelectorAll('[data-challenge-review]').forEach(b=>b.onclick=()=>openReview(s.history.find(h=>h.examId===b.dataset.challengeReview&&h.results.length===100)));
    }
    return {home,start};
  }
  return {report,breakdown,isChallenge,createUI};
})();
