window.SECPLUS_DATA = {
  domains: [
    {id:1,name:'General Security Concepts',weight:12},
    {id:2,name:'Threats, Vulnerabilities, and Mitigations',weight:22},
    {id:3,name:'Security Architecture',weight:18},
    {id:4,name:'Security Operations',weight:28},
    {id:5,name:'Security Program Management and Oversight',weight:20}
  ],
  acronyms: [
    ['SLE','Single Loss Expectancy','Expected financial loss from one occurrence of a risk event.'],
    ['ARO','Annualized Rate of Occurrence','Expected frequency of a risk event in one year.'],
    ['ALE','Annual Loss Expectancy','Expected yearly loss. ALE = SLE × ARO.'],
    ['BPA','Business Partnership Agreement','Agreement that defines how business partners will work together.'],
    ['NDA','Non-Disclosure Agreement','Contract restricting disclosure of confidential information.'],
    ['MOU','Memorandum of Understanding','Documents a common understanding between parties.'],
    ['MOA','Memorandum of Agreement','Documents agreed responsibilities or actions between parties.'],
    ['SLA','Service-Level Agreement','Defines measurable service commitments such as uptime or response time.'],
    ['RTO','Recovery Time Objective','Maximum target time to restore a service after disruption.'],
    ['RPO','Recovery Point Objective','Maximum acceptable amount of data loss measured in time.'],
    ['MTTR','Mean Time to Repair','Average time required to restore a failed component or service.'],
    ['MTBF','Mean Time Between Failures','Average operating time between failures.'],
    ['PKI','Public Key Infrastructure','Framework for certificates, public/private keys, and trust.'],
    ['CA','Certificate Authority','Entity that issues and signs digital certificates.'],
    ['CSR','Certificate Signing Request','Request containing a public key and identifying information sent for signing.'],
    ['CRL','Certificate Revocation List','Published list of revoked certificates.'],
    ['OCSP','Online Certificate Status Protocol','Protocol used to check certificate revocation status.'],
    ['SIEM','Security Information and Event Management','Centralizes and correlates logs and security events.'],
    ['SOAR','Security Orchestration, Automation, and Response','Automates security workflows and response actions.'],
    ['EDR','Endpoint Detection and Response','Endpoint-focused detection, investigation, and response.'],
    ['XDR','Extended Detection and Response','Correlates detection and response across multiple security layers.'],
    ['DLP','Data Loss Prevention','Controls designed to detect and prevent unauthorized data disclosure.'],
    ['IAM','Identity and Access Management','Processes and technologies for identities and access.'],
    ['MFA','Multifactor Authentication','Authentication using factors from more than one category.'],
    ['SSO','Single Sign-On','One authentication event grants access to multiple services.'],
    ['RBAC','Role-Based Access Control','Permissions assigned according to job role.'],
    ['ABAC','Attribute-Based Access Control','Access decisions based on attributes and policies.'],
    ['PAM','Privileged Access Management','Controls and monitors privileged accounts and sessions.'],
    ['WAF','Web Application Firewall','Filters HTTP/S traffic to protect web applications.'],
    ['IDS','Intrusion Detection System','Detects suspicious activity and generates alerts.'],
    ['IPS','Intrusion Prevention System','Detects and actively blocks suspicious activity.'],
    ['VPN','Virtual Private Network','Encrypted tunnel across an untrusted network.'],
    ['IPsec','Internet Protocol Security','Suite for authenticating and encrypting IP traffic.'],
    ['ESP','Encapsulating Security Payload','IPsec protocol providing confidentiality and integrity.'],
    ['AH','Authentication Header','IPsec protocol providing integrity/authentication without encryption.'],
    ['PSK','Pre-Shared Key','Secret known to both parties for authentication.'],
    ['SSH','Secure Shell','Encrypted remote terminal and file-transfer protocol family.'],
    ['TLS','Transport Layer Security','Provides encryption and integrity for network sessions.'],
    ['DNS','Domain Name System','Resolves names to IP addresses and other records.'],
    ['DHCP','Dynamic Host Configuration Protocol','Automatically supplies IP configuration to clients.'],
    ['NTP','Network Time Protocol','Synchronizes system clocks.'],
    ['RDP','Remote Desktop Protocol','Microsoft remote desktop protocol.'],
    ['LDAP','Lightweight Directory Access Protocol','Queries and manages directory information.'],
    ['SAML','Security Assertion Markup Language','XML-based federation and authentication assertions.'],
    ['OAuth','Open Authorization','Delegated authorization framework.'],
    ['OIDC','OpenID Connect','Identity layer built on OAuth 2.0.'],
    ['FIDO','Fast Identity Online','Standards for strong, phishing-resistant authentication.'],
    ['TPM','Trusted Platform Module','Hardware root of trust for keys and measurements.'],
    ['HSM','Hardware Security Module','Dedicated hardware for secure cryptographic key operations.'],
    ['DR','Disaster Recovery','Processes and systems used to restore service after a disaster.'],
    ['BCP','Business Continuity Plan','Plan for maintaining critical business functions during disruption.'],
    ['IR','Incident Response','Organized process for handling security incidents.'],
    ['IoC','Indicator of Compromise','Artifact suggesting malicious activity or compromise.'],
    ['IoA','Indicator of Attack','Behavior or signal suggesting an attack is underway.'],
    ['CVSS','Common Vulnerability Scoring System','Standardized severity scoring for vulnerabilities.'],
    ['CVE','Common Vulnerabilities and Exposures','Identifier for a publicly known vulnerability.'],
    ['CWE','Common Weakness Enumeration','Catalog of software weakness types.'],
    ['SBOM','Software Bill of Materials','Inventory of software components and dependencies.'],
    ['SAST','Static Application Security Testing','Tests source/binary code without executing the application.'],
    ['DAST','Dynamic Application Security Testing','Tests a running application from the outside.'],
    ['IaC','Infrastructure as Code','Provisioning infrastructure using declarative code/configuration.'],
    ['CASB','Cloud Access Security Broker','Security control point between users and cloud services.'],
    ['CSPM','Cloud Security Posture Management','Continuously evaluates cloud configuration and posture.'],
    ['ZTNA','Zero Trust Network Access','Application access based on explicit trust decisions rather than network location.'],
    ['SD-WAN','Software-Defined Wide Area Network','Software-controlled WAN connectivity across multiple links.'],
    ['NAC','Network Access Control','Controls network access based on identity/device posture.'],
    ['802.1X','Port-Based Network Access Control','Standard for authenticating devices/users to wired or wireless access.'],
    ['RADIUS','Remote Authentication Dial-In User Service','AAA protocol often used for network access.'],
    ['TACACS+','Terminal Access Controller Access-Control System Plus','AAA protocol often used for administrative access to network devices.'],
    ['CIA','Confidentiality, Integrity, Availability','Core security objectives.'],
    ['AAA','Authentication, Authorization, Accounting','Identity, permission, and activity-tracking framework.'],
    ['PII','Personally Identifiable Information','Data that can identify a person.'],
    ['PHI','Protected Health Information','Health information protected under applicable healthcare privacy rules.'],
    ['PCI DSS','Payment Card Industry Data Security Standard','Security standard for environments handling payment card data.'],
    ['GDPR','General Data Protection Regulation','European Union data protection regulation.'],
    ['BYOD','Bring Your Own Device','Employees use personally owned devices for work.'],
    ['COPE','Corporate-Owned, Personally Enabled','Organization owns devices but permits some personal use.'],
    ['CYOD','Choose Your Own Device','User chooses from an organization-approved device list.'],
    ['MDM','Mobile Device Management','Centralized management and security of mobile devices.'],
    ['MAM','Mobile Application Management','Management focused on applications and app data.'],
    ['XSS','Cross-Site Scripting','Injection of executable script into content viewed by users.'],
    ['CSRF','Cross-Site Request Forgery','Tricks an authenticated browser into sending an unintended request.'],
    ['SQLi','SQL Injection','Injects SQL commands through application input.']
  ],
  ports: [
    [88,'Kerberos','TCP/UDP','Ticket-based authentication; keep domain infrastructure access appropriately scoped.'],[49,'TACACS+','TCP','Device-administration authentication, authorization, and accounting.'],[1812,'RADIUS Authentication','UDP','Network access authentication and authorization.'],[1813,'RADIUS Accounting','UDP','Accounting records for network access sessions.'],[500,'IKE','UDP','Internet Key Exchange for IPsec negotiation.'],[4500,'IPsec NAT Traversal','UDP','IPsec encapsulation when traversing network address translation.'],[6514,'Syslog over TLS','TCP','Protected transport for syslog with TLS.'],
    [20,'FTP Data','TCP','Legacy file transfer data channel; cleartext.'],[21,'FTP Control','TCP','Legacy FTP control channel; cleartext.'],[22,'SSH / SFTP / SCP','TCP','Secure remote shell and secure file transfer.'],[23,'Telnet','TCP','Insecure cleartext remote terminal.'],[25,'SMTP','TCP','Email transfer between mail systems.'],[53,'DNS','UDP/TCP','Name resolution; UDP common, TCP for larger responses/zone transfers.'],[67,'DHCP Server','UDP','Server-side DHCP service.'],[68,'DHCP Client','UDP','Client-side DHCP service.'],[69,'TFTP','UDP','Trivial File Transfer Protocol; no authentication/encryption.'],[80,'HTTP','TCP','Unencrypted web traffic.'],[110,'POP3','TCP','Legacy mail retrieval; cleartext unless separately secured.'],[123,'NTP','UDP','Time synchronization.'],[135,'RPC Endpoint Mapper','TCP/UDP','Microsoft RPC endpoint mapping.'],[137,'NetBIOS Name','UDP','Legacy NetBIOS name service.'],[138,'NetBIOS Datagram','UDP','Legacy NetBIOS datagrams.'],[139,'NetBIOS Session','TCP','Legacy SMB over NetBIOS.'],[143,'IMAP','TCP','Mail retrieval/synchronization.'],[161,'SNMP','UDP','Network monitoring queries.'],[162,'SNMP Trap','UDP','SNMP notifications/traps.'],[389,'LDAP','TCP/UDP','Directory services; plaintext unless protected.'],[443,'HTTPS','TCP','HTTP over TLS.'],[445,'SMB','TCP','Windows file/printer sharing and related services.'],[465,'SMTPS','TCP','SMTP over implicit TLS in many environments.'],[514,'Syslog','UDP','Traditional syslog transport.'],[587,'SMTP Submission','TCP','Client mail submission, typically with STARTTLS.'],[636,'LDAPS','TCP','LDAP over TLS.'],[993,'IMAPS','TCP','IMAP over TLS.'],[995,'POP3S','TCP','POP3 over TLS.'],[1433,'Microsoft SQL Server','TCP','Microsoft SQL Server database traffic.'],[1521,'Oracle Listener','TCP','Oracle database listener.'],[3306,'MySQL','TCP','MySQL database service.'],[3389,'RDP','TCP/UDP','Remote Desktop Protocol.'],[5060,'SIP','TCP/UDP','VoIP signaling, commonly unencrypted.'],[5061,'SIPS','TCP','SIP over TLS.']
  ]
};
