(()=>{
const F=(key,label,options,answer,why,group='Tasks')=>({key,label,options,answer,why,group});
const tf=(key,label,answer,why)=>F(key,label,['True','False'],answer?'True':'False',why);
const controls=['Security officer','RFID badge','Access control vestibule','Biometric scanner','CCTV','Bollards'];
const attacks=['Botnet','Remote access trojan (RAT)','Worm','Virus','Keylogger','Backdoor','SQL injection','Spyware'];
const remedies=['Enable DDoS protection','Disable unnecessary remote access services','Patch vulnerable systems','Implement phishing-resistant MFA','Conduct a code review','Change display resolution'];
const labs=[];
labs.push({id:1,title:'Attack and remediation matching',objective:'2.4',brief:'For each of five descriptions, select the attack and the best preventative or remediation action. Not every option is used.',fields:[
F('a1','Web server: SYN packets arrive from many sources',attacks,'Botnet','A botnet supplies distributed sources for the SYN flood.'),F('r1','Web server: best response',remedies,'Enable DDoS protection','Distributed denial-of-service filtering reduces flood traffic.'),
F('a2','User: a connection permits remote commands',attacks,'Remote access trojan (RAT)','A RAT provides malicious remote control.'),F('r2','User: best response',remedies,'Disable unnecessary remote access services','Remove the unauthorized remote-control path; investigate and eradicate the malware.'),
F('a3','Database: self-propagating malware spreads using known credentials',attacks,'Worm','Self-propagation is the defining worm behavior. The reference image labels this Virus; the behavior supports Worm.'),F('r3','Database: best response among these choices',remedies,'Patch vulnerable systems','Patch exploitable services and replace known/default credentials. Neither measure alone covers every propagation method.'),
F('a4','Executive: hardware captures keyboard input',attacks,'Keylogger','A hardware keylogger records input.'),F('r4','Executive: reduce stolen-password usefulness',remedies,'Implement phishing-resistant MFA','A captured reusable password alone should not grant access. Remove the device and rotate exposed secrets as part of response.'),
F('a5','Application: hidden access bypasses the normal login',attacks,'Backdoor','The hidden access path bypasses normal authentication.'),F('r5','Application: best preventative review',remedies,'Conduct a code review','Review can expose unauthorized authentication bypass code.')],note:'Two technical corrections to the supplied example: self-propagating malware is a worm; phishing-resistant MFA is stronger than push approval alone.'});
labs.push({id:2,title:'Infection origin investigation',objective:'4.8',brief:'Inspect every host and the firewall logs. Identify the origin separately from each host’s present status. Click a node to inspect it, or type show in the analyst terminal.',terminal:'infection',nodes:['192.168.10.22','192.168.10.37','192.168.10.41','Firewall','10.10.9.12','10.10.9.18'],fields:[F('origin','Origin host',['192.168.10.22','192.168.10.37','192.168.10.41','10.10.9.12','10.10.9.18','Insufficient evidence'],['192.168.10.37','Insufficient evidence'],'The supplied completed example identifies this host as origin. The abbreviated logs alone do not conclusively prove the origin; correlate all available timestamps.'),...['192.168.10.22','192.168.10.37','192.168.10.41','10.10.9.12','10.10.9.18'].map((ip,i)=>F(ip,ip,['Infected','Clean'],[0,2,4].includes(i)?'Infected':'Clean',[0,2,4].includes(i)?'Security services are disabled or quarantine fails, indicating active compromise.':'The provided evidence shows successful quarantine. In real response, validate removal before declaring a host clean.'))]});
const rules3=[['1','Any','172.16.20.75','TCP','8080','Block'],['2','Any','Any','UDP','67','Allow'],['3','Any','Any','TCP','21','Block'],['4','Any','172.16.20.75','TCP','443','Allow'],['5','172.16.20.0/24','172.16.10.10','UDP','69','Allow'],['6','Any','Any','TCP','3306','Allow'],['7','Any','Any','TCP','25','Allow']];
labs.push({id:3,title:'Firewall interpretation I',objective:'4.5',brief:'Evaluate the statements against this ruleset. Assume required routing, return traffic, DNS and unrelated services are working; evaluate only the service permissions shown. Rule order is top to bottom.',table:{headers:['Rule','Source','Destination','Protocol','Port','Action'],rows:rules3},fields:[tf('mail','I can send email to 172.16.20.10.',true,'SMTP TCP 25 is permitted by rule 7.'),tf('web','I cannot view the website at 172.16.20.75.',false,'HTTPS TCP 443 is allowed even though TCP 8080 is blocked.'),tf('files','I cannot transfer files from 172.16.20.10 to 172.16.10.10.',false,'TFTP UDP 69 is allowed from that source subnet.'),tf('dhcp','The shown rules allow my lobby laptop to request DHCP configuration.',true,'UDP 67 is allowed. This alone does not prove internet access; routing, DNS and egress also matter.')]});
labs.push({id:4,title:'Firewall interpretation II',objective:'4.5',brief:'Use implicit deny for unmatched new connections. Assume routing and replies for allowed sessions work.',table:{headers:['Rule','Source','Destination','Protocol','Port','Action'],rows:[['1','Any','192.168.10.101','TCP','22','Allow'],['2','Any','Any','UDP','53','Allow'],['3','Any','Any','UDP','123','Allow'],['4','192.168.20.0/24','192.168.10.103','TCP','3389','Allow']]},fields:[tf('web','I can browse Google using normal HTTPS.',false,'No TCP 443 permit is present.'),tf('time','I can update the clock on 192.168.20.101 using NTP.',true,'UDP 123 is allowed.'),tf('rdp','I can connect by RDP to 192.168.20.1.',false,'The RDP destination is restricted to 192.168.10.103.'),tf('sftp','I can transfer files securely from 192.168.1.102 to 192.168.10.101.',true,'SSH-based SFTP uses the permitted TCP 22.'),tf('dns','I can resolve google.com using a normal UDP DNS query.',true,'UDP 53 is allowed, independently of web browsing.')]});
labs.push({id:5,title:'Physical security placement',objective:'1.2',brief:'Assign all six controls to the facility. Select two controls at the main entrance and two at the server-room entrance. Each control is used once.',fields:[F('lobby1','Control 1',controls,['Security officer','Access control vestibule'],'An officer can verify visitors and handle exceptions.','Main entrance'),F('lobby2','Control 2',controls,['Security officer','Access control vestibule'],'A vestibule reduces tailgating.','Main entrance'),F('generator','Control',controls,'Bollards','Bollards resist vehicles.','Generator'),F('server1','Control 1',controls,['RFID badge','Biometric scanner'],'A badge is a possession credential.','Server room'),F('server2','Control 2',controls,['RFID badge','Biometric scanner'],'Biometrics verify a physical characteristic.','Server room'),F('parking','Control',controls,'CCTV','Video provides monitoring and recorded evidence.','Parking')],nodes:['Main entrance','Generator','Server room','Parking']});
const addr=['Any','192.168.1.100','192.168.1.200','192.168.1.10','10.10.10.0/24'];
const ruleFields=(prefix,rows,addresses)=>rows.flatMap((r,i)=>['Action','Protocol','Source','Destination','Port'].map((name,j)=>F(prefix+i+'-'+j,name, j===0?['Allow','Deny']:j===1?['TCP','UDP','Any']:j===4?['443','20-21','25','3389','53','Any']:addresses,r[j],r[5],`Rule ${i+1}`)));
labs.push({id:6,title:'Build a firewall ruleset',objective:'4.5',brief:'Allow inbound HTTPS to 192.168.1.100; block all inbound FTP; allow SMTP to 192.168.1.200; permit RDP only from 10.10.10.0/24; allow UDP DNS to 192.168.1.10; deny all remaining inbound traffic. Preserve the six-row order.',fields:ruleFields('r',[['Allow','TCP','Any','192.168.1.100','443','HTTPS requires TCP 443 to the web host.'],['Deny','TCP','Any','Any','20-21','FTP control and active data use TCP 21 and 20.'],['Allow','TCP','Any','192.168.1.200','25','SMTP relay uses TCP 25.'],['Allow','TCP','10.10.10.0/24','Any','3389','Restrict RDP sources to the IT subnet.'],['Allow','UDP','Any','192.168.1.10','53','Use the DNS address in the stated requirement; the example completed row contains a typo.'],['Deny','Any','Any','Any','Any','The final deny enforces the listed exceptions.']],addr)});
const cloud=['Autoscaling instance','Database','Instance','Load balancer','WAF'];
labs.push({id:7,title:'Secure cloud architecture',objective:'3.2',brief:'Complete every position in the payment-service architecture. Traffic enters through the edge control, crosses redundant public controls, then reaches the application and database tiers. Choose the missing middle subnet type.',nodes:['Edge','Public tier','Application tier','Data tier'],fields:[F('edge','Top edge component',cloud,'WAF','A web application firewall inspects inbound application requests.','Edge'),F('public1','Public tier position A',cloud,'WAF','The supplied architecture shows redundant WAF positions.','Public tier'),F('public2','Public tier position B',cloud,'WAF','Redundant inspection nodes reduce a single-node failure point.','Public tier'),F('balance','Before application instances',cloud,'Load balancer','Distributes traffic across the application tier.','Application tier'),...['A','B','C'].map(x=>F('app'+x,'Application instance '+x,cloud,'Autoscaling instance','Autoscaling application nodes handle load and replacement.','Application tier')),F('subnet','Middle subnet type',['Public subnet','Private subnet'],'Private subnet','Application nodes do not need direct public exposure.','Application tier'),F('db','Bottom private tier',cloud,'Database','The database belongs in the isolated data tier.','Data tier')],note:'The reference uses redundant WAF nodes; cloud provider implementation details may differ.'});
const vpnFields=[];for(let p=1;p<=2;p++){let g='Peer '+p;vpnFields.push(F(g+'ip','Remote peer IP',['5.5.5.10','5.5.5.20'],p===1?'5.5.5.20':'5.5.5.10','Each gateway points to the opposite public peer.',g+' · Phase 1'),F(g+'auth','Authentication',['PSK','Certificate','None'],'PSK','The scenario specifies a shared secret.',g+' · Phase 1'),F(g+'mode','Negotiation',['Main','Aggressive'],'Main','Main mode is the stronger choice among these legacy IKEv1 options.',g+' · Phase 1'),F(g+'enc1','Encryption',['AES256','DES','3DES'],'AES256','AES-256 is the strongest listed encryption choice.',g+' · Phase 1'),F(g+'hash1','Hash',['SHA256','SHA1','MD5'],'SHA256','SHA-256 is the strongest listed hash choice.',g+' · Phase 1'),F(g+'dh','DH group',['2','5','14'],'14','Group 14 is the strongest available group in this scenario.',g+' · Phase 1'),F(g+'tunnel','IPsec mode',['Tunnel','Transport'],'Tunnel','Gateway-to-gateway protection encapsulates the original IP packet.',g+' · Phase 2'),F(g+'protocol','Protocol',['ESP','AH'],'ESP','ESP provides encryption; AH does not.',g+' · Phase 2'),F(g+'enc2','Encryption',['AES256','DES','3DES'],'AES256','Both peers must agree on their proposal.',g+' · Phase 2'),F(g+'hash2','Hash',['SHA256','SHA1','MD5'],'SHA256','Both peers must agree on the integrity algorithm.',g+' · Phase 2'),F(g+'local','Local network',['192.168.1.0/24','192.168.2.0/24'],p===1?'192.168.1.0/24':'192.168.2.0/24','Local selectors identify this branch LAN.',g+' · Phase 2'),F(g+'remote','Remote network',['192.168.1.0/24','192.168.2.0/24'],p===1?'192.168.2.0/24':'192.168.1.0/24','Remote selectors identify the opposite branch LAN.',g+' · Phase 2'));}
labs.push({id:8,title:'Site-to-site VPN configuration',objective:'3.2',brief:'Configure both concentrators. Branch 1: public 5.5.5.10, LAN 192.168.1.0/24. Branch 2: public 5.5.5.20, LAN 192.168.2.0/24. Select the strongest listed algorithms, encrypt traffic, and authenticate with a pre-shared key. The exercise preserves the supplied IKEv1 settings.',fields:vpnFields,nodes:['Peer 1 · Phase 1','Peer 1 · Phase 2','Peer 2 · Phase 1','Peer 2 · Phase 2']});
const web=['Switch','Router','Web server','PKI certificate','WAF','Firewall'];
labs.push({id:9,title:'Web security and OpenSSL',objective:'1.4',brief:'A website assessment finds traversal, scripting, request-forgery and insecure-protocol risks. Place the supplied architecture controls, then type a command to create an RSA-2048 key and CSR. Use example.com as the generic domain.',terminal:'openssl',nodes:['Perimeter','Routing','Inspection','Web service','Trust'],fields:[F('edge','Internet boundary',web,'Firewall','The boundary filters network access.','Perimeter'),F('router','Routing component',web,'Router','The router forwards between networks.','Routing'),F('waf','Web request inspection',web,'WAF','WAF inspection adds protection against malicious web payloads.','Inspection'),F('server','Application host',web,'Web server','This component serves the application.','Web service'),F('cert','TLS trust material',web,'PKI certificate','A valid certificate supports authenticated TLS.','Trust')]});
const mitigation=['Code review','Record-level access control','WAF','URL filtering','Input validation','Unused'];
labs.push({id:10,title:'Web attack investigation',objective:'2.4',brief:'Inspect the response captured on the attacker tablet. Identify the attack shown in the completed example, or identify the evidence limitation, and place the five supplied controls. Some positions must remain unused.',evidence:'REQUEST: not visible in the supplied screenshots.\nRESPONSE: Welcome to your online games. Thanks for logging in.\nuser,cookie-id,login-time\npete,12351235adf8966eaf,2012-03-21 15:34:34\nmatt,efda838a321f23213,2012-03-21 15:37:34\nsara,123e13afd358fa7499d,2012-03-21 15:39:34',nodes:['Attacker tablet','Source repository','Web server','Database','CRM server'],fields:[F('attack','Attack type',['SQL injection','Cross-site scripting','XML injection','Session hijacking','Insufficient evidence'],['Session hijacking','Insufficient evidence'],'The completed reference selects session hijacking, but the response alone does not establish how access occurred. Insufficient evidence is also accepted.','Attacker tablet'),F('code','Repository control',mitigation,'Code review','Code review checks authentication and session handling.','Source repository'),F('code2','Repository spare position',mitigation,'Unused','Only the available controls are placed once.','Source repository'),F('web1','Web control 1',mitigation,'WAF','A WAF provides compensating request inspection.','Web server'),F('web2','Web control 2',mitigation,'URL filtering','This preserves the supplied control placement; secure session handling still requires application fixes.','Web server'),F('db1','Database input boundary',mitigation,'Input validation','Validation belongs at the data-entry boundary and complements parameterized queries.','Database'),F('db2','Database spare position',mitigation,'Unused','Not every position receives a control.','Database'),F('crm1','CRM authorization',mitigation,'Record-level access control','Restricts which records each authenticated identity may access.','CRM server'),F('crm2','CRM spare position',mitigation,'Unused','Not every position receives a control.','CRM server')]});
labs.push({id:11,title:'Passwordless SSH setup',objective:'4.6',brief:'Use the minimum command sequence to create a key pair, install only the public key on user@server, and verify a passwordless login. Type show for available commands. Commands cannot be reused.',terminal:'ssh',fields:[]});
labs.push({id:12,title:'Command-output compromise analysis',objective:'4.8',brief:'Inspect both scripts in the terminal and classify the compromise. Type show for the commands exposed by this simulation.',terminal:'compromise',fields:[F('script1','file1.sh',['SQL injection','RAT','Backdoor','Logic bomb','Rootkit'],'Logic bomb','Destructive database action is triggered when an account is absent.'),F('script2','file2.sh',['SQL injection','RAT','Backdoor','Logic bomb','Rootkit'],'Backdoor','The netcat listener exposes a shell. The EICAR download is a test artifact, not the source of that backdoor behavior.')]});
const drFields=[];const drAddr=['ANY','10.0.0.1/24','10.0.1.1/24','192.168.0.1/24'];
for(let n=1;n<=3;n++){const host=drAddr[n];const rows=[['DNS Rule',n===3?host:'ANY','ANY','DNS','PERMIT'],['HTTPS Outbound',host,'ANY','HTTPS','PERMIT'],['Management','ANY','ANY','SSH','PERMIT'],['HTTPS Inbound','ANY',host,'HTTPS',n===2?'DENY':'PERMIT'],['HTTP Inbound','ANY',host,'HTTP','DENY']];for(let i=0;i<rows.length;i++){const row=rows[i];['Source','Destination','Service','Action'].forEach((label,j)=>drFields.push(F(`fw${n}-${i}-${j}`,row[0]+' · '+label,j<2?drAddr:j===2?['DNS','HTTPS','HTTP','SSH','TELNET','RDP']:['PERMIT','DENY'],row[j+1],i===1?'Outbound rules use the local host as source and external destinations.':i===2?'SSH replaces insecure management. Production policy should also restrict management sources.':i===4?'Deny cleartext HTTP.':i===0?'Permit DNS so clients can resolve names.':n===2?'The mail host is not a public web service in this scenario.':'Permit inbound HTTPS to the web host.',`Firewall ${n}`)));}}
labs.push({id:13,title:'Disaster-recovery firewall troubleshooting',objective:'4.5',brief:'Correct each firewall without reordering its five rules. Deny cleartext inbound web traffic, use secure management, and restore DR web access. Datacenter router: 10.0.0.254/24. DR router: 192.168.0.254/24. Host identifiers preserve the supplied interface notation.',nodes:['Firewall 1','Firewall 2','Firewall 3'],fields:drFields,note:'The supplied example reverses source/destination on one outbound rule. This exercise checks correct outbound direction. Management-source restriction is an additional production hardening step.'});
window.PBQ_CASES=labs;
})();
