// Response controls transcribed from the supplied v1.8 PDF. The PDF remains the displayed question.
window.MESSER_PBQS=(()=>{
 const f=(label,options,answer)=>({label,options,answer});
 const rows=(labels,options,answers)=>labels.map((label,i)=>f(label,options,answers[i]));
 const group=(label,options,answer)=>({label,options,answer,multiple:true});
 const attacks=['On-path','RFID cloning','Keylogger','Vishing','Rootkit','DDoS','Injection','Supply chain'];
 const physical=['Security guard','Authentication token','Access badge','Lighting','Access control vestibule','Fencing','Biometrics'];
 const factors=['Somewhere you are','Something you have','Something you are','Something you know'];
 const mobile=['Host-based firewall','MDM integration','Infrared sensors','Anti-malware','OSINT','Full device encryption','Biometric authentication'];
 return {
 A1:rows(['Attacker accesses a database directly from a web browser','Attacker intercepts all communication between a client and a web server','Attacker obtains bank account number and birth date by calling the victim','Multiple attackers overwhelm a web server','Attacker obtains a list of all login credentials used over the last 24 hours'],attacks,['Injection','On-path','Vishing','DDoS','Keylogger']),
 A2:[group('Reception — Building lobby',physical,['Security guard','Access control vestibule']),group('Outside Building — Parking and Visitor drop-off',physical,['Lighting','Fencing']),group('Data Center Door — Entrance from inside building',physical,['Biometrics','Access badge']),group('Server Administration — Authentication to server console in the data center',physical,['Authentication token'])],
 A3:rows(['A guard checks the identification of all visitors','All returns must be approved by a Vice President','A generator is used during a power outage','Building doors can be unlocked with an access card','System logs are transferred automatically to a SIEM'],['Managerial','Operational','Technical','Physical'],['Operational','Managerial','Physical','Physical','Technical']),
 A4:rows(['During the login process, your phone receives a text message with a one-time passcode','You enter your PIN to make a deposit into an ATM','You can use your fingerprint to unlock the door to the data center','Your login will not work unless you are connected to the VPN'],factors,['Something you have','Something you know','Something you are','Somewhere you are']),
 A5:[['10.1.1.2','10.2.1.20','TCP','80','Block'],['10.2.1.33','10.1.1.7','TCP','443','Allow'],['10.2.1.47','10.1.1.3','TCP','22','Allow']].flatMap((r,i)=>r.map((answer,j)=>f('Rule '+(i+1)+' · '+['Source IP','Destination IP','Protocol (TCP/UDP)','Port #','Allow/Block'][j],j===2?['TCP','UDP']:j===4?['Allow','Block']:null,answer))),
 B1:rows(['A list of invalidated certificates','Send the public key to be signed','Deploy and manage certificates','The browser checks for a revoked certificate'],['CRL','OCSP','CA','CSR'],['CRL','CSR','CA','OCSP']),
 B2:[group('Tablet for Field Sales',mobile,['MDM integration','Full device encryption','Biometric authentication']),group('Desktop with Browser-based Front-end',mobile,['Host-based firewall','Anti-malware'])],
 B3:rows(['1','2','3','4','5','6','7'].map(n=>'Position '+n),['Eradication','Recovery','Preparation','Analysis','Containment','Lessons learned','Detection'],['Preparation','Detection','Analysis','Containment','Eradication','Recovery','Lessons learned']),
 B4:rows(['Store a password on an authentication server','Verify a sender’s identity','Authenticate the server sending an email','Store keys with a third-party','Prevent data corruption when a system fails','Modify a script to make it difficult to understand'],['Hashing','Digital signature','SPF','Key escrow','Journaling','Obfuscation'],['Hashing','Digital signature','SPF','Key escrow','Journaling','Obfuscation']),
 B5:rows(['All switches in a data center are connected with an 802.1Q trunk','Sales information is uploaded daily from a remote site using a satellite network','A company stores customer purchase information in a MySQL database','An application decrypts credit card numbers and expiration dates to validate for approval','An authentication program performs a hash of all passwords','An IPS identifies a SQL injection attack and removes the attack frames from the network','An automatic teller machine validates a user’s PIN before allowing a deposit','Each time a spreadsheet is updated, all of the cells containing formulas are automatically updated','All weekly backup tapes are transported to an offsite storage facility','All user spreadsheets are stored on a cloud-based file sharing service'],['Data in-transit','Data at-rest','Data in-use'],['Data in-transit','Data in-transit','Data at-rest','Data in-use','Data in-use','Data in-transit','Data in-use','Data in-use','Data at-rest','Data at-rest']),
 C1:rows(['Use a secure terminal to connect to 10.1.10.88','Share the desktop on server 10.1.10.120','Perform a DNS query from 10.1.10.88 to 9.9.9.9','View web pages on 10.1.10.120','Authenticate to an LDAP server at 10.1.10.61','Synchronize the clock on a server at 10.1.10.17'],['ALLOWED','BLOCKED'],['ALLOWED','BLOCKED','ALLOWED','ALLOWED','BLOCKED','ALLOWED']),
 C2:rows(['Block SQL injection over an Internet connection','Intercept all browser requests and cache the results','Forward packets between separate VLANs','Configure a group of redundant web servers','Evaluate the input to a browser-based application'],['WAF','Proxy server','Load balancer','Sensor','MDM','Router','Jump server','IPS'],['IPS','Proxy server','Router','Load balancer','WAF']),
 C3:rows(['A website stops responding to normal requests','Data is captured and retransmitted to a server','The malware is designed to remain hidden on a computer system','A list of passwords are attempted with a known username','An email link redirects a user to a site that requests login credentials','Permissions are circumvented by adding additional code as application input'],['DDoS','Replay','Rootkit','Brute force','Phishing','Injection'],['DDoS','Replay','Rootkit','Brute force','Phishing','Injection']),
 C4:rows(['Create a stronger key using multiple processes','Data is hidden within another media type','Different inputs create the same hash','Sensitive data is hidden from view','A different key is used for decryption than encryption','Information is added to make a unique hash'],['Salting','Steganography','Masking','Asymmetric','Collision','Key stretching'],['Key stretching','Steganography','Collision','Masking','Asymmetric','Salting']),
 C5:rows(['A field service engineer uses their corporate laptop at coffee shops and hotels','Software developers run a series of tests before deploying an application','An administrator prevents employees from visiting known-malicious web sites','Directly access cloud-based services from all corporate locations','Users connecting to the network should use their corporate authentication credentials'],['VPN','NGFW','802.1X','SD-WAN','Sandboxing'],['VPN','Sandboxing','NGFW','SD-WAN','802.1X'])
 };
})();
