/* Shared question reflections. No answer keys are used here. */
window.REASONING=(()=>{
 const reasons={guess:'I guessed',acronym:'Unfamiliar acronym',concept:'Don’t understand the technology',two:'Stuck between choices',wording:'Wording / missing detail',confidence:'Second-guessing',deeper:'Want deeper study',logs:'Cannot interpret the log / evidence'};
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function get(a,id){return a.reflections?.[id]||{reasons:[],note:'',eliminated:[],confidence:''}}
 function ensure(a,id){a.reflections??={};return a.reflections[id]??={reasons:[],note:'',eliminated:[],confidence:''}}
 function panel(a,id,locked=false){const r=get(a,id);return `<section class="reflection" aria-label="Your reasoning"><h3>What’s going through your head?</h3><p>Choose any reasons that fit. These do not change your score.</p><div class="reason-chips">${Object.entries(reasons).map(([k,v])=>`<label><input type="checkbox" data-reason="${k}" ${r.reasons?.includes(k)?'checked':''} ${locked?'disabled':''}> ${v}</label>`).join('')}</div><label>Confidence <select data-confidence ${locked?'disabled':''}><option value="">Not recorded</option>${['Confident','Unsure','Guessing'].map(v=>`<option ${r.confidence===v?'selected':''}>${v}</option>`).join('')}</select></label><label>Your notes<textarea data-reason-note rows="3" placeholder="Why this answer? What did you rule out? What was confusing?" ${locked?'readonly':''}>${esc(r.note)}</textarea></label><small data-note-status>${locked?'Saved with this attempt':'Notes save as you type.'}</small></section>`}
 function bind(root,a,id,save){root.querySelectorAll('[data-reason]').forEach(el=>el.onchange=()=>{const r=ensure(a,id);r.reasons=[...root.querySelectorAll('[data-reason]:checked')].map(e=>e.dataset.reason);a.flags??={};if(r.reasons.length)a.flags[id]=true;save()});const note=root.querySelector('[data-reason-note]');if(note)note.oninput=()=>{ensure(a,id).note=note.value;save();root.querySelector('[data-note-status]').textContent='Saved on this device';};const confidence=root.querySelector('[data-confidence]');if(confidence)confidence.onchange=()=>{ensure(a,id).confidence=confidence.value;save()}}
 function eliminate(a,id,value){const r=ensure(a,id);r.eliminated??=[];r.eliminated=r.eliminated.includes(value)?r.eliminated.filter(x=>x!==value):[...r.eliminated,value]}
 function summary(a,id,options){const r=get(a,id),has=a.flags?.[id]||r.note||r.reasons?.length||r.eliminated?.length||r.confidence;if(!has)return '<p class="muted">No reasoning recorded for this question.</p>';return `<div class="reflection-summary"><b>Your reasoning</b><p>${a.flags?.[id]?'Flagged · ':''}${esc(r.confidence||'Confidence not recorded')}</p><p>${(r.reasons||[]).map(k=>esc(reasons[k]||k)).join(' · ')}</p>${r.note?`<p class="saved-note">${esc(r.note)}</p>`:''}${r.eliminated?.length?`<p>Crossed out: ${r.eliminated.map(v=>esc(options?.[v]??v)).join(' · ')}</p>`:''}</div>`}
 function analytics(a,results){const rows=results||a.results||[],recorded=rows.filter(x=>a.reflections?.[x.id]),uncertain=rows.filter(x=>{const r=get(a,x.id);return a.flags?.[x.id]||r.reasons?.length||['Unsure','Guessing'].includes(r.confidence)}),confidentWrong=rows.filter(x=>x.credit<1&&get(a,x.id).confidence==='Confident');return `<section class="card reasoning-analytics"><h3>Understanding behind the score</h3><p>${recorded.length}/${rows.length} questions with reasoning recorded · ${uncertain.filter(x=>x.credit===1).length} correct but flagged / uncertain · ${confidentWrong.length} confident misses</p><div class="reason-counts">${Object.entries(reasons).map(([k,v])=>{const rs=rows.filter(x=>get(a,x.id).reasons?.includes(k));return rs.length?`<span>${v}: <b>${rs.length}</b> (${rs.filter(x=>x.credit===1).length} correct)</span>`:''}).join('')}</div><p>Unrecorded confidence is unknown. Correct guesses remain review priorities.</p></section>`}
 function guard(messages,proceed){if(!messages.length){proceed();return}const dialog=document.createElement('dialog');dialog.className='skip-dialog';dialog.innerHTML=`<h2>Before you move on</h2><ul>${messages.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><p>You can leave an answer blank intentionally. No answers have been checked for correctness.</p><div class="btn-row"><button class="btn primary" data-return autofocus>Return to question</button><button class="btn secondary" data-skip>Skip intentionally</button></div>`;document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove());dialog.querySelector('[data-return]').onclick=()=>dialog.close();dialog.querySelector('[data-skip]').onclick=()=>{dialog.close();proceed()};dialog.showModal();dialog.querySelector('[data-return]').focus()}
 return {reasons,get,ensure,panel,bind,eliminate,summary,analytics,guard};
})();
