window.createSchoolUI = function(api) {
  const {getState,save,esc,showModal,closeModal,startQuiz,go,videoList,bindVideos,openReview,toast}=api;
  const C=CURRICULUM,V=MESSER_VIDEOS,S=SCHOOL,P=PRELEARNING,$=s=>document.querySelector(s);
  const state=()=>getState(), model=()=>S.overview(state(),C,V), fmt=S.time;
  const score=h=>h?`${h.percent}%`:'—';
  const badge=o=>`<span class="readiness r${o.priority}">${esc(o.level)}</span>`;
  const lessonStatus=o=>o.complete?'✓ Lessons complete':o.watched?'Watching / studying':'Not started';
  const sign=n=>n===null?'—':`${n>0?'+':''}${n} points`;
  function metrics(m){
    const s=state();s.studyPlan??={speed:1,minutes:30};const speed=Number(s.studyPlan.speed)||1,minutes=Number(s.studyPlan.minutes)||30;
    const post=s.history.filter(h=>!S.pre(h)).flatMap(h=>h.results||[]).filter(r=>!r.lab&&C.objectives.some(o=>o.id===r.objective));
    const average=post.length?(100*post.reduce((sum,r)=>sum+r.credit,0)/post.length).toFixed(1)+'%':'—';
    const evidence=`<div class="performance-strip"><span><b>${average}</b> post-learning accuracy across ${post.length} answers</span><span><b>${m.objectives.filter(o=>o.latest).length}/28</b> objectives with post-check evidence</span><small>Excludes pre-checks and PBQs; repeated questions may inflate familiarity.</small></div>`;
    return `<div class="school-metrics"><article><small>Video time remaining · 1×</small><strong>${fmt(m.left)}</strong><span>${fmt(m.watched)} watched / ${fmt(m.total)} total</span></article><article><small>Lesson completion</small><strong>${m.completed} / 28</strong><span>${28-m.completed} objectives left</span></article><article><small>Domains completed</small><strong>${m.domainsDone} / 5</strong><span>${5-m.domainsDone} domains left</span></article><article><small>Priority review</small><strong>${m.review.length}</strong><span>Post-check below 85% or manually flagged</span></article></div><div class="study-budget"><label>Playback speed <select id="studySpeed" class="select">${[1,1.25,1.5,1.75,2].map(v=>`<option ${v===speed?'selected':''} value="${v}">${v}×</option>`).join('')}</select></label><label>Video minutes per session <select id="studyMinutes" class="select">${[15,30,45,60,90].map(v=>`<option ${v===minutes?'selected':''} value="${v}">${v} min</option>`).join('')}</select></label><p><b id="pacedTime">${fmt(m.left/speed)}</b> of playback remaining at this speed · <b id="sessionCount">${Math.ceil(m.left/speed/(minutes*60))}</b> video sessions.<br><small>Video-only estimate; reading, quizzes, breaks, and review require additional time. Watched checkmarks, not the completion label, control this timer.</small></p></div>${evidence}`;
  }
  function timeline(m){return `<section class="card"><h2>Course timeline</h2><p>Introduction → pre-check → videos → post-check → targeted review → retention check</p><div class="domain-timeline">${m.domains.map(d=>`<button data-domain="${d.id}" class="domain-stop ${d.completed===d.count?'done':''}"><span class="domain-number">${d.id}</span><strong>${esc(SECPLUS_DATA.domains.find(x=>x.id===d.id).name)}</strong><span>${fmt(d.total)} total</span><span>${fmt(d.left)} left</span><div class="progress"><span style="width:${d.total?100*d.watched/d.total:0}%"></span></div><small>${d.completed}/${d.count} objectives complete · ${d.review} priority reviews</small></button>`).join('')}</div></section>`;}
  function queue(m){return `<section class="card"><h2>Your next review lessons</h2><p>Most recent evidence per concept drives this list. A high overall score can still leave a specific distinction to review.</p>${m.queue.length?m.queue.slice(0,6).map(o=>`<div class="review-task"><div><strong>${o.id} · ${esc(o.title)}</strong><p>${esc(o.misses.map(x=>x.concept).join(' · ')||'Your manually flagged review')}</p><small>Latest post-check ${score(o.latest)} · ${esc(o.action)}</small></div><button class="btn primary" data-focus="${o.id}">Focused lesson</button></div>`).join(''):'<p>No unresolved missed concepts yet. Begin the next objective or complete a post-video check to build evidence.</p>'}</section>`;}
  function matrix(rows){return `<div class="matrix-wrap"><table class="school-matrix"><thead><tr><th>Objective / lesson status</th><th>Videos left</th><th>Pre-check</th><th>Set A</th><th>Set B</th><th>Set C</th><th>Latest post / trend</th><th>Learning signal / next action</th></tr></thead><tbody>${rows.map(o=>`<tr><td><button class="objective-open" data-open-obj="${o.id}"><strong>${o.id} · ${esc(o.title)}</strong><span>${lessonStatus(o)}</span></button></td><td>${fmt(o.left)}<small>${fmt(o.total)} total</small></td><td>${score(o.baseline)}</td>${['A','B','C'].map(k=>`<td>${o.bySet[k]?`<button class="score-link" data-attempt="${o.bySet[k].id}">${score(o.bySet[k])}</button>`:'—'}</td>`).join('')}<td>${score(o.latest)}<small>${o.trend===null?'No prior post-check':sign(o.trend)+' vs prior'}</small><small>${o.delta===null?'':sign(o.delta)+' vs pre-check'}</small></td><td>${badge(o)}<small>${esc(o.action)}</small>${o.misses.length?`<button class="score-link" data-focus="${o.id}">${o.misses.length} concept${o.misses.length===1?'':'s'} to revisit</button>`:''}</td></tr>`).join('')}</tbody></table></div>`;}
  function rules(){return `<details class="card"><summary>How the learning matrix works</summary><p><b>Below 70%:</b> a focused lesson before retesting. <b>70–84%:</b> reinforce missed distinctions. <b>85% or above:</b> strong evidence on that check, not a guarantee of readiness. Two distinct sets at 85% or above, with lessons complete and the latest check still at least 85%, move an objective to “Retain & revisit.”</p><p>Each A/B/C cell shows its latest attempt, not its best score. Pre-checks are diagnostic and excluded from post-learning averages and weak-area ranking. The pre/post difference compares different questions and is a rough learning signal, not a controlled measurement. Correct retests on the same questions can reflect memory; use another set after a break.</p><p>Marking an objective complete records lesson completion, not mastery. Review flags do not erase completed learning. No practice percentage is converted into CompTIA’s scaled score.</p></details>`;}
  function common(current){
    document.querySelectorAll('.school-matrix').forEach(table=>{const labels=[...table.querySelectorAll('th')].map(x=>x.textContent);table.querySelectorAll('tbody tr').forEach(row=>[...row.children].forEach((cell,i)=>cell.dataset.column=labels[i]));});
    document.querySelectorAll('[data-open-obj]').forEach(b=>b.onclick=()=>objective(b.dataset.openObj));
    document.querySelectorAll('[data-focus]').forEach(b=>b.onclick=()=>focus(b.dataset.focus));
    document.querySelectorAll('[data-attempt]').forEach(b=>b.onclick=()=>openReview(state().history.find(h=>String(h.id)===b.dataset.attempt)));
    document.querySelectorAll('[data-domain]').forEach(b=>b.onclick=()=>{if(current!=='learn')go('learn');document.querySelector('#domain-'+b.dataset.domain)?.scrollIntoView({behavior:'smooth',block:'start'})});
    if($('#studySpeed'))for(const id of ['studySpeed','studyMinutes'])$('#'+id).onchange=()=>{state().studyPlan={speed:+$('#studySpeed').value,minutes:+$('#studyMinutes').value};save();const m=model();$('#pacedTime').textContent=fmt(m.left/state().studyPlan.speed);$('#sessionCount').textContent=Math.ceil(m.left/state().studyPlan.speed/(state().studyPlan.minutes*60));};
  }
  function dashboard(){
    const m=model(),next=m.objectives.find(o=>!o.complete),s=state();api.title('Your learning dashboard','Prepare → Watch → Apply → Review → Retain');
    $('#content').innerHTML=`<div class="grid">${metrics(m)}<section class="card"><div class="kicker">NEXT CLASS</div><h2>${next?next.id+' · '+esc(next.title):'All objectives studied — consolidate with mixed practice'}</h2><p>${next?'Start with the introductory lesson and its diagnostic check, then watch the assigned videos. Completed sections remain available for reinforcement.':'Lesson completion is one milestone. Keep using the review queue, distinct practice sets, and full exams.'}</p><div class="btn-row">${next?`<button class="btn primary" data-open-obj="${next.id}">Open next class</button>`:''}<button class="btn secondary" id="deskButton">Professor Desk & full matrix</button>${s.active?'<button class="btn primary" id="resumeSchool">Resume saved attempt</button>':''}</div></section>${timeline(m)}${queue(m)}${rules()}</div>`;
    common('dashboard');$('#deskButton').onclick=()=>go('learn');if($('#resumeSchool'))$('#resumeSchool').onclick=()=>go('quiz');
  }
  function learn(){
    const m=model();api.title('Professor Desk','Video timeline, class progression, and evidence-based review');
    $('#content').innerHTML=`<div class="grid">${metrics(m)}${timeline(m)}${queue(m)}${m.domains.map(d=>`<section class="card domain-section" id="domain-${d.id}"><div class="section-head"><div><div class="kicker">DOMAIN ${d.id} · ${SECPLUS_DATA.domains[d.id-1].weight}% OF EXAM BLUEPRINT</div><h2>${esc(SECPLUS_DATA.domains[d.id-1].name)}</h2><p>${fmt(d.total)} of videos · ${fmt(d.watched)} watched · <b>${fmt(d.left)} left</b></p></div><span class="tag">${d.completed}/${d.count} lessons complete</span></div>${matrix(d.rows)}</section>`).join('')}${rules()}</div>`;common('learn');
  }
  function summary(o){return `<div class="objective-metrics"><span>${lessonStatus(o)}</span><span>${fmt(o.left)} video left</span><span>Pre ${score(o.baseline)}</span><span>Post ${score(o.latest)}</span>${badge(o)}</div>`;}
  function setStatus(id,value){const s=state(),o=s.objectives[id]??={};o.status=value;if(value==='complete'){o.learningComplete=true;for(const v of V[id]||[])s.videos[v.url]=true;}else if(value==='new'||value==='studying')o.learningComplete=false;save();}
  function objective(id,tab){
    const o=C.objectives.find(x=>x.id===id),m=S.objective(state(),id,V),intro=P[id];tab??=m.complete?'practice':'intro';
    const nav=[['intro','1 · Introduction'],['watch','2 · Videos'],['practice','3 · Post-checks'],['review','4 · Review & notes']];
    let body='';
    if(tab==='intro')body=`<section class="card"><div class="kicker">BEFORE THE VIDEOS · FOUNDATION, NOT A GATE</div><h2>Start here: ${esc(o.title)}</h2><h3>What to bring with you</h3><p class="teaching-copy">${esc(intro.bridge)}</p><h3>The model to understand</h3><p class="teaching-copy">${esc(intro.teach)}</p><div class="flow">${o.flow.map((t,i)=>`<div><b>${i+1}</b>${esc(t)}</div>`).join('')}</div><div class="example"><b>Worked example</b><p>${esc(intro.example)}</p></div><h3 class="watch-heading">Listen for these distinctions</h3><ul>${intro.watch.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><details><summary>Foundation vocabulary, expanded</summary>${o.concepts.map(c=>`<p><b>${esc(c.label)}</b> — ${esc(c.definition)}</p>`).join('')}</details><div class="btn-row"><button class="btn primary" id="preStart">Take pre-video check · 10 questions</button><button class="btn secondary" id="introRead">${state().intros[id]?.read?'✓ Introduction read':'Mark introduction read'}</button><button class="btn secondary" data-class-tab="watch">Continue to videos</button></div><p class="muted">${m.baseline?'Latest diagnostic: '+m.baseline.percent+'%. ':''}This establishes a baseline; it does not lower your post-learning score. You can continue even if you miss questions. Already watched? Use it as a foundation check; it cannot reconstruct your earlier knowledge.</p></section>`;
    if(tab==='watch')body=videoList(id)+`<section class="card"><h3>After watching</h3><p>Explain the key distinctions in your own words, then take a post-video set without consulting the notes.</p><button class="btn primary" data-class-tab="practice">Continue to post-video practice</button></section>`;
    if(tab==='practice')body=`<section class="card"><h2>Apply it after the videos</h2><p>${esc(o.tip)}</p><div class="grid three">${[1,2,3].map(n=>`<article class="practice-stage"><h3>Set ${'ABC'[n-1]}</h3><p>${n===1?'First post-video check':n===2?'Reinforcement after targeted review':'Retention check after a break'}</p><strong>${score(m.bySet['ABC'[n-1]])}</strong><button class="btn primary" data-mini="${n}">${m.bySet['ABC'[n-1]]?'Retake':'Start'} · 10 questions</button></article>`).join('')}</div><p>All three sets remain available. Prefer an unused set after reviewing; repeated scores on the same questions are not independent evidence.</p><button class="btn secondary" data-focus="${id}">Open your focused review lesson</button></section><details class="card"><summary>Revisit the section’s concept explanations</summary><div class="grid two">${o.concepts.map(c=>`<article class="example"><h3>${esc(c.label)}</h3><p>${esc(c.definition)}</p><p>${esc(c.cases[0])}</p></article>`).join('')}</div></details>`;
    if(tab==='review')body=`<section class="card"><h2>Your evidence</h2><p>${esc(m.action)}</p><p>Latest post-check: ${score(m.latest)} · All post-learning questions: ${m.average===null?'—':m.average+'%'} over ${m.attempted} answers.</p><p>Pre/post change: ${sign(m.delta)} · Latest/prior post-check: ${sign(m.trend)}.</p>${m.misses.length?`<ul>${m.misses.map(x=>`<li>${esc(x.concept)}</li>`).join('')}</ul>`:'<p>No unresolved missed concepts recorded.</p>'}<button class="btn primary" data-focus="${id}">Teach me the missed distinctions</button></section><section class="card"><label for="objectiveNotes">Your notes and confusing wording</label><textarea id="objectiveNotes" rows="5">${esc(state().objectives[id]?.notes||'')}</textarea><button class="btn secondary" id="saveNotes">Save notes</button></section>`;
    showModal(`${id} · ${o.title}`,`<div id="objectiveSummary">${summary(m)}</div><nav class="class-tabs" aria-label="Class stages">${nav.map(([key,text])=>`<button class="btn ${key===tab?'primary':'secondary'}" data-class-tab="${key}" aria-pressed="${key===tab}">${text}</button>`).join('')}</nav>${body}<section class="card class-status"><label for="objectiveStatus">Lesson status</label><select id="objectiveStatus" class="select">${[['new','Not started'],['studying','Studying'],['review','Flag for review'],['complete','Lessons complete']].map(([k,t])=>`<option value="${k}" ${state().objectives[id]?.status===k?'selected':''}>${t}</option>`).join('')}</select><p>“Lessons complete” also marks this objective’s videos watched. It does not declare mastery or hide review needs. Individual video checkmarks can be changed afterward.</p></section>`);
    document.querySelectorAll('[data-class-tab]').forEach(b=>b.onclick=()=>objective(id,b.dataset.classTab));
    $('#objectiveStatus').onchange=e=>{setStatus(id,e.target.value);$('#objectiveSummary').innerHTML=summary(S.objective(state(),id,V));background();};
    if(tab==='intro'){$('#preStart').onclick=()=>{closeModal();startQuiz(P[id].questions,'Pre-video '+id+' · Foundation check')};$('#introRead').onclick=()=>{state().intros[id]={...state().intros[id],read:true,at:Date.now()};save();$('#introRead').textContent='✓ Introduction read'}};
    if(tab==='watch'){bindVideos(id);document.querySelectorAll('[data-video]').forEach(b=>{const old=b.onchange;b.onchange=()=>{old();$('#objectiveSummary').innerHTML=summary(S.objective(state(),id,V));background()}})}
    document.querySelectorAll('[data-mini]').forEach(b=>b.onclick=()=>{closeModal();startQuiz(C.questions.filter(q=>q.objective===id&&q.set===+b.dataset.mini),`${id} · Set ${'ABC'[+b.dataset.mini-1]}`)});
    document.querySelectorAll('[data-focus]').forEach(b=>b.onclick=()=>focus(b.dataset.focus));
    if($('#saveNotes'))$('#saveNotes').onclick=()=>{state().objectives[id]={...state().objectives[id],notes:$('#objectiveNotes').value};save();toast('Notes saved')};
  }
  function background(){if(api.page()==='learn')learn();else if(api.page()==='dashboard')dashboard();}
  function focus(id){
    const o=C.objectives.find(x=>x.id===id),m=S.objective(state(),id,V),p=P[id];
    showModal(`${id} · Focused review lesson`,`<section class="card"><div class="kicker">RETEACH → DISTINGUISH → APPLY</div><h2>${esc(o.title)}</h2><p>${esc(p.teach)}</p><div class="example"><b>Worked reasoning</b><p>${esc(p.example)}</p></div>${state().objectives[id]?.notes?`<div class="feedback"><b>Your own observation</b><p>${esc(state().objectives[id].notes)}</p></div>`:''}</section>${m.misses.map(x=>{const c=o.concepts.find(c=>c.label===x.concept),q=x.question;return `<section class="card"><h3>${esc(x.concept)}</h3><p>${esc(c?.definition||q.explanations[q.correct])}</p><div class="example"><b>A different application</b><p>${esc(c?.cases[1]||p.example)}</p></div><h4>What your last answer showed</h4><p>${esc(q.prompt)}</p><p>Your answer: ${esc(q.options[x.answer]||'Unanswered')}<br>Best answer: ${esc(q.options[q.correct])}</p>${q.options.map((v,n)=>`<details><summary>${esc(v)}${n===q.correct?' — best answer':''}</summary><p>${esc(q.explanations[n])}</p></details>`).join('')}</section>`}).join('')||'<section class="card"><p>No missed concepts are currently unresolved. Use the section’s post-checks to gather more evidence.</p></section>'}<section class="card"><h3>Now reinforce it</h3><p>Restate the distinction aloud, then use the next unused set. If all sets are used, choose a retention attempt after a break.</p><div class="btn-row"><button class="btn primary" id="focusNext">${(()=>{const k=['A','B','C'].find(k=>!m.bySet[k]);return k?'Take unused Set '+k:'Choose a retention check'})()}</button><button class="btn secondary" id="focusWatch">Revisit assigned videos</button></div></section>`);
    $('#focusNext').onclick=()=>{const k=['A','B','C'].find(k=>!m.bySet[k]);if(k){closeModal();startQuiz(C.questions.filter(q=>q.objective===id&&q.set==='ABC'.indexOf(k)+1),`${id} · Set ${k}`)}else objective(id,'practice')};$('#focusWatch').onclick=()=>objective(id,'watch');
  }
  return {dashboard,learn,objective,focus};
};
