/* Authored lessons and revised bank. Stored attempts keep their original question snapshots. */
window.STUDY_GUIDES=(()=>{
 const data=REBUILT_CONTENT,esc=REASONING? s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])):String;
 const refs={
  '1.4':[['NIST: key management','https://csrc.nist.gov/projects/key-management']],
  '4.4':[['NIST: SCAP','https://csrc.nist.gov/projects/security-content-automation-protocol'],['CISA: logging','https://www.cisa.gov/audiences/small-and-medium-businesses/secure-your-business/use-logging-on-business-systems']],
  '4.5':[['Cloudflare: SPF, DKIM, and DMARC','https://www.cloudflare.com/learning/email-security/dmarc-dkim-spf/']],
  '4.9':[['CISA: logging','https://www.cisa.gov/audiences/small-and-medium-businesses/secure-your-business/use-logging-on-business-systems']],
  '5.5':[['NIST SP 800-115: assessment techniques','https://csrc.nist.gov/pubs/sp/800/115/final'],['Messer: reconnaissance and testing','https://www.professormesser.com/security-plus/sy0-701/sy0-701-video/penetration-tests-sy0-701/']]
 };
 CURRICULUM.questions=Object.values(data).flatMap(m=>m.questions);
 function render(id){const m=data[id];if(!m)return '';const o=CURRICULUM.objectives.find(x=>x.id===id),videos=MESSER_VIDEOS[id]||[];const sources=[...(refs[id]||[]),...videos.slice(0,4).map(v=>[v.title,v.url])];return `<section class="card study-guide"><div class="kicker">REBUILT STUDY GUIDE · ${id}</div><h2>${esc(o.title)}: understand before memorizing</h2><p>Read the mechanism, work through the example, and compare the alternatives. The new A/B/C sets test these distinctions with separate scenarios. Original Messer exams keep their source wording and scoring.</p>${m.teach.map((p,i)=>`<h3>${i===0?'How it works':'Where the similar answers separate'}</h3><p>${esc(p)}</p>`).join('')}<h3>A decision path</h3><div class="guide-flow">${m.flow.map((step,i)=>`<div><b>${i+1}</b>${esc(step)}</div>`).join('')}</div><h3>Worked application</h3><div class="guide-case"><p>${esc(m.example)}</p></div><h3>Compare the mechanisms</h3><p>For each term, explain the problem it solves and why the nearest alternative would not solve the same problem.</p>${m.terms.map(([term,description])=>`<details><summary>${esc(term)}</summary><p>${esc(description)}</p></details>`).join('')}<h3>Explain it before checking yourself</h3><p>Which detail in the scenario establishes the requirement? What does the selected mechanism actually do? What additional fact would make your second choice correct? Record uncertainty in the quiz notes; a correct guess still belongs in review.</p>${id==='4.9'||id==='2.4'?logLesson():''}${id==='4.5'?emailLesson():''}<details><summary>References and further reading</summary><ul>${sources.map(([t,u])=>`<li><a href="${esc(u)}" target="_blank" rel="noopener">${esc(t)}</a></li>`).join('')}</ul><p>Written lessons work offline. External references and videos require a connection. These are original teaching explanations, not a prediction of live exam questions.</p></details></section>`}
 function logLesson(){return `<h3>Read evidence one field at a time</h3><pre>2026-09-29T14:08:11Z host=auth02
src=192.0.2.18 user=svc_reports result=failed
attempts=420 distinct_users=1 distinct_passwords=420</pre><table><thead><tr><th>Field</th><th>What it establishes</th></tr></thead><tbody><tr><td>Time ending in Z</td><td>UTC timestamp; normalize other sources before comparing.</td></tr><tr><td>host=auth02</td><td>The reporting system. It is not automatically the attacker's host.</td></tr><tr><td>src=192.0.2.18</td><td>The observed origin. Proxies or address translation can limit attribution.</td></tr><tr><td>user / result</td><td>The targeted identity and failed outcome. Failure is not a successful compromise.</td></tr><tr><td>One user, 420 candidates</td><td>Supports concentrated password guessing. One password across many users would instead support spraying.</td></tr></tbody></table><details><summary>What can you conclude? What remains unknown?</summary><p>Brute-force guessing is supported by the explicit account/password distribution. These failures alone do not prove the attacker ever authenticated. Check later success records and related endpoint activity before claiming account compromise.</p></details><pre>src=198.51.100.22:80 -> dst=10.0.4.9:53112
sensor=edge02 action=blocked signature=trojan_download</pre><details><summary>Trace the direction and result</summary><p>The recorded traffic runs from source port 80 toward a high client port. It is consistent with a web-server response to a client. The sensor reports blocking that detected traffic. It does not establish that an entire host is clean, that another path did not succeed, or that the detector cannot be wrong. Correlate session and endpoint records.</p></details><pre>method=POST path=/feedback src=192.0.2.77
input=&lt;script&gt;alert(1)&lt;/script&gt; action=blocked</pre><details><summary>Connect the content to the detector</summary><p>The script markup in submitted input supports an attempted cross-site scripting pattern. 'Blocked' is evidence of the local control's action, not proof of successful script execution. A database-query payload would point to a different execution target.</p></details>`}
 function emailLesson(){return `<h3>Follow one email</h3><div class="guide-flow"><div><b>SPF</b>Is this sending system authorized for the checked mail domain?</div><div><b>DKIM</b>Does the domain-associated signature verify the signed content?</div><div><b>DMARC</b>Does a passing result align with the visible From domain, and what policy applies?</div></div><pre>header.from=example.test
spf=pass smtp.mailfrom=vendor.test
dkim=pass header.d=example.test</pre><details><summary>Work through alignment</summary><p>SPF passing for vendor.test does not by itself align with example.test. DKIM passing for example.test does align. DMARC can pass through that aligned DKIM result; both mechanisms need not pass with alignment. Neither result encrypts the message or guarantees the sender's requested action is safe.</p></details>`}
 return {data,render};
})();
