/* Targeted practice keeps imported evidence and reflections on the user's device. */
window.createTargetedUI=function(api){
 'use strict';
 const tracks=window.TARGETED_TRACKS,esc=api.esc,$=s=>document.querySelector(s),root=()=>$('#content');
 let current=null,stage='map',visualMode=0,reviewAttempt=null;
 const button=(label,attr,primary=false)=>`<button class="btn ${primary?'primary':'secondary'}" ${attr}>${label}</button>`;
 const store=()=>{const s=api.getState();s.targeted??={version:1,lessons:{},attempts:[],active:null};s.targeted.lessons??={};s.targeted.attempts??=[];return s.targeted};
 const lesson=t=>(store().lessons[t.id]??={});
 const track=id=>tracks.find(t=>t.id===id);
 const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
 function source(){try{const m=JSON.parse(localStorage.getItem('security-plus-messer-v1')||'null');return (m?.history||[]).filter(h=>h.exam==='B'&&Array.isArray(h.results)).sort((a,b)=>(b.finished||0)-(a.finished||0))[0]||null}catch{return null}}
 function meaningful(r){return !!(r&&(r.note?.trim()||r.reasons?.length||r.eliminated?.length||r.confidence))}
 function uncertain(a,id){const r=a.reflections?.[id]||{};return !!(a.flags?.[id]||r.reasons?.length||['Unsure','Guessing','Somewhat confident'].includes(r.confidence))}
 const eq=(a,b)=>Array.isArray(b)?Array.isArray(a)&&a.length===b.length&&b.every(v=>a.includes(v)):a===b;
 function evidence(t,h=source()){
  if(!h)return [];
  return Object.entries(t.refs).flatMap(([id,fields])=>{const r=h.results.find(r=>r.id===id);if(!r)return [];const ref=h.reflections?.[id]||{};
   if(fields&&window.MESSER_PBQS?.[id]){const defs=MESSER_PBQS[id];const bad=fields.filter(i=>defs[i]&&!eq(h.answers?.[id]?.[i],defs[i].answer));return bad.length?[{id,miss:true,pbq:true,detail:`${bad.length}/${fields.length} relevant response groups differ from the key`,note:ref.note||'',reasons:ref.reasons||[],fields:bad}]:[]}
   if(r.credit<1||uncertain(h,id))return [{id,miss:r.credit<1,pbq:false,detail:r.credit<1?'Missed':'Correct, flagged / uncertain',note:ref.note||'',reasons:ref.reasons||[],eliminated:ref.eliminated||[],confidence:ref.confidence||''}];return [];
  })
 }
 function latest(t){return store().attempts.filter(a=>a.track===t.id).sort((a,b)=>b.finished-a.finished)[0]}
 function pending(a){return (a?.results||[]).filter(r=>r.credit!==1||uncertain(a,r.id)||a.reflections?.[r.id]?.confidence!=='Confident')}
 function rank(t){const base=evidence(t).reduce((n,e)=>n+(e.pbq?2:e.miss?3:1),0),a=latest(t);return a?pending(a).length*3+base/10:base}
 function status(t){const a=latest(t);if(!a)return 'Not checked yet';const n=pending(a).length;return n?`${n} answers to reinforce`:'Confident on this check'}
 function shell(){api.title('Targeted Lab','See the mechanism → distinguish the choices → apply it');root().classList.add('target-root')}
 function home(){current=null;reviewAttempt=null;shell();const h=source(),active=store().active;const rs=h?.results||[],miss=rs.filter(r=>r.credit<1),flag=rs.filter(r=>h.flags?.[r.id]),correctFlag=rs.filter(r=>r.credit===1&&uncertain(h,r.id));const mc=rs.filter(r=>Number(r.id.slice(1))>5),pbq=rs.filter(r=>Number(r.id.slice(1))<=5);const scored=rs.reduce((n,r)=>n+r.credit,0);const order=[...tracks].sort((a,b)=>rank(b)-rank(a));
 root().innerHTML=`<section class="card target-hero"><div class="kicker">YOUR TARGETED STUDY PLAN</div><h2>Learn the distinction that changes the answer.</h2><p>Eight focused segments. Each has an interactive visual, a worked scenario, a comparison of nearby choices, and ten original questions.</p><p>These are targeted exam-concept lessons, not scores of video retention. The final three questions in each check test clearly labeled transfer material taught first.</p>${active?button('Resume saved targeted check','data-resume',true):''}</section>
 <section class="card"><h2>Evidence behind your priorities</h2>${h?`<div class="target-kpis"><div><strong>${scored}/${rs.length}</strong><span>Exam B · ${(100*scored/rs.length).toFixed(1)}%</span></div><div><strong>${mc.reduce((n,r)=>n+r.credit,0)}/${mc.length}</strong><span>Multiple-choice</span></div><div><strong>${pbq.reduce((n,r)=>n+r.credit,0)}/${pbq.length}</strong><span>Fully correct PBQs</span></div><div><strong>${miss.length+correctFlag.length}</strong><span>Missed or correct-but-uncertain</span></div></div><p>${miss.length} missed · ${flag.length} flagged · ${correctFlag.length} correct but flagged / uncertain. ${Object.values(h.reflections||{}).filter(r=>r.note?.trim()).length} typed notes. Empty reflection records do not count as recorded reasoning.</p><small>Latest completed Exam B on this device, ${new Date(h.finished).toLocaleDateString()}. PBQ subparts guide lessons but do not change the original score. A PBQ can support more than one segment; segment counts are not additive. Unrecorded confidence is unknown.</small>`:'<p>No completed Exam B is saved in this installation. Import your export to rank the segments and display your own notes. The lessons work without importing.</p>'}<details class="target-import"><summary>Import Exam B evidence from a backup</summary><p>Adds missing Messer attempts on this device. Existing attempts, active exams and course progress are kept.</p><label class="file-label">Choose your Security+ JSON export<input id="targetImport" type="file" accept=".json,application/json"></label><p id="targetImportStatus" role="status"></p></details></section>
 <div class="target-track-grid">${order.map((t,i)=>{const ev=evidence(t,h),a=latest(t);return `<article class="card target-track"><div class="kicker">${ev.length?'PRIORITY '+(i+1):'REINFORCEMENT'} · ${esc(t.objectives.join(' / '))}</div><h2>${esc(t.title)}</h2><p>${esc(t.hook)}</p><p class="target-evidence">${ev.length?ev.map(e=>`${e.id} ${e.pbq?'subparts':e.miss?'missed':'uncertain'}`).join(' · '):'No mapped miss / uncertainty in this export; available for reinforcement.'}</p><p><b>${status(t)}</b>${a?` · ${a.results.filter(r=>r.credit===1).length}/${a.results.length} last check`:''}</p><div class="btn-row">${button('Open visual lesson',`data-track="${t.id}"`,true)}${a?button('Review check',`data-review="${a.id}"`):''}</div></article>`}).join('')}</div><section class="card"><h3>How this narrows the work</h3><p>Review priorities come from missed answers and recorded uncertainty. The new checks track each distinction, notes, crossed-out choices and confidence. A correct guess stays in your review list. Repeating these same questions measures familiarity, not independent exam readiness.</p></section>`;
 root().querySelectorAll('[data-track]').forEach(b=>b.onclick=()=>open(b.dataset.track));root().querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>result(store().attempts.find(a=>a.id===b.dataset.review)));root().querySelector('[data-resume]')?.addEventListener('click',quiz);$('#targetImport').onchange=importEvidence;
 }
 async function importEvidence(e){try{const f=e.target.files[0];if(!f)return;if(f.size>20*1024*1024)throw Error('Choose a backup smaller than 20 MB.');const j=JSON.parse(await f.text()),m=j.messerExams;if(j.app!=='security-plus-school'||m?.version!==1||!Array.isArray(m.history)||!m.history.some(h=>h.exam==='B'&&Array.isArray(h.results)))throw Error('Choose a Security+ export containing completed Messer Exam B.');let local;try{local=JSON.parse(localStorage.getItem('security-plus-messer-v1')||'null')}catch{}local=local?.version===1&&Array.isArray(local.history)?local:{version:1,history:[],active:null};const ids=new Set(local.history.map(h=>h.id));for(const h of m.history){if(h.id&&!ids.has(h.id)&&Array.isArray(h.results)){local.history.push(h);ids.add(h.id)}}localStorage.setItem('security-plus-messer-v1',JSON.stringify(local));home();api.toast('Exam evidence imported on this device')}catch(err){$('#targetImportStatus').textContent=err.message}}
 function evidencePanel(t){const ev=evidence(t);return `<details class="card"><summary>Why this segment is on your plan${ev.length?' · '+ev.length+' mapped questions':''}</summary><p>${esc(t.why)}</p>${ev.map(e=>`<div class="target-source"><b>${e.id} · ${esc(e.detail)}</b>${e.note?`<blockquote>${esc(e.note)}</blockquote>`:''}${e.reasons.length?`<p>${e.reasons.map(r=>esc(REASONING.reasons[r]||r)).join(' · ')}</p>`:''}${e.eliminated?.length?`<small>Crossed out in the original attempt: ${e.eliminated.map(esc).join(', ')}</small>`:''}</div>`).join('')||'<p>No mapped missed/uncertain evidence is present on this device. This lesson remains available as reinforcement.</p>'}</details>`}
 function node(label,detail,cls=''){return `<div class="target-node ${cls}"><b>${label}</b><span>${detail}</span></div>`}
 function path(nodes){return `<div class="target-path">${nodes.join('<span class="target-arrow" aria-hidden="true">→</span>')}</div>`}
 function visual(t){
 const selectors=(items)=>`<div class="btn-row target-switch" role="group" aria-label="Explore the visual">${items.map((s,i)=>`<button class="btn ${visualMode===i?'primary':'secondary'}" data-mode="${i}" aria-pressed="${visualMode===i}">${s}</button>`).join('')}</div>`;
 if(t.id==='pki')return `${selectors(['Direct OCSP check','OCSP stapling'])}<figure class="target-diagram"><figcaption>Who gets the revocation status?</figcaption>${visualMode===0?path([node('Client','Needs status'),node('OCSP responder','Returns signed status'),node('Client','Verifies response')]):path([node('OCSP responder','Signs status'),node('Server','Fetches and staples status'),node('Client','Verifies stapled response')])}<p class="target-callout">${visualMode===0?'The client contacts the responder separately.':'The client avoids its own responder request. It must still validate the signature, freshness and certificate trust.'}</p><div class="target-boundary">Separate responsibility: <b>TPM / HSM</b> protects keys. <b>CSR / CA / CRL / OCSP</b> belongs to the certificate lifecycle.</div></figure>`;
 if(t.id==='access')return `${selectors(['Network admission','Admin access','Web protection'])}<figure class="target-diagram"><figcaption>${['Who may join?','How does the technician reach management?','Where is malicious web input inspected?'][visualMode]}</figcaption>${[path([node('Laptop','Supplicant'),node('Switch / AP','Authenticator'),node('RADIUS','AAA service'),node('Directory','Identity source')]),path([node('Technician','Authenticates'),node('Jump server','Controlled admin hop'),node('Internal device','Management interface')]),path([node('Web client','HTTP request'),node('WAF','Inspect web input'),node('Application','Process allowed request')])][visualMode]}<p class="target-callout">${['LDAP can serve directory lookups behind RADIUS. It is not a replacement for the 802.1X exchange.','NAC can evaluate device admission. The jump server supplies the administration path.','UTM bundles capabilities; WAF names the specific web-request inspection role.'][visualMode]}</p></figure>`;
 if(t.id==='data')return `${selectors(['Stored','Crossing a link','Being calculated','Token vs mask'])}<figure class="target-diagram"><figcaption>Follow the data operation</figcaption>${visualMode<3?path([node('Disk / database','AT REST',visualMode===0?'selected':''),node('Network link','IN TRANSIT',visualMode===1?'selected':''),node('Memory + CPU','IN USE',visualMode===2?'selected':'')]):`<div class="target-lanes">${path([node('Sensitive value','Stored in protected vault'),node('tok_84','Transaction substitute')])}${path([node('Account display','Actual number held elsewhere'),node('**** 4821','Masked view only')])}</div>`}<p class="target-callout">${['A backup drive stays data at rest even when the drive is in a moving vehicle.','Electronic transfer across a link is in transit; physical movement of storage is different.','Decrypting and calculating values is processing: data in use.','A token stands in for a value in a workflow. Masking only conceals the view.'][visualMode]}</p></figure>`;
 if(t.id==='email')return `<figure class="target-diagram"><figcaption>Try the DMARC decision</figcaption><p>Visible From domain: <b>plant.example</b></p><div class="target-email-inputs"><label>SPF result<select id="emailSPF"><option value="aligned">Pass · plant.example</option><option value="other">Pass · unrelated.example</option><option value="fail">Fail</option></select></label><label>DKIM result<select id="emailDKIM"><option value="aligned">Pass · plant.example</option><option value="other">Pass · unrelated.example</option><option value="fail">Fail</option></select></label></div>${path([node('SPF path','Authorized host + alignment'),node('OR','One aligned pass is enough'),node('DKIM path','Verified signature + alignment')])}<p id="emailVerdict" class="target-callout" role="status"></p><small>This demonstrates authentication alignment, not malware safety or a guarantee of message delivery.</small></figure>`;
 if(t.id==='response')return `${selectors(['Corporate connection','Cellular hotspot'])}<figure class="target-diagram"><figcaption>Which sensor is on the path?</figcaption>${path([node('Laptop','Host agent / firewall','selected'),node(visualMode?'Cellular hotspot':'Corporate gateway',visualMode?'Bypasses corporate sensor':'Gateway can observe'),node('Internet','Destination')])}${visualMode?node('Corporate gateway','Not on this route: no matching flow records expected','muted-node'):''}<p class="target-callout">${visualMode?'Investigate enabled host telemetry. No gateway record does not prove that the connection never happened.':'Both endpoint and gateway may supply evidence; what is recorded depends on enabled telemetry.'}</p></figure><div class="target-log"><b>Tap a log clue</b>${[['10:11 GET /admin 404','A requested directory returned not found; do not infer a successful compromise.'],['10:11 GET /backup.zip 404','A different file is probed: repeated resource discovery suggests enumeration.'],['10:11 GET /.env 403','The server refused this request. A denial does not establish that every other request was denied.']].map(([l,n],i)=>`<button data-log="${i}" data-explain="${esc(n)}"><code>${esc(l)}</code></button>`).join('')}<p id="logExplain" role="status">Look at what changes between requests, then read the response.</p></div>`;
 if(t.id==='governance')return `${selectors(['Who is who?','Insurance continues','Insurance ends','Activity ends'])}<figure class="target-diagram"><figcaption>${visualMode?'Classify the new decision':'Separate authority, operation and the person described'}</figcaption>${visualMode===0?`<div class="target-lanes">${path([node('Business owner','Protection requirements'),node('Custodian','Runs backups')])}${path([node('Data subject','Person described'),node('Controller','Purpose / means'),node('Processor','Acts on instructions')])}</div>`:path([node('Business activity',visualMode===3?'Stopped':'Continues'),node('Loss exposure',['','Some cost transferred by insurance','Retained internally','This activity’s exposure removed'][visualMode]),node('Risk response',['','TRANSFER','ACCEPTANCE','AVOIDANCE'][visualMode],'selected')])}<p class="target-callout">${['One organization can hold multiple roles. Choose the particular responsibility described.','Insurance can shift some financial consequences; it does not eliminate the technical risk.','Canceling insurance while continuing the activity retains the uninsured exposure.','Avoidance stops the risk-producing activity. It does not merely stop paying for coverage.'][visualMode]}</p></figure>`;
 if(t.id==='assets')return `${selectors(['Asset inventory','Public information','Target probes','Isolation boundary'])}<figure class="target-diagram"><figcaption>${['Enumeration: list, then compare','Existing information','Direct interaction','Guest isolation'][visualMode]}</figcaption>${[path([node('Yesterday','Drive serial: A104'),node('Today','Drive serial: B992','selected'),node('Difference','Hardware changed')]),path([node('Public report','Already published'),node('Analyst','Reads the report'),node('OSINT','Information gathered')]),path([node('Tester','Sends probes'),node('Target','Responds'),node('Discovery','Active reconnaissance')]),path([node('Guest VM','Restricted resources'),node('Isolation boundary','Exploit crosses it','selected'),node('Host','Unauthorized access')])][visualMode]}<p class="target-callout">${['Enumeration itself lists components. Comparison is what reveals change; neither implies a second login factor.','Gathering public information does not itself mean data was stolen from a protected system.','A tester can have full documents and still use active probes. Knowledge level and technique are separate.','An escape breaks isolation. Normal guest resource access is not an escape.'][visualMode]}</p></figure>`;
 return `${selectors(['External adversary','Insider already present'])}<figure class="target-diagram"><figcaption>Change one fact; reconsider the best fit</figcaption>${path([node('Actor access',visualMode?'Already inside':'Remote only'),node('Available route',visualMode?'Unattended authenticated terminal':'Public vulnerable database','selected'),node('Decision','Prioritize the supported path')])}<p class="target-callout">${visualMode?'Physical/session controls now match the supplied access. Do not keep ranking as if the attacker were outside.':'The public path needs fewer invented access conditions than the isolated internal system.'}</p></figure>`;
 }
 function bindVisual(t){root().querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{visualMode=+b.dataset.mode;renderLesson()});if(t.id==='email'&&$('#emailSPF')){const update=()=>{const a=$('#emailSPF').value,b=$('#emailDKIM').value;$('#emailVerdict').textContent=a==='aligned'||b==='aligned'?'DMARC authentication: PASS — at least one passing method aligns with plant.example.':'DMARC authentication: FAIL — no passing method aligns with plant.example.'};$('#emailSPF').onchange=update;$('#emailDKIM').onchange=update;update()}root().querySelectorAll('[data-log]').forEach(b=>b.onclick=()=>{$('#logExplain').textContent=b.dataset.explain;root().querySelectorAll('[data-log]').forEach(x=>x.classList.toggle('selected',x===b))})}
 function open(id){current=track(id);stage='map';visualMode=0;renderLesson();window.scrollTo(0,0)}
 function renderLesson(){shell();const t=current,ls=lesson(t);const tabs=[['map','1 · Visual model'],['worked','2 · Worked example'],['compare','3 · Compare choices'],['practice','4 · Apply it']];
 let body='';if(stage==='map')body=`<section class="card"><h3>${esc(t.hook)}</h3>${visual(t)}<details><summary>Expand the mechanism step by step</summary><ol class="target-steps">${t.steps.map(([label,detail])=>`<li><b>${esc(label)}</b><p>${esc(detail)}</p></li>`).join('')}</ol></details></section>`;
 if(stage==='worked')body=`<section class="card target-worked"><div class="kicker">WORKED EXAMPLE · ANSWER EXPLAINED</div><h3>Start with what the scenario actually gives you.</h3><p class="target-scenario">${esc(t.worked.scenario)}</p><h4>Decisive clues</h4><ol>${t.worked.clues.map(c=>`<li>${esc(c)}</li>`).join('')}</ol><div class="target-callout"><b>${esc(t.worked.answer)}</b><p>${esc(t.worked.because)}</p></div><h4>Why the tempting alternative fails</h4><p>${esc(t.worked.trap)}</p></section>`;
 if(stage==='compare')body=`<section class="card"><h3>When would the other answer be right?</h3><p>Learn the job and the limiting clue together.</p><div class="target-compare">${t.compare.map(([name,job,fit,limit])=>`<article><h4>${esc(name)}</h4><b>${esc(job)}</b><p><span>Choose it when:</span> ${esc(fit)}</p><p><span>Distinguish it:</span> ${esc(limit)}</p></article>`).join('')}</div></section>`;
 if(stage==='practice')body=`<section class="card"><h3>Ten fresh scenarios for this segment</h3><p>Seven questions on the core distinctions above, followed by three on the transfer material below. Scores are reported separately. One question at a time; choose an answer, record confidence, then see the explanation.</p><aside class="target-transfer"><h4>Read before the transfer questions</h4><p>${esc(t.transfer)}</p></aside><p>Notes, flag reasons and cross-outs save with the check. Repeated attempts use the same ten questions in a different order.</p>${button('Start 10-question check','data-start',true)}${latest(t)?button('Review previous check',`data-review="${latest(t).id}"`):''}</section>`;
 root().innerHTML=`<div class="btn-row">${button('← All targeted segments','data-home')}</div><section class="card"><div class="kicker">TARGETED SEGMENT · ${esc(t.objectives.join(' / '))}</div><h2>${esc(t.title)}</h2><p>${esc(t.why)}</p><nav class="target-tabs" aria-label="Lesson stages">${tabs.map(([id,label])=>`<button class="btn ${stage===id?'primary':'secondary'}" data-stage="${id}" aria-current="${stage===id?'step':'false'}">${label}</button>`).join('')}</nav></section>${body}<div class="btn-row">${stage!=='practice'?button('Continue →',`data-stage="${tabs[tabs.findIndex(x=>x[0]===stage)+1][0]}"`,true):''}</div>${evidencePanel(t)}<details class="card"><summary>Your lesson notes</summary><textarea id="targetLessonNote" rows="4" aria-label="Lesson notes" placeholder="What still does not click?">${esc(ls.note||'')}</textarea><small>Saved on this device and included in your backup.</small></details><details class="card"><summary>Sources and further reading</summary><p>Original teaching examples and practice questions. References explain the underlying mechanisms. External pages require internet.</p>${t.sources.map(([name,url])=>`<p><a href="${esc(url)}" target="_blank" rel="noopener">${esc(name)}</a></p>`).join('')}</details>`;
 root().querySelector('[data-home]').onclick=home;root().querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{stage=b.dataset.stage;renderLesson();window.scrollTo(0,0)});root().querySelector('[data-start]')?.addEventListener('click',()=>start(t));root().querySelector('[data-review]')?.addEventListener('click',()=>result(latest(t)));$('#targetLessonNote').oninput=e=>{ls.note=e.target.value;api.save()};bindVisual(t);
 }
 function start(t){if(store().active&&!confirm('Replace the saved unfinished targeted check? Completed checks and other exams are kept.'))return;newAttempt(t)}
 function newAttempt(t){store().active={id:crypto.randomUUID(),track:t.id,started:Date.now(),index:0,items:[...shuffle(t.questions.filter(q=>q.scope==='core')),...shuffle(t.questions.filter(q=>q.scope==='transfer'))].map(q=>({...q,order:shuffle([0,1,2,3])})),answers:{},reflections:{},flags:{},results:[],transferReady:false};api.save();quiz()}
 function quiz(){shell();const a=store().active;if(!a){home();return}const t=track(a.track),q=a.items[a.index];if(!q){finish();return}const r=a.results.find(r=>r.id===q.id),ref=REASONING.get(a,q.id),selected=a.answers[q.id];
 if(q.scope==='transfer'&&!a.transferReady){root().innerHTML=`<section class="card"><div class="kicker">BEFORE QUESTIONS 8–10</div><h2>Transfer: one step beyond the core distinction</h2><p>${esc(t.transfer)}</p><p>These three questions are scored separately from the seven core questions.</p>${button('I’ve read this · continue','data-transfer',true)}${button('Pause and save','data-pause')}</section>`;root().querySelector('[data-transfer]').onclick=()=>{a.transferReady=true;api.save();quiz()};root().querySelector('[data-pause]').onclick=home;return}
 root().innerHTML=`<div class="target-quiz-head"><div><div class="kicker">${esc(t.title)} · ${q.scope==='core'?'CORE DISTINCTION':'TRANSFER'}</div><h2>Question ${a.index+1} of ${a.items.length}</h2></div>${button('Pause and save','data-pause')}</div><section class="card target-question"><h3>${esc(q.prompt)}</h3><div class="target-options">${q.order.map((v,i)=>`<div class="target-option-row"><button class="target-option ${selected===v?'selected':''} ${ref.eliminated?.includes(v)?'eliminated':''}" data-option="${v}" aria-pressed="${selected===v}" ${r?'disabled':''}><b>${'ABCD'[i]}</b><span>${esc(q.options[v])}</span></button><button class="target-cross" data-cross="${v}" aria-label="${ref.eliminated?.includes(v)?'Restore':'Cross out'} option ${'ABCD'[i]}" aria-pressed="${ref.eliminated?.includes(v)||false}" ${r?'disabled':''}>${ref.eliminated?.includes(v)?'Undo':'Cross out'}</button></div>`).join('')}</div>${selected!==undefined&&!r?`<fieldset class="target-confidence"><legend>How confident are you?</legend>${[['Confident','Confident'],['Unsure','Somewhat confident'],['Guessing','Guessing']].map(([v,label])=>`<label><input type="radio" name="targetConfidence" value="${v}" ${ref.confidence===v?'checked':''}> ${label}</label>`).join('')}</fieldset>`:''}
 <details class="target-reflection"><summary>Flag reasons & notes${ref.note||ref.reasons?.length?' · saved':''}</summary><div class="reason-chips">${Object.entries(REASONING.reasons).map(([key,label])=>`<label><input data-target-reason="${key}" type="checkbox" ${ref.reasons?.includes(key)?'checked':''} ${r?'disabled':''}> ${esc(label)}</label>`).join('')}</div><label>Your reasoning<textarea id="targetQuestionNote" rows="3" ${r?'readonly':''}>${esc(ref.note||'')}</textarea></label></details>${r?feedback(q,r,a):`<div class="btn-row">${button('Check answer','data-check',true)}${button('Skip intentionally','data-skip')}</div><p id="targetQuestionStatus" role="status"></p>`}</section>`;
 root().querySelector('[data-pause]').onclick=home;
 if(r){root().querySelector('[data-next]').onclick=()=>{a.index++;api.save();quiz();window.scrollTo(0,0)};return}
 root().querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>{const v=+b.dataset.option;a.answers[q.id]=v;const f=REASONING.ensure(a,q.id);f.eliminated=(f.eliminated||[]).filter(x=>x!==v);api.save();quiz()});
 root().querySelectorAll('[data-cross]').forEach(b=>b.onclick=()=>{const v=+b.dataset.cross;REASONING.eliminate(a,q.id,v);if(a.answers[q.id]===v&&REASONING.get(a,q.id).eliminated.includes(v))delete a.answers[q.id];api.save();quiz()});
 root().querySelectorAll('[name="targetConfidence"]').forEach(el=>el.onchange=()=>{REASONING.ensure(a,q.id).confidence=el.value;if($('#targetQuestionStatus'))$('#targetQuestionStatus').textContent='';api.save()});
 root().querySelectorAll('[data-target-reason]').forEach(el=>el.onchange=()=>{REASONING.ensure(a,q.id).reasons=[...root().querySelectorAll('[data-target-reason]:checked')].map(x=>x.dataset.targetReason);a.flags[q.id]=!!REASONING.get(a,q.id).reasons.length;api.save()});
 $('#targetQuestionNote').oninput=e=>{REASONING.ensure(a,q.id).note=e.target.value;api.save()};
 root().querySelector('[data-check]').onclick=()=>{if(a.answers[q.id]===undefined){REASONING.guard(['No answer is selected.'],()=>record(true));return}if(!REASONING.get(a,q.id).confidence){$('#targetQuestionStatus').textContent='Choose a confidence rating before checking.';return}record(false)};
 root().querySelector('[data-skip]').onclick=()=>REASONING.guard(['This will record this question as intentionally skipped.'],()=>record(true));
 }
 function record(skipped){const a=store().active,q=a.items[a.index];if(a.results.some(r=>r.id===q.id))return;if(skipped)delete a.answers[q.id];a.results.push({id:q.id,skill:q.skill,scope:q.scope,credit:!skipped&&a.answers[q.id]===q.correct?1:0,answer:skipped?null:a.answers[q.id],skipped,question:q});api.save();quiz()}
 function feedback(q,r,a){const f=REASONING.get(a,q.id);return `<div class="target-feedback" role="status"><h3>${r.skipped?'Skipped intentionally':r.credit===1?'Correct':'Review this distinction'}</h3><p><b>Decisive clue:</b> ${esc(q.clue)}</p><p><b>Best answer:</b> ${esc(q.options[q.correct])}</p><p>${esc(q.explanations[q.correct])}</p>${r.answer!==null&&r.answer!==q.correct?`<p><b>Your choice:</b> ${esc(q.explanations[r.answer])}</p>`:''}<p>${r.credit===1&&f.confidence!=='Confident'?'Correct but uncertain stays in your review queue.':''}</p><details><summary>Why each alternative fits or fails</summary>${q.order.filter(i=>i!==q.correct).map(i=>`<p><b>${esc(q.options[i])}:</b> ${esc(q.explanations[i])}</p>`).join('')}</details></div>${button(a.index===a.items.length-1?'Finish & see priorities':'Next question →','data-next',true)}`}
 function finish(){const s=store(),a=s.active;if(!a)return;a.finished=Date.now();s.attempts.unshift(a);s.active=null;api.save();result(a)}
 function result(a){if(!a){home();return}reviewAttempt=a;current=track(a.track);shell();const all=a.results,core=all.filter(r=>r.scope==='core'),transfer=all.filter(r=>r.scope==='transfer'),need=pending(a);const metric=(label,rows)=>`<div><strong>${rows.filter(r=>r.credit===1).length}/${rows.length}</strong><span>${label}</span></div>`;
 root().innerHTML=`<section class="card"><div class="kicker">TARGETED CHECK · ${esc(current.title)}</div><h2>${need.length?need.length+' answers to reinforce':'Confident on this check'}</h2><div class="target-kpis">${metric('Core distinctions',core)}${metric('Transfer questions',transfer)}<div><strong>${all.filter(r=>r.credit===1&&uncertain(a,r.id)).length}</strong><span>Correct but flagged / uncertain</span></div><div><strong>${all.filter(r=>r.credit===0&&a.reflections?.[r.id]?.confidence==='Confident').length}</strong><span>Confident misses</span></div></div><p>Saved ${new Date(a.finished).toLocaleString()}. This check does not change your Messer exam score or mark an entire objective mastered.</p><div class="btn-row">${button('Revisit visual lesson','data-lesson',true)}${button('All targeted segments','data-home')}</div></section><section class="card"><h3>What to work on next</h3>${need.length?`<ul>${need.map(r=>`<li><b>${esc(r.question.skill.replaceAll('-',' '))}</b> · ${r.skipped?'Skipped':r.credit!==1?'Missed':uncertain(a,r.id)?'Correct but uncertain':'Confidence unknown'}<p>${esc(r.question.clue)}</p></li>`).join('')}</ul>`:'<p>Explain the distinction without the choices, then revisit it later. A repeat uses the same questions and can reflect memory.</p>'}</section><section class="card"><h3>Review answers and your reasoning</h3>${all.map(r=>`<details class="target-review-item"><summary>${r.credit===1?'✓':'Review'} · ${esc(r.question.prompt)}</summary><p><b>Your answer:</b> ${esc(r.answer===null?'Skipped':r.question.options[r.answer])}</p><p><b>Best answer:</b> ${esc(r.question.options[r.question.correct])}</p><p><b>Clue:</b> ${esc(r.question.clue)}</p>${r.question.options.map((o,i)=>`<p><b>${esc(o)}:</b> ${esc(r.question.explanations[i])}</p>`).join('')}${REASONING.summary(a,r.id,r.question.options)}</details>`).join('')}</section>`;
 root().querySelector('[data-lesson]').onclick=()=>open(current.id);root().querySelector('[data-home]').onclick=home;window.scrollTo(0,0)
 }
 return {home,open,evidence,source,pending,start,quiz};
};
