// Run with Playwright; CHROMIUM_EXECUTABLE optionally selects a local browser.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..');
const c={window:{}};vm.createContext(c);
const old=[];
function collect(x){if(!x||typeof x!=='object')return;if(typeof x.prompt==='string')old.push(x.prompt);if(typeof x.text==='string'&&x.choices)old.push(x.text);Object.values(x).forEach(v=>{if(typeof v==='object')collect(v)})}
for(const f of ['data','curriculum','prelearning','deep-lessons','rebuilt-content','guided-data','targeted-data','messer-data']){vm.runInContext(fs.readFileSync(path.join(root,'js',f+'.js'),'utf8'),c);Object.values(c.window).forEach(collect)}
vm.runInContext(fs.readFileSync(path.join(root,'js/challenge-data.js'),'utf8'),c);
const forms=c.window.CHALLENGE_EXAMS,questions=forms.flatMap(e=>e.questions),norm=s=>s.toLowerCase().replace(/[^a-z0-9]/g,'');
assert.equal(forms.length,2);assert.equal(questions.length,200);assert.equal(new Set(questions.map(q=>q.id)).size,200);assert.equal(new Set(questions.map(q=>norm(q.prompt))).size,200);
const existing=new Set(old.map(norm));assert(questions.every(q=>!existing.has(norm(q.prompt))));
for(const form of forms){assert.equal(form.questions.length,100);assert.deepEqual([1,2,3,4,5].map(d=>form.questions.filter(q=>q.objective.startsWith(d+'.')).length),[12,22,18,28,20]);assert.equal(new Set(form.questions.map(q=>q.objective)).size,28);assert(form.questions.every(q=>q.type==='mcq'&&q.options.length===4&&new Set(q.options).size===4&&q.explanations.length===4&&q.explanations.every(e=>e.length>20)&&q.correct>=0&&q.correct<4));}
(async()=>{
 const server=require('http').createServer((req,res)=>{try{const url=new URL(req.url,'http://localhost');const file=path.join(root,url.pathname==='/'?'index.html':url.pathname);res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.pdf':'application/pdf','.json':'application/json'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end()}});
 await new Promise(r=>server.listen(8881,'127.0.0.1',r));let browser;
 try{
 browser=await chromium.launch({...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{}),headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote']});
 const context=await browser.newContext({viewport:{width:1024,height:768},hasTouch:true,acceptDownloads:true});const page=await context.newPage(),errors=[];page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));let accept=true;page.on('dialog',d=>accept?d.accept():d.dismiss());
 await page.addInitScript(()=>{if(!localStorage.getItem('challenge-test-seeded')){localStorage.setItem('security-plus-school-v4',JSON.stringify({version:4,objectives:{'1.1':{status:'complete',notes:'Keep original progress'}},history:[],labs:{},active:null}));localStorage.setItem('security-plus-messer-v1',JSON.stringify({version:1,history:[],marker:'untouched'}));localStorage.setItem('challenge-test-seeded','yes')}});
 await page.goto('http://127.0.0.1:8881/#challenge');await page.waitForFunction(()=>window.SECPLUS_TEST);assert(await page.locator('[data-challenge-start]').count()===2);
 await page.screenshot({path:'/tmp/challenge-home.png',fullPage:true});
 await page.locator('[data-challenge-start="challenge-1"]').click();
 let a=await page.evaluate(()=>SECPLUS_TEST.state().active);assert.equal(a.items.length,100);assert.equal(a.examId,'challenge-1');assert.equal(a.minutes,90);assert(a.deadline-a.started>=5399000);assert(a.items.every(q=>q.type==='mcq'));assert.notDeepEqual(a.items.map(q=>q.id),forms[0].questions.map(q=>q.id));
 const originalOrder=a.items.map(q=>({id:q.id,order:q.order})),first=a.items[0];
 assert(!(await page.locator('#content').innerText()).includes(first.explanations[first.correct]));assert((await page.locator('.quiz-meta').innerText()).includes('Mixed domains'));assert.equal(await page.locator('.review-option').count(),0);
 await page.locator('[data-action="next"]').click();assert(await page.locator('dialog.skip-dialog').isVisible());await page.locator('[data-return]').click();assert.equal(await page.evaluate(()=>SECPLUS_TEST.state().active.index),0);
 await page.locator('[data-answer="0"]').click();await page.locator('[data-cross="0"]').click();assert.equal(await page.evaluate(id=>SECPLUS_TEST.state().active.answers[id],first.id),undefined);
 await page.locator('[data-reason-note]').fill('Considering B <script>window.injected=true</script> & C');await page.locator('[data-confidence]').selectOption('Guessing');await page.locator('[data-reason="two"]').check();await page.locator('[data-action="next"]').click();await page.locator('[data-skip]').click();assert.equal(await page.evaluate(()=>SECPLUS_TEST.state().active.index),1);
 await page.reload();await page.waitForFunction(()=>window.SECPLUS_TEST);await page.locator('#challengeResume').click();a=await page.evaluate(()=>SECPLUS_TEST.state().active);assert.deepEqual(a.items.map(q=>({id:q.id,order:q.order})),originalOrder);assert(a.reflections[first.id].note.includes('<script>'));assert.equal(a.skipped[first.id],true);assert.equal(await page.evaluate(()=>window.injected),undefined);
 await page.locator('[data-answer]').first().click();await page.screenshot({path:'/tmp/challenge-question.png',fullPage:true});
 // Reject replacement and ensure resume state survives.
 await page.evaluate(()=>SECPLUS_TEST.go('challenge'));accept=false;await page.locator('[data-challenge-start="challenge-2"]').click();assert.equal(await page.evaluate(()=>SECPLUS_TEST.state().active.examId),'challenge-1');accept=true;
 // Deterministic score fixture: two misses/domain, one unanswered/domain, plus one correct guess/domain.
 const expected=await page.evaluate(()=>{const a=SECPLUS_TEST.state().active;a.answers={};a.flags={};a.reflections={};let expected=[];for(let d=1;d<=5;d++){const qs=a.items.filter(q=>q.objective.startsWith(d+'.'));qs.forEach((q,i)=>{if(i!==1)a.answers[q.id]=i===0?(q.correct+1)%4:q.correct;if(i===0)a.reflections[q.id]={confidence:'Confident',note:'Reasoned but wrong',reasons:[]};if(i===2)a.reflections[q.id]={confidence:'Guessing',note:'Review this distinction',reasons:['guess'],eliminated:[]};});expected.push({total:qs.length,correct:qs.length-2,uncertainCorrect:1,confidentWrong:1,unknown:qs.length-2})}a.index=0;SECPLUS_TEST.go('quiz');return expected});
 await page.locator('[data-action="submit"]').click();assert((await page.locator('#modal').innerText()).includes('5 unanswered'));await page.locator('[data-action="keep"]').click();await page.locator('[data-action="submit"]').click();await page.locator('[data-action="finish"]').click();
 let h=await page.evaluate(()=>SECPLUS_TEST.state().history[0]);assert.equal(h.percent,90);assert.equal(h.results.length,100);assert.equal(h.examId,'challenge-1');assert.equal(h.previouslySeen,0);assert.equal(await page.locator('.challenge-report tbody tr').count(),5);
 const actual=await page.evaluate(()=>CHALLENGE.breakdown(SECPLUS_TEST.state().history[0]).map(({total,correct,uncertainCorrect,confidentWrong,unknown})=>({total,correct,uncertainCorrect,confidentWrong,unknown})));assert.deepEqual(actual,expected);await page.screenshot({path:'/tmp/challenge-results.png',fullPage:true});
 await page.locator('#completionReview').click();assert.equal(await page.locator('.review-option.correct').count(),100);await page.locator('#toggleMissed').click();assert.equal(await page.locator('.review-option.correct').count(),15);await page.locator('#closeModal').click();
 // Every authored key grades correctly in the second form through the same engine.
 await page.evaluate(()=>{SECPLUS_TEST.challenge.start('challenge-2',100);const a=SECPLUS_TEST.state().active;for(const q of a.items)a.answers[q.id]=q.correct;SECPLUS_TEST.finishQuiz()});assert.equal(await page.evaluate(()=>SECPLUS_TEST.state().history[0].percent),100);
 // Export includes full questions and notes; merge keeps both attempts exactly once.
 await page.evaluate(()=>SECPLUS_TEST.go('backup'));const dp=page.waitForEvent('download');await page.locator('[data-action="export"]').click();const dl=await dp;const exported=JSON.parse(fs.readFileSync(await dl.path(),'utf8'));assert.equal(exported.state.history.length,2);assert(exported.state.history[1].results.every(r=>r.question.prompt));assert.equal(exported.messerExams.marker,'untouched');
 const roundtrip=await page.evaluate(()=>{const s=SECPLUS_TEST.state(),restored=SCHOOL.migrate(JSON.parse(SCHOOL.serialize(s)),MESSER_VIDEOS),merged=SCHOOL.merge(s,restored,MESSER_VIDEOS);return {count:merged.history.length,notes:merged.history[1].reflections,old:merged.objectives['1.1'].notes}});assert.equal(roundtrip.count,2);assert.equal(roundtrip.old,'Keep original progress');assert.equal(Object.values(roundtrip.notes).filter(r=>r.note==='Review this distinction').length,5);
 // Full form remains fixed, seen count is honest, and an expired saved attempt submits automatically.
 await page.evaluate(()=>SECPLUS_TEST.challenge.start('challenge-1',90));assert.equal(await page.evaluate(()=>SECPLUS_TEST.state().active.previouslySeen),100);
 await page.evaluate(()=>{const s=SECPLUS_TEST.state();s.active.deadline=Date.now()-1;localStorage.setItem('security-plus-school-v4',SCHOOL.serialize(s))});await page.reload();await page.waitForFunction(()=>window.SECPLUS_TEST&&!SECPLUS_TEST.state().active);assert.equal(await page.evaluate(()=>SECPLUS_TEST.state().history[0].percent),0);
 // Untimed resumes, layout, and offline data all work without changing stored course/Messer results.
 await page.evaluate(()=>SECPLUS_TEST.challenge.start('challenge-2',0));assert.equal(await page.evaluate(()=>SECPLUS_TEST.state().active.deadline),null);
 for(const width of [390,768,1024]){await page.setViewportSize({width,height:900});for(const route of ['challenge','quiz']){await page.evaluate(r=>SECPLUS_TEST.go(r),route);assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)),route+' overflow '+width)}}
 await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(async()=>{const cache=await caches.open('security-plus-school-v13');return !!(await cache.match('js/challenge-data.js'))});await context.setOffline(true);await page.reload();await page.waitForFunction(()=>window.SECPLUS_TEST);assert.equal(await page.locator('[data-challenge-start]').count(),2);await page.locator('#challengeResume').click();assert.equal(await page.locator('[data-answer]').count(),4);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('security-plus-messer-v1')).marker),'untouched');assert.deepEqual(errors,[]);
 console.log(JSON.stringify({passed:true,questions:200,weights:[12,22,18,28,20],objectivesPerForm:28,duplicateStems:0,existingUniqueStemsCompared:existing.size,grading:true,domainConfidence:true,notesExportMerge:true,skipAndReplaceGuards:true,timerExpiry:true,offline:true,viewports:[390,768,1024],errors}));
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r))}
})().catch(e=>{console.error(e);process.exitCode=1});
