const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const {chromium}=require('playwright');const root=path.resolve(__dirname,'..');
const c={window:{}};vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(root,'js/morning-data.js'),'utf8'),c);
const lessons=c.window.MORNING_LESSONS,qs=lessons.flatMap(l=>l.questions);assert.equal(lessons.length,6);assert.equal(qs.length,24);assert.equal(new Set(qs.map(q=>q.id)).size,24);for(const q of qs){assert.equal(q.options.length,4);assert.equal(new Set(q.options).size,4);assert.equal(q.explanations.length,4);assert(q.correct>=0&&q.correct<4)}
(async()=>{const server=require('http').createServer((req,res)=>{try{const u=new URL(req.url,'http://localhost');const f=path.join(root,u.pathname==='/'?'index.html':u.pathname);res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.pdf':'application/pdf'})[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f))}catch{res.statusCode=404;res.end()}});await new Promise(r=>server.listen(8882,'127.0.0.1',r));let browser;
try{browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote']});const context=await browser.newContext({viewport:{width:1024,height:768}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto('http://127.0.0.1:8882/#morning');await page.waitForFunction(()=>window.SECPLUS_TEST);assert.equal(await page.locator('[data-check]').count(),7);await page.screenshot({path:'/tmp/morning-home.png',fullPage:true});
await page.locator('[data-lesson="evidence"]').first().click();assert.equal(await page.locator('.morning-example article').count(),4);await page.screenshot({path:'/tmp/morning-lesson.png',fullPage:true});await page.locator('[data-check="evidence"]').click();let a=await page.evaluate(()=>SECPLUS_TEST.state().active);assert.equal(a.items.length,4);assert.equal(a.minutes,0);assert(!(await page.locator('#content').innerText()).includes(a.items[0].explanations[a.items[0].correct]));await page.locator('[data-reason-note]').fill('Both choices overlap <script>bad()</script>');await page.locator('[data-reason="wording"]').check();await page.locator('[data-confidence]').selectOption('Unsure');await page.locator('[data-action="next"]').click();assert(await page.locator('dialog.skip-dialog').isVisible());await page.locator('[data-return]').click();await page.reload();await page.waitForFunction(()=>window.SECPLUS_TEST);await page.locator('#morningResume').click();assert.equal(await page.locator('[data-reason-note]').inputValue(),'Both choices overlap <script>bad()</script>');assert(await page.locator('[data-reason="wording"]').isChecked());
await page.evaluate(()=>{const a=SECPLUS_TEST.state().active;for(const q of a.items)a.answers[q.id]=q.correct;SECPLUS_TEST.finishQuiz()});assert.equal(await page.evaluate(()=>SECPLUS_TEST.state().history[0].percent),100);const snapshot=await page.evaluate(()=>{const s=SECPLUS_TEST.state(),m=SCHOOL.migrate(JSON.parse(SCHOOL.serialize(s)),MESSER_VIDEOS);return m.history[0]});assert(Object.values(snapshot.reflections).some(r=>r.reasons.includes('wording')&&r.note.includes('<script>')));
for(const l of lessons){await page.evaluate(id=>SECPLUS_TEST.morning.open(id),l.id);assert.equal(await page.locator('.table tbody tr').count(),l.rows.length);for(const width of [390,768,1024]){await page.setViewportSize({width,height:900});assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),'overflow '+l.id+width)}}
await page.evaluate(()=>{SECPLUS_TEST.morning.start('all');const a=SECPLUS_TEST.state().active;for(const q of a.items)a.answers[q.id]=q.correct;SECPLUS_TEST.finishQuiz()});assert.equal(await page.evaluate(()=>SECPLUS_TEST.state().history[0].percent),100);assert.equal(await page.evaluate(()=>SECPLUS_TEST.state().history[0].results.length),24);
await page.evaluate(()=>SECPLUS_TEST.go('dashboard'));await page.locator('#morningButton').click();assert.equal(await page.locator('[data-review="all"]').count(),1);await page.locator('[data-review="all"]').click();assert.equal(await page.locator('.review-option.correct').count(),24);await page.locator('#closeModal').click();await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(async()=>{const c=await caches.open('security-plus-school-v14');return !!await c.match('js/morning-data.js')});await context.setOffline(true);await page.reload();await page.waitForFunction(()=>window.SECPLUS_TEST);assert.equal(await page.locator('[data-check]').count(),7);assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,lessons:6,questions:24,notesAndWordingSaved:true,skipGuard:true,allKeysGrade:true,backup:true,offline:true,responsive:true,errors}));
}finally{await browser?.close();await new Promise(r=>server.close(r))}})().catch(e=>{console.error(e);process.exitCode=1});
