// Run with Playwright available; CHROMIUM_EXECUTABLE optionally selects an installed browser.
// Optional first argument is a private Security+ export; it is never written into the repository.
const fs=require('fs'),path=require('path'),assert=require('assert'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..');
(async()=>{
 const server=require('http').createServer((req,res)=>{try{const url=new URL(req.url,'http://localhost'),file=path.join(root,url.pathname==='/'?'index.html':url.pathname);res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.pdf':'application/pdf','.json':'application/json'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end()}});
 await new Promise(r=>server.listen(8879,'127.0.0.1',r));let browser;
 try{
 browser=await chromium.launch({...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{}),headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote']});
 const context=await browser.newContext({viewport:{width:1024,height:768},hasTouch:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.goto('http://127.0.0.1:8879/');await page.waitForFunction(()=>window.SECPLUS_TEST);
 const before=await page.evaluate(()=>JSON.stringify(SECPLUS_TEST.state().history));
 await page.getByRole('button',{name:'Targeted visual lessons',exact:true}).click();assert((await page.locator('#content').innerText()).includes('No completed Exam B'));
 if(process.argv[2]){await page.locator('.target-import summary').click();await page.locator('#targetImport').setInputFiles(process.argv[2]);await page.waitForFunction(()=>!!SECPLUS_TEST.targeted.source());assert.equal(await page.evaluate(()=>JSON.stringify(SECPLUS_TEST.state().history)),before);const e=await page.evaluate(()=>({score:SECPLUS_TEST.targeted.source().score,map:TARGETED_TRACKS.map(t=>({id:t.id,ev:SECPLUS_TEST.targeted.evidence(t)}))}));const imported=JSON.parse(fs.readFileSync(process.argv[2],'utf8')).messerExams.history.filter(h=>h.exam==='B').sort((a,b)=>b.finished-a.finished)[0];assert.equal(e.score,imported.score);const expected=imported.results.filter(r=>r.credit<1||imported.flags?.[r.id]).map(r=>r.id);assert.deepEqual([...new Set(e.map.flatMap(t=>t.ev.map(e=>e.id)))].sort(),expected.sort());}
 const content=await page.evaluate(()=>({tracks:TARGETED_TRACKS.length,questions:TARGETED_TRACKS.flatMap(t=>t.questions),source:SECPLUS_TEST.targeted.source()?.exam}));assert.equal(content.tracks,8);assert.equal(content.questions.length,80);assert.equal(new Set(content.questions.map(q=>q.prompt)).size,80);assert(content.questions.every(q=>q.options.length===4&&q.explanations.length===4));
 await page.screenshot({path:'/tmp/targeted-home.png',fullPage:true});
 for(const id of ['pki','access','data','email','response','governance','assets','decisions']){
  await page.evaluate(id=>SECPLUS_TEST.targeted.open(id),id);assert(await page.locator('.target-diagram').isVisible());
  if(id==='email'){await page.selectOption('#emailSPF','other');await page.selectOption('#emailDKIM','fail');assert((await page.locator('#emailVerdict').innerText()).includes('FAIL'));await page.selectOption('#emailDKIM','aligned');assert((await page.locator('#emailVerdict').innerText()).includes('PASS'));}
  else {const count=await page.locator('[data-mode]').count();for(let i=0;i<count;i++)await page.locator(`[data-mode="${i}"]`).click();}
  if(id==='response'){await page.locator('[data-log="1"]').click();assert((await page.locator('#logExplain').innerText()).includes('enumeration'));await page.screenshot({path:'/tmp/targeted-visual.png',fullPage:true});}
  for(const st of ['worked','compare','practice']){await page.locator(`[data-stage="${st}"]`).first().click();assert((await page.locator('#content').innerText()).length>300)}
 }
 await page.evaluate(()=>SECPLUS_TEST.targeted.open('pki'));await page.locator('[data-stage="practice"]').first().click();await page.locator('[data-start]').click();
 const clue=await page.evaluate(()=>{const a=SECPLUS_TEST.state().targeted.active;return a.items[a.index].clue});assert(!(await page.locator('#content').innerText()).includes(clue));
 await page.locator('[data-option="1"]').click();await page.locator('[data-cross="1"]').click();assert.equal(await page.evaluate(()=>Object.keys(SECPLUS_TEST.state().targeted.active.answers).length),0);await page.locator('[data-check]').click();assert(await page.locator('dialog').isVisible());await page.locator('[data-return]').click();
 await page.locator('[data-option="1"]').click();await page.locator('[data-check]').click();assert((await page.locator('#targetQuestionStatus').innerText()).includes('confidence'));
 await page.locator('.target-reflection summary').click();await page.locator('#targetQuestionNote').fill('Testing <script>window.bad=true</script> & saved notes');await page.locator('[data-target-reason="two"]').check();await page.locator('[value="Confident"]').check();await page.screenshot({path:'/tmp/targeted-quiz.png',fullPage:true});
 await page.reload();await page.waitForFunction(()=>window.SECPLUS_TEST);await page.evaluate(()=>SECPLUS_TEST.go('targeted'));await page.locator('[data-resume]').click();assert((await page.locator('#targetQuestionNote').inputValue()).includes('<script>'));assert.equal(await page.evaluate(()=>window.bad),undefined);await page.locator('[data-check]').click();assert(await page.locator('.target-feedback').isVisible());await page.locator('[data-next]').click();
 await page.locator('[data-skip]').click();await page.locator('[data-skip]').last().click();assert((await page.locator('.target-feedback').innerText()).includes('Skipped intentionally'));await page.locator('[data-next]').click();
 for(let n=2;n<10;n++){if(n===7){assert(await page.locator('[data-transfer]').isVisible());await page.locator('[data-transfer]').click()}await page.locator('[data-option="0"]').click();await page.locator(`[value="${n===2?'Guessing':'Confident'}"]`).check();await page.locator('[data-check]').click();await page.locator('[data-next]').click();}
 const result=await page.evaluate(()=>{const s=SECPLUS_TEST.state(),a=s.targeted.attempts[0];const restored=SCHOOL.migrate(JSON.parse(SCHOOL.serialize(s)),MESSER_VIDEOS),merged=SCHOOL.merge(restored,restored,MESSER_VIDEOS);return {score:a.results.filter(r=>r.credit===1).length,pending:SECPLUS_TEST.targeted.pending(a).length,core:a.results.filter(r=>r.scope==='core').length,transfer:a.results.filter(r=>r.scope==='transfer').length,notes:Object.values(merged.targeted.attempts[0].reflections).some(r=>r.note.includes('<script>')),attempts:merged.targeted.attempts.length,active:s.targeted.active}});assert.deepEqual(result,{score:8,pending:3,core:7,transfer:3,notes:true,attempts:1,active:null});
 for(const width of [390,768,1024]){await page.setViewportSize({width,height:900});await page.evaluate(()=>SECPLUS_TEST.targeted.open('pki'));const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert(!overflow,`overflow at ${width}`)}
 await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(async()=>await caches.has('security-plus-school-v15'));await context.setOffline(true);await page.reload();await page.waitForFunction(()=>window.SECPLUS_TEST);await page.evaluate(()=>SECPLUS_TEST.go('targeted'));assert(await page.locator('[data-track="pki"]').isVisible());assert.deepEqual(errors,[]);
 console.log(JSON.stringify({passed:true,tracks:8,questions:80,privateImportPreservesCourse:true,allVisuals:true,noEarlyAnswerReveal:true,skipGuard:true,confidenceGate:true,noteRoundTrip:true,separateScores:true,uncertainQueue:true,backupMerge:true,offline:true,viewports:3,errors}));
 }finally{await browser?.close();server.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
