import json
from pathlib import Path
tracks=[]
def track(id,title,refs,objectives,hook,why,steps,compare,worked,transfer,sources):
 t=dict(id=id,title=title,refs=refs,objectives=objectives,hook=hook,why=why,steps=steps,compare=compare,worked=worked,transfer=transfer,sources=sources,questions=[]);tracks.append(t);return t
def q(t,skill,prompt,opts,clue,scope='core'):
 # Options are authored as [answer, explanation]; the UI shuffles their display.
 t['questions'].append(dict(id=t['id']+'-'+str(len(t['questions'])+1),skill=skill,prompt=prompt,options=[o[0] for o in opts],explanations=[o[1] for o in opts],correct=0,clue=clue,scope=scope))
T=track('pki','Certificates & hardware keys',{'B1':[0,1,2,3],'B40':None,'B55':None,'B81':None},['1.4','3.2'],
 'Request → issue → check status. A hardware key protector has a different job.',
 'Separate the certificate lifecycle from the device that protects a private key. Knowing that all of these involve cryptography is not enough to choose between them.',
 [['Device','Creates a key pair. The private key stays protected.'],['CSR → CA','A Certificate Signing Request carries the public key and identifying information to a Certificate Authority.'],['Certificate','The CA signs the binding between an identity and its public key. Clients validate trust, name and dates.'],['Status check','A Certificate Revocation List lists revoked certificates. Online Certificate Status Protocol asks about one certificate.']],
 [['CSR — Certificate Signing Request','Ask for a certificate','A public key is being submitted for signing.','Not a revocation check; never send the private key.'],['CA — Certificate Authority','Issue and sign certificates','An organization must establish certificate trust.','Not the client’s request or the list of revoked certificates.'],['CRL — Certificate Revocation List','Publish revoked serial numbers','A client downloads a signed revocation list.','A list can be cached and become stale.'],['OCSP — Online Certificate Status Protocol','Return status for a certificate','A client asks a responder about revocation.','Stapling changes who fetches the signed response.'],['TPM — Trusted Platform Module','Protect device-bound keys','Disk key protection and resistance to repeated authorization guesses.','It does not maintain a CRL or replace bulk disk encryption.'],['HSM — Hardware Security Module','Protect cryptographic keys and operations','A service needs controlled key use, often centrally.','Hardware key protection is distinct from certificate revocation.']],
 {'scenario':'A camera-management console trusts the server’s certificate issuer. Its client cannot reach the revocation responder, but can reach the server. The server supplies a recent, signed status response with the TLS handshake.', 'clues':['Trust in the issuer already exists.','The client must avoid a separate responder connection.','The status response is signed by an authorized responder.'], 'answer':'OCSP stapling','because':'The server retrieves and attaches the signed status response. The client verifies it; the server is not inventing its own trust decision.','trap':'A CSR starts issuance. It cannot prove that an already-issued certificate is still valid.'},
 'Transfer: distinguish a trust-chain failure from a revocation or expiry failure. A valid stapled response does not make an untrusted issuer trusted. A TPM can bind key use to boot measurements and throttle authorization guesses; it is not a guarantee against every physical attack.',
 [['Microsoft: TPM overview','https://learn.microsoft.com/en-us/windows/security/hardware-security/tpm/trusted-platform-module-overview'],['IETF: TLS certificate status extension','https://www.rfc-editor.org/rfc/rfc6066#section-8']])
q(T,'issuance','An administrator has generated a key pair for a new management server. What should be submitted to obtain a signed certificate?', [('A certificate signing request','Carries the public key and identifying details to the issuer.'),('The server’s private key','Must stay protected; possession would allow impersonation.'),('A certificate revocation list','Distributes revocation information after certificates exist.'),('A stapled status response','Reports status of an existing certificate, not a request for a new one.')], 'The certificate has not been issued yet.')
q(T,'revocation','A disconnected client periodically downloads a signed file containing serial numbers of invalidated certificates. What is it using?', [('A certificate revocation list','CRL is a published list of revoked certificates.'),('A certificate signing request','CSR requests issuance, not invalidation status.'),('A root certificate','Establishes a trust anchor; does not list revoked serial numbers.'),('Key escrow','Stores recoverable keys with a designated party.')], 'A downloaded list of revoked serial numbers.')
q(T,'stapling','A client can reach a web service but cannot contact the CA’s status responder. Which server feature can supply a signed revocation-status response during connection setup?', [('OCSP stapling','The server obtains and attaches the responder’s signed response.'),('Wildcard certification','Covers permitted names; does not deliver revocation status.'),('CSR generation','Requests a certificate; does not report its current status.'),('Private-key escrow','Supports recovery, not client revocation checks.')], 'The server supplies status so the client need not query separately.')
q(T,'trust','An enterprise Wi-Fi client reports “issuer not trusted” for the authentication server. The server name and certificate dates are correct. What should be checked first?', [('The client’s trusted CA configuration','A missing or incorrect trust anchor explains an untrusted issuer.'),('The account’s password-expiration date','A password problem does not establish certificate trust.'),('The switch’s port speed','Connectivity exists far enough to receive the certificate.'),('The client’s cached revocation list','Revocation status is separate from trusting the issuer named in this error.')], 'Issuer trust failed; the prompt rules out name and date errors.')
q(T,'key-protection','A laptop should release a protected disk-unlock key only under approved startup conditions. Which component best supports this requirement?', [('TPM','Trusted Platform Module can protect keys and tie their use to platform measurements.'),('CRL distribution point','Publishes revocation lists; does not protect a disk key.'),('Certificate signing request','An issuance message, not protected key storage.'),('OCSP responder','Provides certificate status, not measured-boot key release.')], 'Device-bound key release, not certificate lifecycle.')
q(T,'anti-hammering','Repeated incorrect PIN attempts cause a laptop’s TPM authorization path to delay further guesses. What purpose does this serve?', [('Resistance to brute-force guessing','Dictionary-attack logic limits repeated authorization attempts.'),('Automatic certificate renewal','Renewal is a certificate lifecycle operation.'),('Encryption of every packet','A TPM is not the network’s bulk encryption engine.'),('Publication of revoked keys','Revocation distribution is a different service.')], 'The control slows repeated authorization guesses.')
q(T,'ca','A company needs a trusted service to sign employee public-key certificates. Which role is needed?', [('Certificate Authority','The CA issues and signs certificates.'),('Certificate Revocation List','A CRL is a list, not an issuer.'),('Online Certificate Status Protocol client','A client asks for status, rather than issuing certificates.'),('Key escrow agent','Holds recovery material; that does not make it the certificate issuer.')], 'Sign identity-to-public-key bindings.')
q(T,'trust-transfer','A certificate has a valid stapled “good” status, but its issuer is absent from the client’s trust store. What follows?', [('The status response alone does not establish issuer trust','Revocation and trust-chain validation are separate checks.'),('The good status makes all issuers trusted','Would defeat trust-anchor validation.'),('The private key must be downloaded to the client','Clients verify with public information, not the server’s private key.'),('A new CRL automatically fixes the trust chain','A revocation list does not install trust anchors.')], 'Good revocation status is only one validation result.','transfer')
q(T,'key-protection-transfer','A signing service must perform cryptographic operations without exposing its private key to application processes. Which design best fits?', [('An HSM-backed signing service','An HSM protects keys while providing authorized cryptographic operations.'),('A public CRL mirror','Distributes revocation information, not protected signing.'),('An OCSP cache on every client','Caches status but does not protect the signing service’s private key.'),('A wildcard name in the certificate','Changes name coverage, not private-key exposure.')], 'Protect key use by a service.','transfer')
q(T,'validation-transfer','A browser reports a hostname mismatch. The issuer is trusted and the certificate is not expired. What is the most direct fix?', [('Deploy a certificate covering the requested server name','Name validation must match the intended endpoint.'),('Disable certificate validation','Hides the warning by removing authentication assurance.'),('Reset the user’s password','Does not change certificate name coverage.'),('Publish a longer CRL','Revocation-list length does not fix the name mismatch.')], 'Match the stated failure, not just any PKI operation.','transfer')

T=track('access','Who grants access—and where?',{'B2':[0,1],'B21':None,'B25':None,'B63':None,'B69':None},['3.2','4.1','4.6'],
 'Identify the job: entry decision, admin path, device policy, or application inspection.',
 'Acronyms become useful when each one has a location and a job. A log collector does not grant access, and an access-policy engine does not provide an administrator’s command-line session.',
 [['Laptop / supplicant','Requests entry using 802.1X.'],['Switch / authenticator','Controls the port and forwards the authentication exchange.'],['RADIUS service','Remote Authentication Dial-In User Service carries AAA decisions.'],['Directory','LDAP — Lightweight Directory Access Protocol — can provide directory lookups behind the service.']],
 [['AAA — Authentication, Authorization, Accounting','Identity, permission, activity','Centralize who signs in and what they may do.','Not the same as collecting security alerts.'],['NAC — Network Access Control','Decide network admission','Quarantine a device that fails posture checks.','Does not itself provide an admin shell to internal routers.'],['Jump server','Controlled administration path','A hardened intermediate host reaches management interfaces.','Does not replace identity verification.'],['WAF — Web Application Firewall','Inspect web requests','Filter malicious HTTP input before the application.','Not a general remote-access tunnel.'],['UTM — Unified Threat Management','Bundle security services','Combine firewall and other inspection features.','Broader package; a WAF is the more specific web-input control.'],['MDM — Mobile Device Management','Manage mobile settings','Enforce mobile-device policy and remote management.','Not reconnaissance or a room-motion detector.'],['SIEM — Security Information and Event Management','Correlate security events','Investigate logs across systems.','Logging a login is not performing AAA.'],['SASE — Secure Access Service Edge','Cloud-delivered networking and security','Apply distributed access/security policy near users.','An architectural approach, not a synonym for a WAF.']],
 {'scenario':'An integrator must administer internal access-control servers from a remote support network. Only one hardened host may reach their management interfaces.', 'clues':['The task is an administration path.','The destination systems are inside a private network.','One approved intermediate host has reachability.'],'answer':'Jump server','because':'The administrator authenticates to the intermediate host, then uses its restricted management path.','trap':'NAC can decide whether a laptop may join a network. That does not create the required remote shell path.'},
 'Transfer: keep control purpose separate from deployment. EDR (Endpoint Detection and Response) records and investigates endpoint behavior; XDR (Extended Detection and Response) correlates across multiple security sources. A VPN concentrator terminates VPN tunnels. LDAP can be an identity source behind 802.1X/RADIUS; it is not the access point’s 802.1X exchange protocol.',
 [['Cisco Duo: 802.1X roles','https://duo.com/learn/what-is-8021x-authentication'],['IEEE: port-based access control','https://1.ieee802.org/security/802-1x/']])
q(T,'jump-server','A vendor needs SSH access to internal switches. Policy requires all management sessions to pass through one hardened intermediary. What fits?', [('Jump server','Provides the restricted intermediate administration path.'),('NAC','Controls admission/posture; does not supply the management shell path.'),('SIEM','Collects and correlates events; does not relay the required admin session.'),('WAF','Inspects web requests, not SSH administration.')], 'One intermediate host for management sessions.')
q(T,'aaa','Switch administrators must authenticate centrally, receive role-specific permissions, and have command activity recorded. What model covers all three?', [('AAA','Authentication, Authorization, Accounting cover those three functions.'),('SIEM','Can analyze records but is not the three-part access model.'),('MDM','Manages mobile devices rather than defining this login model.'),('IPsec','Protects IP communications; does not by itself implement the three functions.')], 'Identity + permissions + activity records.')
q(T,'nac','A laptop with an expired endpoint agent should receive only remediation-network access when it connects. Which control best fits?', [('NAC','Uses posture/admission policy to restrict network access.'),('Jump server','Provides an administration path rather than general device admission.'),('WAF','Examines web application requests.'),('HSM','Protects cryptographic keys and operations.')], 'Network admission depends on device health.')
q(T,'waf','A public portal needs requests containing SQL injection patterns inspected before they reach its application. Which control is most specific?', [('WAF','Web Application Firewall inspects application-layer web input.'),('VPN concentrator','Terminates protected tunnels; does not specifically filter SQL input.'),('NAC','Controls network admission rather than web request content.'),('MDM','Manages mobile endpoint configuration.')], 'Public web input is the inspection target.')
q(T,'mdm','Lost field tablets must support remote policy enforcement and managed wipe. Which capability best fits?', [('MDM','Mobile Device Management provides device policy and management actions.'),('OSINT','Open-Source Intelligence gathers publicly available information.'),('Infrared motion detection','Detects physical movement, not tablet policy compliance.'),('SIEM correlation','Correlates events; management commands need another control.')], 'Manage the mobile device itself.')
q(T,'8021x','In a typical enterprise 802.1X deployment, which component controls whether the access port opens after receiving the authentication result?', [('The switch or access point acting as authenticator','It enforces the controlled-port decision.'),('The supplicant laptop alone','It requests access but cannot grant itself entry.'),('The LDAP schema','A schema defines directory structure, not port state.'),('The SIEM dashboard','It can observe events but does not serve as the port authenticator.')], 'Enforcing the port decision is the authenticator’s role.')
q(T,'directory','An 802.1X authentication service needs to look up users and groups in an enterprise directory. Which protocol can support that lookup?', [('LDAP','Lightweight Directory Access Protocol accesses directory information.'),('SPF','Sender Policy Framework authorizes email sending hosts.'),('SNMP traps','Carry management notifications, not directory lookups.'),('OCSP','Checks certificate revocation status.')], 'Directory lookup behind the authentication service.')
q(T,'edr-transfer','Analysts need endpoint process trees and the ability to isolate an affected laptop. What capability fits best?', [('EDR','Endpoint Detection and Response supports endpoint investigation and response.'),('WAF','Sees web requests at the protected application, not every laptop process.'),('VPN concentrator','Terminates tunnels, not endpoint process investigation.'),('HSM','Protects keys rather than recording process trees.')], 'Processes and response on the endpoint.','transfer')
q(T,'xdr-transfer','A platform joins endpoint detections, email events, and cloud identity activity into one investigation. Which term is most specific?', [('XDR','Extended Detection and Response correlates detections across sources.'),('MDM','Device management is not cross-source detection and response.'),('Standalone host firewall','Filters host traffic but does not by itself correlate all these sources.'),('NAC','Primarily controls network access and posture.')], 'Detection and response across multiple security domains.','transfer')
q(T,'control-location-transfer','Remote users need encrypted tunnels terminated at a central gateway. Which appliance role is the direct match?', [('VPN concentrator','Terminates and manages many VPN connections.'),('WAF','Inspects application requests; it is not the tunnel-termination role.'),('Jump server','Provides a management hop, not general VPN termination.'),('LDAP directory','Stores identity information, not tunnel termination.')], 'Follow the traffic path and name the gateway’s job.','transfer')

T=track('data','Data states & protection choices',{'B4':[0,1,3,4,5],'B5':list(range(10)),'B27':None,'B43':None},['1.4','3.3','4.5'],
 'Stored, traveling electronically, or being processed? Then ask what must be protected.',
 'Tokenization, masking, encryption and hashing solve different problems. Identify whether you must recover the original, replace it in a workflow, hide its display, or verify a match.',
 [['At rest','Stored database, disk, backup tape—even a tape in a courier van.'],['In transit','Data moving electronically across a link or network.'],['In use','A processor works on values in memory, such as calculation or validation.']],
 [['Tokenization','Replace a sensitive value','A payment reference can be used without sending the card number.','Not merely hiding a few display digits.'],['Masking','Hide part of a display','A receipt shows only the last four digits.','The displayed placeholder need not be a usable transaction token.'],['Encryption','Recover using a key','An authorized reader must recover protected data.','Requires key management; not a one-way password verifier.'],['Hashing','Produce a one-way digest','Check integrity or support a salted password-verification scheme.','Cannot decrypt a hash to obtain the original.'],['Digital signature','Verify origin and integrity','Verify a signed release using the signer’s public key.','Does not inherently hide the content.'],['Obfuscation','Make interpretation harder','Transform code into a harder-to-read form.','Not equivalent to strong confidentiality.'],['Key escrow','Arrange controlled recovery','A designated party stores recovery key material.','Does not issue certificates or verify email senders.'],['Journaling','Record updates for recovery','Replay or roll back filesystem changes after interruption.','Not a way to store a password verifier.']],
 {'scenario':'A payment service returns reference tok_84 to a merchant. Later charges use that reference. A separate receipt shows **** 4821.', 'clues':['tok_84 is a substitute used in the transaction workflow.','The receipt only hides digits from view.'],'answer':'Tokenization for the transaction; masking for the receipt','because':'The replacement value can stand in for the sensitive account number. Display hiding has a different purpose.','trap':'Both make the original number less visible, but only the first supplies a substitute for later operations.'},
 'Transfer: a locked, powered-off disk is different from an unlocked application displaying decrypted records. Full disk encryption protects stored data; it does not prevent an authorized running process from reading it. For passwords, use a salted, deliberately expensive password-hashing scheme rather than a fast unsalted general-purpose hash.',
 [['OWASP: password storage','https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html'],['NIST: data at rest','https://csrc.nist.gov/glossary/term/data_at_rest']])
q(T,'tokenization','A merchant stores a replacement payment reference that can be submitted for later charges without retaining the card number. What is this?', [('Tokenization','A usable surrogate replaces the sensitive value in the workflow.'),('Masking','Hides display characters but does not necessarily create a transaction surrogate.'),('Hashing','Creates a digest; is not inherently a usable payment reference.'),('Steganography','Hides the existence of information inside other content.')], 'The replacement is used to perform later transactions.')
q(T,'masking','A help-desk screen shows only the final four digits of an account number. What technique is directly shown?', [('Masking','The display conceals part of the sensitive value.'),('Key escrow','Concerns recovery key custody.'),('Tokenization','Would replace the value with a surrogate; that is not established here.'),('Digital signing','Verifies origin and integrity, not display hiding.')], 'Partial display hiding, with no claimed transaction substitute.')
q(T,'rest','Encrypted backup drives are being driven to a storage facility. What state describes the records stored on those drives?', [('At rest','The bits remain stored on media; moving the vehicle does not make a network transmission.'),('In transit','Applies to electronic transfer, not physical movement of stored media.'),('In use','Would describe processing the data.'),('In a cryptographic session','Encryption of stored media does not imply an active session.')], 'Follow the data operation, not the vehicle.')
q(T,'use','A payroll application decrypts salary values in memory and calculates tax. What state describes the values being calculated?', [('In use','The application is actively processing values.'),('At rest','Describes stored values outside the processing operation.'),('In transit','No electronic transfer is the operation being asked about.'),('Archived','Archival storage is not active calculation.')], 'The requested operation is calculation in memory.')
q(T,'cleartext','A packet capture directly displays a login password as readable text. Which finding is best supported?', [('Credentials crossed the link without effective transport confidentiality','The observation supports cleartext exposure on that captured path.'),('The password hash has been cracked','No hash-cracking step is described.'),('The user used an expired certificate','Certificate expiry is not shown by readable credentials.'),('The server’s disk encryption failed','A network capture does not establish a disk-encryption failure.')], 'State what the capture demonstrates, not an unseen cause.')
q(T,'journaling','After sudden power loss, a filesystem consults its recorded pending updates to restore a consistent state. Which mechanism is involved?', [('Journaling','Records filesystem transactions to support crash recovery.'),('Obfuscation','Makes information harder to interpret.'),('Key escrow','Supports controlled key recovery.'),('Digital signing','Supports authenticity and integrity verification, not transaction replay.')], 'Recorded updates support filesystem consistency after interruption.')
q(T,'signature','A software release remains publicly readable, but customers must verify it came from the publisher and was not modified. What is most appropriate?', [('Digital signature','Supports origin and integrity checks without needing to conceal the release.'),('Masking','Hides portions of a display.'),('Symmetric encryption alone','Protects confidentiality but does not provide a publisher-verifiable signature.'),('Obfuscation','Makes analysis harder without proving publisher authenticity.')], 'Public readability plus verifiable publisher origin.')
q(T,'password-transfer','A stolen password database should resist precomputed lookup tables and make each guess expensive. Which design fits?', [('Unique salts with a suitable password-hashing scheme','Salts disrupt shared precomputation; costly hashing slows guesses.'),('One fast unsalted hash for every password','Enables efficient guessing and precomputed comparisons.'),('Reversible encoding such as Base64','Encoding is readily reversed and offers no password protection.'),('Password masking in the login form only','Protects screen display, not the stored verifier.')], 'Both unique salts and expensive verification matter.','transfer')
q(T,'fde-transfer','An authorized process on an unlocked laptop can read a sensitive file although full disk encryption is enabled. What explains this?', [('Disk encryption does not replace access controls on running processes','The system can decrypt data for authorized use after unlocking.'),('All disk encryption is ineffective','It still protects stored data in relevant locked/offline scenarios.'),('The file must have been tokenized','A running process reading data does not establish tokenization.'),('A CRL was missing','Certificate revocation lists are unrelated to this observation.')], 'Distinguish stored-data protection from active access.','transfer')
q(T,'obfuscation-transfer','A script’s names and control flow are transformed to hinder inspection, but it still runs normally and can be reverse engineered. What has been applied?', [('Obfuscation','Raises interpretation effort without guaranteeing secrecy.'),('Irreversible password hashing','A hashed script would not execute as the original program.'),('Key escrow','Stores recovery material rather than transforming code.'),('Full disk encryption','Protects stored media, not this code transformation.')], 'Harder to interpret is not the same as cryptographically secret.','transfer')
T=track('email','Email authentication without acronym soup',{'B17':None,'B4':[2]},['4.5'],
 'SPF checks the sending host. DKIM checks a signature. DMARC ties a passing identity to the visible From domain.',
 'This is reinforcement, not an assumption that every email concept is weak. The flagged DKIM answer and earlier chat justify a compact distinction lesson.',
 [['Sending host','SPF — Sender Policy Framework — checks whether the sending IP is authorized for the envelope-sender domain.'],['Signed message','DKIM — DomainKeys Identified Mail — checks a message signature against a public key published in DNS.'],['Visible From','DMARC — Domain-based Message Authentication, Reporting and Conformance — requires an aligned SPF or DKIM pass.'],['Receiver policy','DMARC publishes none, quarantine or reject plus reporting instructions; receivers apply their policies.']],
 [['SPF','Authorize a sending host','Check sending IP against envelope-domain policy.','Does not sign the message or automatically authenticate the visible From.'],['DKIM','Verify signed message content','Find the signature’s selector/domain key in DNS.','Does not encrypt mail. A valid signature can belong to a different domain.'],['DMARC','Check alignment and policy','At least one passing SPF/DKIM identity aligns with visible From.','Both SPF and DKIM need not pass; an unaligned pass is insufficient.'],['TLS — Transport Layer Security','Protect a transport connection','Encrypt the link between communicating peers.','Does not substitute for domain-level email authentication.']],
 {'scenario':'Visible From: billing@plant.example. SPF passes for mail.vendor.example. DKIM passes with d=plant.example.', 'clues':['SPF’s passing domain does not align with plant.example.','DKIM’s passing domain matches the visible From domain.'],'answer':'DMARC can pass through aligned DKIM','because':'One aligned authentication path is enough. The unaligned SPF pass is not the reason.','trap':'Counting the word “pass” without checking which domain passed loses the alignment requirement.'},
 'Transfer: forwarding can break SPF when the forwarding IP is not authorized for the original envelope domain. DKIM may survive if signed content is preserved. Changing signed content can invalidate DKIM. Neither mechanism guarantees that authenticated mail is harmless.',
 [['Cloudflare: email authentication','https://developers.cloudflare.com/email-service/concepts/email-authentication/']])
q(T,'spf','A receiving mail server checks whether an IP address is authorized to send for the envelope-sender domain. Which mechanism is this?', [('SPF','Sender Policy Framework checks authorized sending hosts.'),('DKIM','Verifies a cryptographic message signature.'),('DMARC alignment alone','Uses authentication results and aligned domains; does not replace SPF’s host check.'),('TLS','Protects a connection rather than publishing authorized sender IPs.')], 'Sending IP authorized for the envelope domain.')
q(T,'dkim','An email contains a signature and a selector identifying a public key in DNS. Which mechanism verifies it?', [('DKIM','DomainKeys Identified Mail verifies the signature with that published key.'),('SPF','Checks sending IP authorization, not this message signature.'),('RADIUS','Handles access authentication rather than email signatures.'),('IPsec','Protects IP traffic and does not use this mail signature selector.')], 'A message signature plus a DNS selector.')
q(T,'dmarc','An organization publishes instructions to quarantine mail that fails aligned domain authentication. Which mechanism publishes that policy?', [('DMARC','Publishes domain authentication policy and reporting instructions.'),('SPF alone','Publishes sending-host authorization, not the full aligned From-domain policy.'),('DKIM alone','Signs messages but does not publish this handling policy.'),('S/MIME encryption','Can protect message content but is not this DNS domain policy.')], 'Handling policy tied to aligned domain authentication.')
q(T,'alignment','From is alerts@factory.example. SPF passes for unrelated.example; DKIM fails. What is the DMARC authentication result?', [('Fail: no aligned passing method','The only pass belongs to an unrelated domain.'),('Pass because SPF passed somewhere','A pass must align with the visible From domain.'),('Pass because TLS can encrypt the connection','Transport encryption is not DMARC alignment.'),('Unknown until the recipient opens the message','DMARC checks occur during mail handling, not user opening.')], 'A pass for an unrelated identity does not authenticate the visible From.')
q(T,'one-path','SPF fails, but DKIM verifies with a domain matching the visible From. What can DMARC do?', [('Pass through aligned DKIM','One aligned passing method satisfies the authentication condition.'),('Always fail because both methods must pass','DMARC does not require both.'),('Ignore DKIM and test the user’s password','User passwords are not this domain authentication decision.'),('Decrypt the message to determine its sender','DMARC is not an encryption/decryption mechanism.')], 'At least one aligned pass.')
q(T,'not-encryption','A team enables DKIM and concludes that mail content is now unreadable to intermediaries. Which correction is accurate?', [('DKIM signs; it does not encrypt content','A verifiable signature addresses integrity/origin, not secrecy.'),('DKIM encrypts using the recipient’s password','That is not how DKIM operates.'),('SPF automatically encrypts the content instead','SPF authorizes sending hosts.'),('DMARC reject policy encrypts every accepted message','Reject is a handling policy, not encryption.')], 'Signing and confidentiality are separate properties.')
q(T,'dmarc-policy','A domain wants reports about authentication failures without asking receivers to quarantine or reject solely because of its DMARC policy. Which policy fits?', [('p=none','Requests monitoring/reporting without a quarantine/reject instruction.'),('p=reject','Requests rejection, which conflicts with the stated monitoring phase.'),('p=quarantine','Requests suspicious handling, not monitoring alone.'),('Remove all authentication records','Loses the intended published authentication/reporting framework.')], 'Observe before requesting enforcement.')
q(T,'forwarding-transfer','A forwarding service preserves a message’s signed content but changes the connecting IP. Which result is plausible?', [('SPF can fail while DKIM still verifies','The forwarding IP may not be authorized; an intact signature may survive.'),('Both methods must always fail','DKIM does not depend only on the connecting IP.'),('Both methods must always pass','SPF can be affected by forwarding.'),('DMARC no longer checks any alignment','Alignment remains part of DMARC.')], 'Host authorization and content signature depend on different evidence.','transfer')
q(T,'tampering-transfer','A gateway alters a body section covered by the DKIM signature after signing. What is the direct risk?', [('DKIM verification failure','Changing signed content can invalidate the signature.'),('Automatic update of the published private key','DKIM publishes a public key, not an automatically updated private key.'),('Guaranteed SPF failure','SPF depends on sending-host authorization, not body changes.'),('Automatic encryption of the new text','Signatures do not encrypt added content.')], 'Signed content has changed.','transfer')
q(T,'limits-transfer','An attacker sends a malicious attachment from a domain they control. SPF, DKIM and DMARC all pass for that domain. What can be concluded?', [('Domain authentication does not establish that content is safe','The sender can authenticate its own malicious mail.'),('The attachment cannot contain malware','These mechanisms are not malware verdicts.'),('The recipient’s machine is already compromised','Receiving a message is not proof of execution or compromise.'),('The domain must belong to the recipient’s employer','Passing checks does not establish that business relationship.')], 'Authenticated origin is not a safety guarantee.','transfer')

T=track('response','Incident decisions, evidence & visibility',{'B31':None,'B58':None,'B72':None},['4.8','4.9','2.5'],
 'What is already established? What is the next objective? Which sensor can actually see it?',
 'A response phase, an evidence-handling procedure and a detection tool answer different questions. Locate the traffic or evidence before choosing a tool.',
 [['Validate','Determine whether the observed activity is an incident; scope it using relevant evidence.'],['Contain','Limit ongoing harm within the response plan and authority. Isolation can preserve power and evidence.'],['Eradicate / recover','Remove the cause, restore from trusted sources, validate and monitor.'],['Preserve throughout','Record evidence handling, protect originals, hash working copies, and maintain custody.']],
 [['Chain of custody','Document evidence handling','Record who obtained, transferred and stored an item and when.','A hash helps detect changes but does not identify every custodian.'],['Legal hold','Prevent destruction of relevant records','Suspend routine deletion for a preservation obligation.','Does not document each physical or digital handoff.'],['E-discovery','Find and produce electronic material','Identify, preserve, review and produce electronically stored information.','A broader process, not a substitute for custody records.'],['Non-repudiation','Support accountability for an action','A digital signature helps support attribution and integrity.','Not the record of evidence possession.'],['HIPS — Host-based Intrusion Prevention System','Observe / prevent activity on a host','Host telemetry can remain useful when traffic bypasses the company gateway.','Visibility depends on deployed sensors and enabled logging.'],['Host firewall logs','Record traffic at the endpoint','Inspect connections on a laptop using a cellular hotspot.','A gateway that never sees the path cannot supply those missing flow records.']],
 {'scenario':'A managed laptop switches from corporate Wi-Fi to a cellular hotspot. The corporate gateway reports no matching connections. The laptop still has its endpoint agent and host firewall enabled.', 'clues':['The hotspot route bypasses the corporate gateway.','The endpoint still participates in every connection.'],'answer':'Look for host-level evidence','because':'The host firewall and endpoint sensor are on the path of the activity. A central gateway cannot log flows that never traverse it.','trap':'“More powerful appliance” is irrelevant if it is in the wrong place. Absence of gateway records does not prove absence of activity.'},
 'Transfer: for web logs, repeated requests for different filenames/directories suggest enumeration; many passwords for one account suggest brute force; one password across many accounts suggests spraying. A success code proves only the reported request outcome, not automatically data theft. Secure remote logging preserves another copy, but time synchronization and access controls still matter.',
 [['CISA: chain of custody','https://www.cisa.gov/sites/default/files/2023-12/Chain%20of%20Custody_2023.8.14_508.pdf'],['CISA: ransomware response','https://www.cisa.gov/stopransomware/ransomware-guide']])
q(T,'containment','Responders have confirmed malware is actively spreading from a workstation. Their approved playbook permits network isolation. What best limits further spread while retaining volatile evidence?', [('Isolate its network connection while keeping it powered','Contains the path of spread without immediately losing memory contents.'),('Wipe the disk immediately','Destroys evidence and jumps to eradication.'),('Wait for a complete historical log review before acting','Allows the established active spread to continue.'),('Publish a final incident report','Reporting does not contain the ongoing incident.')], 'Confirmed ongoing harm; authority to isolate is already established.')
q(T,'custody','An analyst transfers a seized drive to another examiner. What record most directly supports evidence-handling accountability?', [('A signed custody record with identities, times and item details','Documents the handoff and who controlled the evidence.'),('Only the final incident summary','Does not necessarily document each transfer.'),('The drive’s purchase receipt','Shows acquisition, not investigation custody.'),('A password policy screenshot','Does not track this evidence item.')], 'Who had this item, when, and under what transfer?')
q(T,'legal-hold','A preservation notice covers a mailbox that would otherwise be deleted tonight. Which action directly addresses the notice?', [('Suspend the applicable deletion under legal hold','Preserves relevant records from routine destruction.'),('Delete it after calculating a hash','A hash does not retain the original contents.'),('Create a new user password','Does not stop scheduled record deletion.'),('Mark the network traffic as trusted','Does not preserve the mailbox.')], 'Preserve records that are about to be destroyed.')
q(T,'host-visibility','A laptop uses a cellular hotspot instead of the enterprise gateway. Which source is most likely to contain its outbound connection records?', [('Its enabled host firewall log','The endpoint sees its own connections on that path.'),('The bypassed corporate firewall alone','Cannot see flows that never traverse it.'),('The public website’s WAF for all applications','Only observes requests to the protected web service.'),('The offline backup catalog','Tracks backups rather than current network connections.')], 'Place the sensor on the actual traffic path.')
q(T,'eradication','A compromised server is already isolated and evidence has been preserved. The team removes malicious persistence and closes the exploited weakness. Which phase does this describe?', [('Eradication','Removes the cause and foothold.'),('Preparation','Occurs before response and includes plans and readiness.'),('Detection only','Identifies suspicious events rather than removing persistence.'),('Lessons learned','Reviews and improves the process after the incident.')], 'Remove the cause after containment.')
q(T,'integrity','Two forensic copies have matching cryptographic hashes to the acquired image. What does that directly support?', [('The compared contents match to the assurance provided by the hash','Hash comparison supports content integrity.'),('Every person who handled them is identified','Requires custody records.'),('The original system had no malware','Matching copies can both contain malware.'),('The initial acquisition was legally authorized','Authorization is separate from matching contents.')], 'Integrity evidence is not a complete custody or authorization record.')
q(T,'ediscovery','A team searches archived mail, filters material relevant to litigation, reviews it, and produces the requested records. Which process best fits?', [('E-discovery','Covers discovery and production of electronic information.'),('Packet filtering','Controls network traffic rather than legal record production.'),('Non-repudiation alone','Supports accountability, not this full collection/review workflow.'),('Malware eradication','Removes malicious code rather than producing records.')], 'Search, review and production of electronic records.')
q(T,'enumeration-transfer','A web log shows GET /admin 404, GET /backup.zip 404, GET /.env 403, and GET /old/ 404 from one source. What is most directly suggested?', [('Directory and file enumeration','The source is probing multiple resource names.'),('Password spraying','Would involve authentication attempts across accounts.'),('Confirmed file exfiltration','No successful file transfer is established by these lines.'),('Impossible travel','Requires geographic/time evidence for identity use.')], 'Different paths are being tried; do not invent successful theft.','transfer')
q(T,'remote-logs-transfer','An attacker clears an application server’s local logs. Which earlier measure best preserves independently accessible copies?', [('Forwarding logs to a secured remote collector','Retains a separate protected copy if forwarding succeeded.'),('Renaming the local log directory','Does not establish an independent copy.'),('Disabling time synchronization','Makes correlation less reliable.'),('Giving the application administrator deletion rights on every log store','Extends the attacker’s potential deletion reach.')], 'A separately protected copy survives local deletion.','transfer')
q(T,'spray-transfer','Authentication records show one failed attempt against each of 80 accounts using the same candidate password. Which pattern best fits?', [('Password spraying','A small password set is tried across many accounts.'),('Single-account brute force','Would typically show many guesses against one account.'),('Directory traversal','Manipulates file paths, not this authentication pattern.'),('Confirmed credential theft','Failures alone do not show that credentials were obtained.')], 'One guess spread across many identities.','transfer')

T=track('governance','Data roles, risk choices & due care',{'B8':None,'B28':None,'B29':None,'B80':None},['5.1','5.2','5.4'],
 'Who decides? Who performs? Who is described? And who now bears the risk?',
 'Business authority, privacy roles and operational work overlap in real organizations. In an exam, choose the role described by the actual responsibility, not the most senior-sounding word.',
 [['Data subject','The person the personal data is about.'],['Controller / owner','Controller: purpose and means of personal-data processing. Owner: business accountability and protection requirements for an asset.'],['Processor / custodian','Processor: processes for a controller. Custodian: operates storage, backups and access under policy.'],['Steward','Maintains data quality, definitions and governance practices.']],
 [['Data owner','Accountable business authority','Decides the asset’s protection and access requirements.','Need not personally operate the backup system.'],['Data controller','Purpose and means of processing','Decides why and how personal information is processed.','Not the individual whose information is stored.'],['Data processor','Acts for the controller','Processes personal information on the controller’s behalf.','Does not automatically own the business purpose.'],['Data subject','Person described','A customer whose address is stored.','Not the server, database or administrator.'],['Acceptance','Retain the risk','Continue the activity while consciously bearing the exposure.','Canceling insurance is not still transferring that cost.'],['Transfer','Shift some consequences','Use an insurance policy or contractual allocation.','Does not remove all responsibility or technical risk.'],['Mitigation','Reduce likelihood or impact','Apply controls such as patching and recovery capabilities.','Still leaves residual risk.'],['Avoidance','Stop the risk-producing activity','Discontinue the activity entirely.','Canceling only insurance does not avoid the original activity.']],
 {'scenario':'A business keeps operating its customer portal but cancels cyber insurance. Management explicitly accepts the uninsured loss exposure. No new technical control is introduced.', 'clues':['The portal continues to run.','The insurance transfer ends.','Management consciously retains the loss exposure.'],'answer':'Risk acceptance','because':'The decision is about who now bears the potential loss. Stopping insurance does not stop the risky business activity.','trap':'Reading the old insurance arrangement instead of the new decision leads to “transfer.”'},
 'Transfer: due care is taking reasonable protective action; due diligence includes investigation and ongoing assessment. They can overlap—do not treat “audit” as an automatic keyword. A control implementation describes protection; a pre-acquisition investigation describes evaluation. Residual risk remains after controls. Data stewards focus on quality/governance; custodians operate protection mechanisms.',
 [['NIST: risk response','https://csrc.nist.gov/glossary/term/risk_response'],['ICO: controller and processor roles','https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/controllers-and-processors/what-are-controllers-and-processors/']])
q(T,'owner','A business manager sets the classification and required backup frequency for the department’s records. IT implements those requirements. What role is the manager performing?', [('Data owner','Sets business protection requirements and is accountable for the asset.'),('Data custodian','Would operate the storage and backup mechanisms.'),('Data subject','Is the person the personal data describes.'),('Data processor solely because of job title','The stated task is business accountability, not merely processing for another party.')], 'Sets requirements while someone else implements them.')
q(T,'subject','An online store retains a customer’s shipping address. In privacy terminology, what is the customer’s role in relation to that information?', [('Data subject','The information describes that person.'),('Data controller','The store determines the processing purpose in this scenario.'),('Data processor','Would process for the controller.'),('Data custodian','Would operate the storage or protection systems.')], 'The person whom the data describes.')
q(T,'controller','An organization decides why personal data will be collected and how it will be used. A contractor processes it only on that organization’s instructions. What is the organization?', [('Data controller','Determines the purposes and means of processing.'),('Data processor','The contractor performs that stated role.'),('Data subject','The people described by the information fill that role.'),('Storage custodian only','The described authority goes beyond operating storage.')], 'Decides purpose and means.')
q(T,'acceptance','A company cancels its insurance, continues the insured activity, and explicitly elects to bear the possible losses itself. Which response now applies?', [('Acceptance','It retains the risk and its consequences.'),('Transfer','The insurance transfer has just ended.'),('Avoidance','The activity continues.'),('Mitigation','No new likelihood/impact-reducing measure is described.')], 'Classify the new decision, not the former insurance.')
q(T,'mitigation','A firm keeps an exposed service but patches it and restricts incoming access to reduce attack likelihood. Which response is shown?', [('Mitigation','The controls reduce risk while the activity remains.'),('Avoidance','The service has not been discontinued.'),('Transfer','No shift of consequences to another party is stated.'),('Acceptance without treatment','Protective treatment is explicitly applied.')], 'Continue the activity with risk-reducing controls.')
q(T,'avoidance','Management stops collecting a category of sensitive data because it no longer wants the associated exposure. Which response best describes this decision?', [('Avoidance','The risk-producing collection activity stops.'),('Transfer','No third party is taking over the exposure.'),('Acceptance','Management is not continuing that exposure unchanged.'),('Insurance mitigation','No insurance transaction is described.')], 'Remove the activity creating this particular risk.')
q(T,'due-care','A company deploys required access controls and backup safeguards to responsibly protect its customer records. Which concept most directly describes taking these protective steps?', [('Due care','Taking reasonable protective action fulfills a duty of care.'),('Active reconnaissance','Probing a target is not the purpose of these safeguards.'),('Data retention','Specifies how long information is kept, not the full protective duty.'),('Exfiltration','Unauthorized removal of data is unrelated to implementing safeguards.')], 'Reasonable protective action is actually being taken.')
q(T,'diligence-transfer','Before selecting a provider, a team investigates its security practices, checks evidence and assesses its risks. Which concept best captures this investigation?', [('Due diligence','Investigation and assessment support an informed decision.'),('Risk avoidance automatically','No decision to abandon the activity has yet been made.'),('Non-repudiation','Concerns accountability for actions, not vendor investigation.'),('Data masking','Conceals display values, not due investigation.')], 'Investigation before commitment.','transfer')
q(T,'custodian-transfer','IT staff perform backups and restore tests according to requirements set by the business owner. Which operational role best fits?', [('Data custodian','Operates protection mechanisms under established requirements.'),('Data subject','Is the person the data describes.'),('Data controller solely because they run backups','Operating a task does not by itself determine processing purposes.'),('Data steward solely because they handle storage','Stewardship emphasizes quality/governance rather than this backup operation.')], 'Implements the owner’s requirements.','transfer')
q(T,'residual-transfer','After segmentation and patching reduce an assessed risk, management reviews the exposure still remaining. What is that remaining exposure called?', [('Residual risk','The risk that remains after treatment.'),('Inherent risk','Exposure before considering the controls.'),('Transferred ownership of all liability','Controls do not automatically transfer liability.'),('Eliminated risk','The scenario explicitly says exposure remains.')], 'After controls, some risk remains.','transfer')
T=track('assets','Reconnaissance, enumeration & system boundaries',{'B9':None,'B12':None,'B15':None,'B70':None,'B71':None},['2.3','3.1','4.2','4.3','5.5'],
 'Name the activity or boundary from the evidence—not from an assumed outcome.',
 '“Enumeration” means listing/discovering items; its object matters. Public-information gathering, active probing, asset comparison and crossing an isolation boundary are distinct activities.',
 [['Public information','Read an existing public report: gather OSINT without probing the target service.'],['Target interaction','Send probes to a target: active reconnaissance.'],['Inventory snapshot','Enumerate hardware or software: list components, then compare snapshots to detect change.'],['Boundary crossing','A guest reaches host or another isolated guest: investigate an escape of isolation.']],
 [['OSINT — Open-Source Intelligence','Gather publicly available information','Use public websites, reports or social posts.','Not automatically exfiltration from a protected system.'],['Active reconnaissance','Interact with the target','Probe its exposed services.','Reading a third-party public report need not probe the target.'],['Partially known environment','Some internal/test context supplied','The tester receives limited information rather than comprehensive details.','Describes tester knowledge, not whether probes are active.'],['Enumeration','List or discover items','List hardware, accounts or web paths; specify which.','Does not mean multifactor authentication or automatic malware removal.'],['Embedded system','Dedicated function within a device','Purpose-built controller or appliance with limited interfaces.','Limited access alone does not prove vendor support has ended.'],['End-of-life','Lifecycle/support status','Vendor has ended the relevant supported lifecycle.','A dedicated appliance is not necessarily end-of-life.'],['VM escape','Break guest isolation','Guest execution reaches host resources or crosses guest isolation.','A VM merely running an app is ordinary virtualization.']],
 {'scenario':'Each login records a laptop’s storage serial number and memory configuration. A comparison with yesterday’s snapshot identifies a newly installed drive.', 'clues':['Components are listed.','Two snapshots are compared.','The observed difference is hardware configuration.'],'answer':'Asset enumeration plus change detection','because':'Listing components provides inventory. Comparing that inventory identifies changes.','trap':'The word “login” does not imply multifactor authentication; the described measurement concerns the laptop’s hardware.'},
 'Transfer: web enumeration probes resource names; asset enumeration inventories components. A 404 response means the requested resource was not found in that response, not that the server is completely secure. A 200 response alone does not prove malicious exfiltration. Keep evidence narrower than the conclusion. Test knowledge level and active/passive technique are separate axes.',
 [['NIST: penetration testing','https://csrc.nist.gov/glossary/term/penetration_testing'],['OWASP: information gathering','https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/01-Information_Gathering/']])
q(T,'osint','An assessor reads archived public news releases to identify the technologies a company uses, without contacting its systems. Which activity is described?', [('OSINT collection','Uses publicly available information.'),('Active service scanning','Requires probing the target’s services, which is absent here.'),('Exfiltration','Would involve unauthorized removal of protected data.'),('Privilege escalation','Requires gaining additional system rights.')], 'Existing public information without target probing.')
q(T,'active-recon','An authorized tester sends connection probes to a target’s ports to determine which services respond. What technique is being used?', [('Active reconnaissance','Direct interaction elicits target responses.'),('Passive collection from public archives','No longer passive: probes are sent to the target.'),('Data retention','Concerns keeping records, not service discovery.'),('Certificate revocation','Invalidates certificates, not maps exposed services.')], 'The tester deliberately interacts with the target.')
q(T,'knowledge','A tester receives a limited network diagram and one low-privilege account, but not source code or complete architecture. Which knowledge category fits best?', [('Partially known environment','The tester has some but incomplete internal information.'),('Fully known environment','The scenario explicitly withholds comprehensive details.'),('Unknown environment','Internal context and credentials were supplied.'),('Passive reconnaissance','That is a technique, not the amount of prior knowledge.')], 'Some supplied knowledge, not complete knowledge.')
q(T,'inventory','An agent lists installed hardware at every login and compares it with a baseline. What does this most directly support?', [('Detecting hardware configuration changes','Enumeration plus comparison reveals additions or modifications.'),('Requiring a second authentication factor','Inventory alone does not impose another factor.'),('Deleting every malicious file automatically','Listing components is not malware remediation.'),('Encrypting all network packets','Inventory does not provide transport encryption.')], 'List components, then compare changes.')
q(T,'embedded','A purpose-built environmental controller runs a dedicated function with no general-user operating-system interface. Support is still available. Which description best fits?', [('Embedded system','A dedicated system within an appliance.'),('End-of-life system','The prompt explicitly says support remains available.'),('Software-defined networking','Separates network control functions; not established here.'),('Hypervisor escape','An isolation failure is not described.')], 'Dedicated appliance function; no evidence of ended support.')
q(T,'escape','Code inside an isolated guest exploits the hypervisor and gains access to host resources it should not reach. What is the failure?', [('VM escape','The guest crosses its isolation boundary.'),('Normal resource provisioning','Authorized provisioning does not describe an exploit of isolation.'),('Password spraying','Attempts a small password set across accounts.'),('Data masking','Hides displayed values rather than crossing isolation.')], 'Guest code reaches beyond its permitted boundary.')
q(T,'end-of-life','A vendor announces that a product will no longer receive security fixes after a stated date. Which issue is directly established after that date?', [('End-of-support exposure','The stated issue is loss of vendor security updates.'),('All devices are already compromised','No compromise evidence is provided.'),('Every device is an embedded system','Lifecycle status does not determine system architecture.'),('The product has escaped a hypervisor','No isolation failure is described.')], 'Use the explicit support-lifecycle fact.')
q(T,'web-enumeration-transfer','A client requests /config.old, /backup.sql and /admin-test in rapid succession. No authentication requests appear. What is the best initial classification?', [('Web resource enumeration','Different potential files and paths are being discovered.'),('Password spraying','No password attempts across accounts are shown.'),('Hardware inventory','These are web paths, not component listings.'),('Confirmed remote code execution','Requests alone do not demonstrate execution.')], 'What is being enumerated? Web resources.','transfer')
q(T,'axes-transfer','A tester has complete architecture documents and then sends probes to a server. Which description is consistent?', [('Known environment with active reconnaissance','Knowledge level and technique can both describe this test.'),('Unknown environment because packets were sent','Sending probes does not erase supplied knowledge.'),('Passive reconnaissance because documentation exists','The probing step is active regardless of documents.'),('No penetration test can use internal information','Known-environment tests do use such information.')], 'Two different axes, not mutually exclusive labels.','transfer')
q(T,'evidence-transfer','A log records HTTP 200 for /downloads/report.pdf. Which conclusion is justified from that line alone?', [('The server reported success for that request','That is the observation; authorization, content and intent need context.'),('Sensitive information was certainly stolen','The record alone does not establish sensitivity or unauthorized theft.'),('The requester was certainly an administrator','No role information is given.'),('The server has no vulnerabilities','One successful response cannot establish that.')], 'Do not turn an observation into an unsupported full story.','transfer')

T=track('decisions','BEST / NEXT: choose the decisive clue',{'B16':None,'B62':None},['2.1','2.2','5.2'],
 'Ask → evidence → constraint → choice. Do not invent a missing condition.',
 'Several options can be reasonable in real life. Rank them against the stated asset, exposure, objective and timeline. If a practice question mixes impact and vulnerability language, acknowledge the ambiguity rather than memorizing an absolute rule.',
 [['Ask','Does it request a risk, a control, a cause, or a next action?'],['Evidence','What is actually stated or demonstrated?'],['Constraint','Which requirement makes one plausible option fit better?'],['Choice','Choose the option meeting that requirement with the fewest added assumptions.']],
 [['FIM — File Integrity Monitoring','Detect file changes','Compare protected files with an approved baseline.','Not primarily a control for sensitive data leaving the organization.'],['DLP — Data Loss Prevention','Prevent inappropriate data disclosure','Detect or block sensitive information sent to unauthorized destinations.','Not simply a file-change detector.'],['Threat vector','Route or means of access','A malicious attachment or exposed service.','Not the same category as the resulting financial loss.'],['Vulnerability','Weakness that can be exploited','An unpatched reachable service.','A potential consequence is not itself the weakness.'],['Impact','Consequence to the organization','Loss of proprietary designs or disrupted operations.','An impact-focused answer needs the business context.'],['Likelihood / exposure','How feasible or reachable the attack is','Public reachability can matter for an external adversary.','Do not assume all threat actors have physical/internal access.'],['NEXT','Current phase plus immediate objective','After compromise is established, limit spread before cleanup.','Do not automatically restart detection regardless of the evidence.'],['BEST','Fit to stated constraints','A specific web-input filter fits web-input attacks.','The longest answer or broadest product is not automatically best.']],
 {'scenario':'An external adversary with no internal access wants to publish customer records. A public database has a known exploitable flaw. A disconnected lab terminal also has an outdated password policy.', 'clues':['The adversary is external with no internal foothold.','Customer records are the stated target.','The vulnerable database is publicly reachable.'],'answer':'Prioritize the public database exposure','because':'Reachability, exploitability and the target asset all line up. The isolated terminal is a concern but needs additional access assumptions.','trap':'“All are problems” is true but does not answer which most directly enables this specific scenario.'},
 'Transfer: change one fact and the best answer can change. If the attacker is already inside, internal controls become more relevant. If the prompt asks for a business consequence, answer an impact; if it asks for an exploitable weakness, answer a vulnerability. One ambiguous practice item should not become a universal technical rule.',
 [['NIST: risk assessment guide','https://csrc.nist.gov/pubs/sp/800/30/r1/final']])
q(T,'external-exposure','An external attacker with no internal foothold wants customer records. Which finding most directly enables that objective?', [('An Internet-reachable customer database with a known exploitable flaw','It combines reachability, a usable weakness and the target data.'),('A disconnected test terminal with an old local password','Would require additional access not supplied by the scenario.'),('A locked archive cabinet missing an inventory label','A concern, but not a direct remote path to the records.'),('A lab VLAN with an undocumented printer name','Does not establish a direct exploitable path to the target.')], 'Match attacker access, exploitable route and desired asset.')
q(T,'impact','A design firm allows personally owned cameras in a restricted prototype room. The question asks for the primary business consequence of unauthorized photography. Which answer is the right category?', [('Loss of proprietary design information','Describes the resulting business impact.'),('A camera lens','A device component, not the consequence.'),('An unpatched camera operating system','A possible weakness, not the stated impact of photography.'),('A device-management policy','A potential control rather than a consequence.')], 'The question explicitly asks for a consequence.')
q(T,'vulnerability','Which statement identifies a vulnerability rather than a business impact?', [('A public service lacks a patch for a known exploitable flaw','Describes an exploitable weakness.'),('Customer trust declines after a breach','A consequence.'),('Production stops for a day','An operational impact.'),('Proprietary plans are disclosed','An information-loss impact.')], 'Name the weakness, not the harm that could follow.')
q(T,'constraint','A requirement is to stop unauthenticated Internet users from reaching an admin page while allowing staff through an approved internal path. Which action most directly meets it?', [('Restrict the admin endpoint to the approved path and authorized users','Directly addresses reachability and access to this endpoint.'),('Collect more disk-capacity metrics','Does not restrict that access.'),('Increase the public web server’s bandwidth','May improve availability but not this access requirement.'),('Rename the administrator’s desktop shortcut','Does not change server reachability or authorization.')], 'Access restriction is the requirement; choose an access control.')
q(T,'next','Compromise is confirmed, evidence collection is arranged, and the response lead authorizes isolation to stop active spread. Which action fits NEXT?', [('Execute the authorized containment','The scenario has already established the need and authority.'),('Assume no incident until every historical event is reviewed','Ignores the confirmed compromise and active spread.'),('Immediately declare the system fully recovered','Recovery is not yet established.'),('Begin a lessons-learned meeting instead of containment','Improvement review does not stop the ongoing harm.')], 'Start from the state the prompt already established.')
q(T,'evidence','An alert reports an unexpected login location. Which initial conclusion requires the fewest unsupported assumptions?', [('The location is anomalous and needs validation with context','It may indicate misuse, but VPNs and other factors can affect apparent location.'),('The user is certainly malicious','Intent is not established.'),('Every account in the company is compromised','One alert does not support that scope.'),('The monitoring system must be broken','A true anomaly is also possible.')], 'An anomaly is evidence to investigate, not a complete attribution.')
q(T,'specificity','A team specifically needs to detect unauthorized changes to a protected configuration file. Which control is the closest fit?', [('FIM — File Integrity Monitoring','Compares file state to detect changes.'),('DLP — Data Loss Prevention','Targets improper data movement/disclosure, not simply file modification.'),('VPN tunnel termination','Protects a connection, not the file baseline.'),('Certificate renewal','Maintains certificates, not configuration-change detection.')], 'Changed file versus data leaving: choose the stated property.')
q(T,'changed-fact-transfer','Change the previous external-attacker scenario: a malicious insider already has physical access to a shared terminal with no session lock. Which fact now matters directly?', [('The insider can use an unattended authenticated session','The revised access condition makes that route relevant.'),('Physical access must always be ignored','The prompt explicitly supplies it.'),('Only Internet-facing weaknesses can ever matter','The attacker is now inside.'),('Every public database must be compromised first','That extra step is not required for the stated session risk.')], 'Changed access changes the ranking.','transfer')
q(T,'counterfactual-transfer','You are deciding between FIM and DLP. Which extra requirement would make DLP the better fit?', [('Block sensitive records from being uploaded to an unauthorized destination','That is data-loss prevention.'),('Alert when a local configuration file hash changes','That is file-integrity monitoring.'),('Identify whether a signed executable changed after signing','Integrity verification is the direct property.'),('Compare today’s system-file baseline to yesterday’s','That still describes integrity/change monitoring.')], 'Ask what fact would make the other choice correct.','transfer')
q(T,'ambiguity-transfer','A practice item uses “threat vector” but its explanation chooses a business impact. What is the soundest study takeaway?', [('Learn the stated impact rationale while keeping vector and impact distinct','Acknowledges the item’s ambiguity without corrupting the underlying concepts.'),('Redefine every impact as a threat vector','Would create a false general rule.'),('Always select the largest-sounding loss in later questions','Ignores later wording and evidence.'),('Assume every plausible distractor is equally correct in all scenarios','Constraints still distinguish options in well-specified scenarios.')], 'Keep technical definitions stable even when practice wording is imperfect.','transfer')

# Strengthen nearby alternatives: the distinction, rather than an unrelated option, does the work.
def revise(track_id,n,options):
 item=next(t for t in tracks if t['id']==track_id)['questions'][n-1]
 item['options']=[v[0] for v in options];item['explanations']=[v[1] for v in options]
revise('pki',4,[('The client’s trusted CA configuration','A missing or incorrect trust anchor explains the untrusted issuer.'),('Whether the server’s certificate covers the requested name','A real certificate check, but the scenario explicitly says the name is correct.'),('Whether the certificate has expired','A real validation failure, but the dates are stated to be valid.'),('Whether the user account has permission to join the network','Authorization can fail after authentication; it does not repair issuer trust.')])
revise('pki',6,[('Resistance to brute-force authorization attempts','TPM dictionary-attack logic limits repeated guesses.'),('Validation of the software measured during boot','Boot measurement is another TPM use, but the evidence here is repeated-guess throttling.'),('Protection against exporting the disk-unlock key','Protected key storage is useful, but the observed delay specifically targets guessing.'),('Recovery after an authorized hardware replacement','Recovery is a separate workflow; throttling does not recover a key.')])
revise('pki',9,[('An HSM-backed signing service','Authorized cryptographic operations occur while the key remains protected.'),('A software signer that decrypts an exported key into application memory','Performs signing but conflicts with the non-exposure requirement.'),('An encrypted key file whose password is held by the signing process','Protects storage, but the application still obtains the usable key.'),('A backup escrow service that returns the private key for each request','Supports recovery but returns key material instead of keeping it inside a signing boundary.')])
revise('pki',10,[('Deploy a certificate covering the requested server name','Directly addresses name validation.'),('Add the same issuer to the trust store again','Issuer trust is already satisfied.'),('Obtain a fresh OCSP response for the existing certificate','Revocation status does not change name coverage.'),('Renew the certificate with exactly the same subject names','Extends validity dates without fixing the mismatched name.')])
revise('access',3,[('NAC','Posture/admission policy restricts the device to remediation access.'),('A SIEM correlation rule that alerts on expired agents','Observes the issue but does not itself enforce admission.'),('A VPN gateway configured only to validate user credentials','User identity alone does not implement the required device-posture restriction.'),('An MDM inventory report listing outdated agents','Identifies device state but does not itself apply the stated network admission decision.')])
revise('access',5,[('MDM','Provides managed policy and wipe capabilities for tablets.'),('A SIEM collecting the tablets’ security events','Collects evidence but is not the primary device-management mechanism.'),('A NAC rule restricting corporate network entry','Can restrict entry but does not manage a lost device away from that network.'),('A WAF protecting the tablet application’s server','Protects server-side web input, not the tablet’s local configuration and wipe function.')])
revise('data',5,[('Credentials crossed the captured link without effective transport confidentiality','Readable credentials directly demonstrate exposure on that path.'),('An obsolete but functioning cipher was used on the captured link','Weak encryption is a concern, but readable cleartext alone does not establish a particular cipher.'),('The server stored its password database without salts','A packet capture does not establish the database storage format.'),('A certificate-authority private key was compromised','No evidence of issuer-key compromise is supplied.')])
revise('data',6,[('Journaling','Records transactions to support consistent crash recovery.'),('A checksum comparison alone','Can detect changed data but does not itself replay pending updates.'),('A scheduled full backup','Provides a recovery copy, but the described mechanism consults update records.'),('Whole-disk encryption','Protects confidentiality, not pending filesystem transaction consistency.')])
revise('data',7,[('Digital signature','Provides publisher-origin and integrity verification while content remains readable.'),('An unsigned checksum posted beside the file on the same untrusted mirror','Can reveal accidental differences but an attacker can replace both file and checksum.'),('Encryption with a key distributed to every customer','Shared-key encryption does not uniquely establish the publisher as signer.'),('A file-size comparison against the previous release','Matching size neither proves origin nor excludes modification.')])
revise('response',2,[('A custody record with identities, times and evidence-item details','Documents the specific handoff and custodians.'),('Only a cryptographic hash of the drive image','Supports integrity comparison but does not identify who held it.'),('Only a preservation notice for relevant data','Requires retention but does not document this transfer.'),('Only the search terms used during evidence review','Supports the review process, not possession history.')])
revise('response',3,[('Suspend the applicable deletion under legal hold','Directly preserves the records from routine destruction.'),('Calculate a hash while leaving the deletion job enabled','A digest cannot reconstruct deleted contents.'),('Record the mailbox administrator’s name in a custody form only','A custody record alone does not stop scheduled deletion.'),('Create a report listing matching messages without preserving them','A listing is not preservation of the actual responsive material.')])
revise('response',4,[('Its enabled host firewall log','The endpoint observes its own connections on the hotspot route.'),('The bypassed corporate gateway’s traffic log','The flow does not traverse that gateway.'),('The corporate wireless controller’s connection log alone','Can show departure from corporate Wi-Fi, but not necessarily the later outbound hotspot flows.'),('The corporate DNS resolver’s log when the hotspot uses another resolver','A resolver that is not queried cannot record those lookups.')])
revise('assets',4,[('Detecting hardware configuration changes','Component listings compared with a baseline reveal changes.'),('Verifying that the person logging in used two factors','Hardware inventory does not establish the authentication method.'),('Determining which public services an external scanner can reach','Local hardware inventory is not an external service-reachability test.'),('Proving all installed software is patched','A hardware snapshot does not by itself verify software patch state.')])
revise('decisions',4,[('Restrict the admin endpoint to the approved path and authorized users','Directly meets the reachability and access constraint.'),('Alert in the SIEM whenever the public admin page is requested','Detection does not prevent unauthenticated reachability.'),('Encrypt the public connection while leaving the admin endpoint unrestricted','Confidentiality of the path does not implement the requested access restriction.'),('Back up the admin server more frequently','Recovery readiness does not restrict current access.')])
revise('decisions',7,[('FIM — File Integrity Monitoring','Compares file state to detect unauthorized changes.'),('DLP — Data Loss Prevention','Targets inappropriate data movement or disclosure rather than any file change.'),('NAC — Network Access Control','Controls admission or posture, not specifically a protected file baseline.'),('A network intrusion sensor without host-file telemetry','Can observe network activity but lacks the stated local file comparison.')])

assert len(tracks)==8
ids=set();prompts=set()
for t in tracks:
 assert len(t['questions'])==10
 assert sum(q['scope']=='core' for q in t['questions'])==7
 for question in t['questions']:
  assert question['id'] not in ids and question['prompt'] not in prompts
  ids.add(question['id']);prompts.add(question['prompt'])
  assert len(set(question['options']))==4 and len(question['explanations'])==4
Path('js/targeted-data.js').write_text('/* Original targeted teaching and questions; no personal results are embedded. */\nwindow.TARGETED_TRACKS='+json.dumps(tracks,ensure_ascii=False,separators=(',',':'))+';\n')
print(f'{len(tracks)} tracks / {len(ids)} original questions')
