import json
from pathlib import Path
courses={'acronyms':[],'ports':[]}
def lesson(kind,title,objective,terms,teach,flow,example,trap,questions):
 courses[kind].append(dict(title=title,objective=objective,terms=terms.split('|'),teach=teach,flow=flow.split('|'),example=example,trap=trap,questions=[dict(prompt=q[0],options=q[1].split('|'),correct=0,explanations=q[2].split('|')) for q in questions]))
def A(*a):lesson('acronyms',*a)
def P(*a):lesson('ports',*a)
A('Security goals and identity','1.2','CIA|AAA|IAM|MFA|SSO',
'Begin with the outcome. Confidentiality limits who can read data; integrity detects unauthorized changes; availability keeps services usable. Authentication proves identity, authorization decides permission, and accounting records activity. IAM manages this lifecycle. MFA needs different factor categories; two passwords are still one category. SSO reduces repeated sign-ins, so protecting its central identity provider matters.',
'Identify the security goal|Authenticate the person|Authorize the action|Record what happened',
'A badge reader identifies a technician, an access policy permits only the equipment room, and an event log records entry. Those are authentication, authorization, and accounting. Keeping the log unaltered protects integrity.',
'Do not treat authentication as permission. A successfully signed-in user can still be denied access.',[
('A technician signs in successfully but cannot open payroll records. Which AAA function made that decision?','Authorization|Authentication|Accounting|Availability','Authorization evaluates permissions for the requested resource.|Authentication already succeeded; it established identity.|Accounting records actions and decisions.|Availability concerns whether services can be used, not individual permissions.'),
('A company adds a PIN after a password and calls it MFA. What is the BEST assessment?','Both are knowledge factors|The PIN is a possession factor|Two prompts always provide MFA|SSO makes them separate factors','Both are something you know; add a possession or inherence factor.|Remembering a PIN does not require possession of a device.|Factor categories, not prompt count, determine MFA.|SSO changes the sign-in experience, not the factor category.'),
('A defender compares a downloaded file with a trusted published digest. Which CIA goal is being checked?','Integrity|Confidentiality|Availability|Authorization','A matching trusted digest supports that the file has not changed.|A digest does not hide the file contents.|This check does not keep a service online.|A digest comparison does not grant access.')])
A('Permissions and federation','4.6','RBAC|ABAC|PAM|SAML|OAuth|OIDC|FIDO',
'RBAC grants permissions through job roles. ABAC evaluates attributes such as department, device posture, time, and data classification. PAM limits privileged access and can issue temporary credentials. SAML carries federation assertions, OAuth delegates authorization, and OIDC adds identity to OAuth. FIDO supports public-key authentication; an origin-bound security key helps resist phishing.',
'User requests access|Identity assertion or authentication|Role or attribute policy|Time-limited privilege',
'A contractor signs in through the company identity provider. A policy checks contract status, a managed device, and work hours before allowing a privileged session. Federation handles identity; ABAC decides access; PAM controls the elevated session.',
'OAuth alone is not a user authentication protocol. OIDC adds an identity layer.',[
('Access requires a managed device, an active contract, and a daytime shift. Which model BEST represents this policy?','ABAC|RBAC|SSO|PAM','ABAC evaluates multiple attributes and context.|RBAC bases permissions on roles; the scenario emphasizes context attributes.|SSO avoids repeated authentication, not policy decisions.|PAM manages elevated accounts; it does not name this policy model.'),
('A calendar app needs permission to read a user’s contacts without learning the password. Which framework fits?','OAuth|SAML|FIDO|RBAC','OAuth delegates scoped authorization using tokens.|SAML commonly federates authentication assertions.|FIDO authenticates users with public-key credentials.|RBAC assigns permissions by role rather than delegating API access.'),
('Administrators should receive temporary elevated credentials with session recording. What is the BEST control?','PAM|OIDC|SSO|SAML','PAM manages and monitors privileged sessions and credentials.|OIDC supplies identity information, not privileged-session management.|SSO consolidates sign-ins but does not enforce temporary privilege.|SAML exchanges assertions rather than managing administrator sessions.')])
A('Certificates and protected keys','1.4','PKI|CA|CSR|CRL|OCSP|TPM|HSM|TLS',
'PKI binds identities to public keys using certificates and trust chains. A CA signs certificates. Generate a key pair locally, keep the private key secret, and send a CSR containing the public key. CRLs publish revocations; OCSP checks status. A TPM protects device-bound keys and measurements; an HSM performs protected key operations for a service. TLS protects network sessions when configured and validated correctly.',
'Generate key pair|Send CSR, keep private key|CA signs certificate|Validate trust, name, time, revocation',
'A web server sends its CSR to a CA. The browser checks the resulting certificate against the requested hostname and a trusted chain. A revoked certificate can still be within its expiration dates, so expiration alone is insufficient.',
'A CSR does not contain the private key. Encryption without authenticating the peer can still connect you to an attacker.',[
('A server needs a certificate signed. Which item should leave the server for the CA?','CSR|Private key|TPM recovery secret|CA signing key','The CSR carries the public key and requested identity details.|The private key must remain protected on the server or key device.|A device recovery secret is unrelated and should not be disclosed.|The CA owns its signing key; the server should never receive it.'),
('A client needs an online answer about whether one certificate has been revoked. Which mechanism fits?','OCSP|CSR|HSM|TLS','OCSP requests status for a particular certificate.|A CSR requests issuance, not revocation status.|An HSM protects key operations, not status queries.|TLS secures sessions; certificate revocation checking is a separate validation concern.'),
('A signing service needs protected keys and high-volume cryptographic operations in dedicated hardware. Which is BEST?','HSM|TPM|CRL|CA certificate','An HSM is designed to protect keys and perform service-side cryptographic operations.|A TPM is typically tied to a platform’s trust and boot measurements.|A CRL is published revocation data.|A CA certificate contains public information, not secure key-processing hardware.')])
A('Network detection and access','3.2','IDS|IPS|WAF|NAC|802.1X|RADIUS|TACACS+',
'An IDS observes and alerts; an IPS is positioned to prevent traffic. A WAF understands web requests and can filter application attacks. NAC evaluates who or what may join the network; 802.1X provides port-based authentication using an authenticator and an authentication service. RADIUS commonly supports network-access AAA. TACACS+ is commonly used for device administration with separated AAA functions.',
'Endpoint requests network access|Switch relays authentication|AAA service evaluates identity|NAC applies access policy',
'A laptop attaches to a switch. The switch uses 802.1X and RADIUS before opening normal access. An IDS later detects unusual traffic; an inline IPS can block it. A WAF protects the web application specifically.',
'An IDS alert does not mean traffic was blocked. A WAF is not a replacement for all network firewall rules.',[
('A sensor sees an exploit and raises an alert, but traffic continues. Which device behavior is shown?','IDS|IPS enforcement|NAC admission|WAF blocking','IDS detects and alerts without necessarily blocking.|IPS enforcement would prevent the matching traffic.|NAC admission controls entry to the network.|WAF blocking would reject matching web requests.'),
('A public website needs filtering of malicious HTTP parameters. Which is the BEST fit?','WAF|RADIUS|TACACS+|802.1X','A WAF inspects web application traffic and request patterns.|RADIUS supplies network-access AAA.|TACACS+ provides administrative AAA for devices.|802.1X authenticates access at a network port.'),
('The security team wants switch ports to require user or device authentication before normal access. Which standard fits?','802.1X|TLS|OCSP|SAML','802.1X provides port-based network access authentication.|TLS secures sessions but does not define switch-port admission.|OCSP checks certificate revocation status.|SAML supplies federation assertions for services.')])
A('Tunnels and cloud boundaries','3.1','VPN|IPsec|ESP|AH|PSK|CASB|CSPM|ZTNA|SD-WAN|IaC',
'A VPN protects traffic across an untrusted path. IPsec is a suite: ESP can encrypt and authenticate, while AH provides integrity and authentication without confidentiality. A PSK is a shared secret used for authentication. CASB applies policy around cloud service use; CSPM finds cloud configuration weaknesses. ZTNA grants access to specific applications after explicit checks. SD-WAN steers WAN traffic; IaC defines infrastructure through versioned configuration.',
'Check identity and device|Permit required application|Protect traffic|Monitor configuration drift',
'A company finds publicly exposed storage through CSPM, applies cloud-use policies through a CASB, and gives contractors access to one application through ZTNA. These products solve different problems despite all appearing in cloud architecture.',
'AH is not encryption. A VPN connection alone should not imply permission to reach every internal system.',[
('A tunnel must conceal packet payloads. Which IPsec component can provide confidentiality?','ESP|AH|PSK alone|SD-WAN alone','ESP supports payload encryption along with integrity services.|AH authenticates and checks integrity but does not encrypt payloads.|A PSK authenticates peers; it is not itself a data-protection protocol.|SD-WAN steers traffic; confidentiality depends on its configured security mechanisms.'),
('A tool repeatedly finds public storage buckets and overly broad cloud permissions. Which capability is this?','CSPM|CASB|SD-WAN|AH','CSPM evaluates cloud configuration and security posture.|CASB focuses on policy enforcement around cloud service access and use.|SD-WAN manages WAN connectivity.|AH provides IPsec integrity and authentication.'),
('Contractors should reach only an approved application after identity and device checks. Which model fits BEST?','ZTNA|Unrestricted VPN access|AH|IaC','ZTNA grants application-specific access based on explicit checks.|Broad network access exceeds the required application scope.|AH is a packet-protection component, not an access model.|IaC describes infrastructure configuration, not this access decision.')])
A('Detection, response, and data loss','4.4','SIEM|SOAR|EDR|XDR|DLP|IR|IoC|IoA',
'SIEM collects and correlates events. SOAR runs coordinated response workflows. EDR investigates and responds on endpoints; XDR joins signals across security layers. DLP focuses on unauthorized data movement. An IoC is evidence suggesting compromise, while an IoA describes suspicious attack behavior. Incident response uses preparation, analysis, containment, eradication, and recovery with lessons learned.',
'Collect signals|Correlate and investigate|Contain with authorization|Recover and improve',
'A SIEM connects an unusual login with a large download. EDR isolates the laptop. DLP blocks an upload of customer data. SOAR can coordinate these actions through an approved playbook; it does not remove the need to validate evidence.',
'Collecting logs is not the same as automating response. Select the capability the question actually requests.',[
('Analysts need to correlate firewall, identity, and server logs on a common timeline. Which is BEST?','SIEM|DLP|HSM|PAM','SIEM aggregates and correlates security events across sources.|DLP addresses unauthorized disclosure of sensitive data.|HSM protects cryptographic keys and operations.|PAM manages privileged access rather than general event correlation.'),
('An approved playbook should open a ticket, isolate a host, and block a hash across tools. Which capability fits?','SOAR|SIEM collection only|CRL|NAC admission only','SOAR orchestrates and automates actions across security tools.|Collection and correlation alone do not execute the workflow.|A CRL lists revoked certificates.|NAC admission alone does not coordinate the multi-tool playbook.'),
('A control detects account numbers being sent to personal cloud storage and stops the transfer. What is it?','DLP|XDR correlation|OCSP|SAST','DLP identifies sensitive data and enforces handling restrictions.|XDR connects detection across layers; the described data-handling control is DLP.|OCSP checks certificate status.|SAST analyzes source or compiled code without running the application.')])
A('Vulnerabilities and application attacks','4.3','CVE|CVSS|CWE|SBOM|SAST|DAST|XSS|CSRF|SQLi',
'A CVE identifies a known vulnerability; CVSS describes technical severity; CWE categorizes weakness types. An SBOM lists components so exposure can be traced. SAST inspects code without running it, while DAST probes a running application. SQL injection targets database queries, XSS executes script in a browser, and CSRF abuses an authenticated browser to send an unwanted action.',
'Inventory components|Identify weaknesses|Assess severity and exposure|Remediate and validate',
'A dependency appears in the SBOM with a reported CVE. Its CVSS score informs prioritization, but internet exposure and business importance also matter. Testing then verifies the fix in the actual application.',
'A high CVSS score is not a complete business-risk assessment. XSS and CSRF exploit different mechanisms.',[
('A team needs the standardized identifier of one publicly disclosed flaw. Which should it record?','CVE|CVSS|CWE|SBOM','CVE identifies a particular disclosed vulnerability.|CVSS scores technical severity.|CWE categorizes weakness patterns.|An SBOM inventories software components.'),
('A scanner sends crafted requests to a running web application without access to source code. Which test is shown?','DAST|SAST|SBOM generation|CVSS scoring','DAST tests behavior of a running application.|SAST inspects code without executing the application.|SBOM generation produces an inventory.|CVSS scoring assesses severity rather than sending test requests.'),
('An attacker causes a logged-in browser to submit an unwanted funds-transfer request. No injected script is required. Which attack fits?','CSRF|XSS|SQLi|CWE','CSRF abuses the browser’s authenticated state to perform an unintended action.|XSS requires execution of attacker-controlled script in the user’s browser.|SQLi changes a database query through input.|CWE is a weakness catalog, not the attack described.')])
A('Resilience and risk calculations','5.2','RTO|RPO|MTTR|MTBF|DR|BCP|SLE|ARO|ALE',
'RTO is a restoration-time target; RPO is the acceptable data-loss window. MTTR is measured average repair time, while MTBF measures average operation between failures. BCP maintains critical business activity; DR restores technology after disruption. SLE estimates loss per event; ARO estimates annual frequency; ALE = SLE × ARO. Targets and historical measurements are different.',
'Identify business impact|Set recovery targets|Design backup and recovery|Test actual performance',
'A payment service must return within two hours and lose at most fifteen minutes of records: RTO is two hours, RPO is fifteen minutes. A $40,000 event expected once every four years has ARO 0.25 and ALE $10,000.',
'RPO measures lost data in time, not how long repairs take. ARO can be less than one.',[
('Backups must limit loss to the last 20 minutes of transactions. Which metric defines that requirement?','RPO|RTO|MTTR|MTBF','RPO is the acceptable data-loss window.|RTO specifies how quickly service must be restored.|MTTR is average measured repair time.|MTBF is average operation between failures.'),
('A $60,000 loss occurs once every three years on average. What is the ALE?','$20,000|$60,000|$180,000|$3,000','SLE $60,000 × ARO 1/3 = $20,000 per year.|$60,000 is the single-event loss.|Multiplying by three reverses the annual frequency.|This value does not follow SLE × ARO.'),
('Staff use a manual order process during an outage while IT restores the database. Which plan MOST directly covers the manual process?','BCP|DR only|CRL|SBOM','BCP keeps critical business functions operating during disruption.|DR focuses on restoring systems; manual business continuity is broader.|A CRL lists revoked certificates.|An SBOM inventories software components.')])
A('Agreements and protected information','5.1','SLA|NDA|MOU|MOA|BPA|PII|PHI|PCI DSS|GDPR',
'Choose agreements by their purpose: SLA defines measurable service commitments; NDA restricts disclosure; MOU records shared understanding; MOA documents agreed actions; BPA defines a business partnership. PII identifies people and PHI concerns protected health information. PCI DSS addresses payment-card environments; GDPR concerns personal-data protection under its scope. Exact obligations depend on applicable context and agreement terms.',
'Identify data and parties|Determine obligations|Document responsibilities|Measure and review compliance',
'A hosted access-control vendor commits to four-hour incident response in an SLA. An NDA protects building drawings. Employee identities and badge activity require appropriate privacy handling even when the system is physical security.',
'An agreement’s title alone does not settle legal enforceability. For exam scenarios, identify its stated purpose.',[
('A customer needs a written commitment to 99.9% uptime with defined service remedies. Which document fits BEST?','SLA|NDA|SBOM|MOU','An SLA defines measurable service levels and related terms.|An NDA restricts disclosure rather than uptime.|An SBOM inventories software components.|An MOU records understanding but is not the specific service-level instrument.'),
('A supplier must keep unreleased site drawings confidential. Which agreement MOST directly addresses that goal?','NDA|SLA|BPA|RTO','An NDA addresses disclosure of confidential information.|An SLA addresses service performance.|A BPA describes the broader business relationship.|RTO is a recovery target, not an agreement.'),
('An application stores payment-card information. Which named standard MOST directly addresses that environment?','PCI DSS|GDPR|PHI|PII','PCI DSS specifically addresses payment-card data security.|GDPR addresses personal-data protection under its scope, not specifically payment-card security standards.|PHI is a category of health information.|PII is a category of identifying data, not a payment-card security standard.')])
A('Mobile ownership and service vocabulary','4.1','BYOD|COPE|CYOD|MDM|MAM|SSH|DNS|DHCP|NTP|RDP|LDAP',
'BYOD means a personal device is used for work. COPE means the company owns it and permits personal use; CYOD offers an approved selection. MDM manages the device; MAM manages applications and their data. For network services, connect the letters to the job: SSH administers securely, DNS resolves names, DHCP supplies addressing, NTP synchronizes time, RDP provides a remote desktop, and LDAP accesses directory data.',
'Determine ownership|Set management scope|Protect work data|Permit only required services',
'On a personal phone, an employer may manage only the work app and remove its business data through MAM. A corporate tablet may receive device-wide settings through MDM. Deleting personal data without a defined policy is not a substitute for choosing the right management scope.',
'Ownership and management scope are separate decisions: BYOD does not automatically mean the organization manages every part of the device.',[
('Employees own their phones. The organization wants to wipe only the work app’s data. Which control fits BEST?','MAM|Full device wipe|COPE|CYOD','MAM targets applications and their associated work data.|A full wipe exceeds the requested scope.|COPE describes company ownership, unlike this scenario.|CYOD describes choosing from approved devices, not application-only management.'),
('A company buys phones but permits employees to use them personally. Which model is this?','COPE|BYOD|CYOD necessarily|MAM','COPE explicitly combines corporate ownership and personal use.|BYOD uses personally owned equipment.|An approved choice list is not stated.|MAM is an application-management capability, not an ownership model.'),
('Hosts reach a server by IP address but not by its name. Which service should be investigated FIRST?','DNS|NTP|RDP|DHCP lease renewal','DNS resolves the name, making it the direct first check.|NTP handles time synchronization.|RDP supplies remote desktop sessions.|A working IP path makes name resolution a better initial focus than renewing addressing.')])
P('Start with secure web and administration','4.5','80|443|22|23|3389',
'A port identifies a service endpoint; it does not prove what traffic is actually doing. HTTP commonly uses TCP 80; HTTPS commonly uses TCP 443 with TLS. SSH uses TCP 22 for encrypted shell access and SFTP/SCP. Telnet on TCP 23 exposes terminal traffic. RDP uses TCP/UDP 3389 for desktop access. Permit administration only from authorized management paths.',
'Identify the service|Choose protected protocol|Restrict source and destination|Validate allowed and blocked traffic',
'For an internal Linux server, allow TCP 22 only from the management subnet. An internet-facing website normally needs inbound TCP 443. Opening 3389 from any internet source is unnecessary for either requirement.',
'Changing a port number does not add encryption. HTTPS may also use UDP 443 with HTTP/3; the traditional TCP mapping is not the only possible transport.',[
('A Linux administrator needs encrypted command-line access. Which destination should the firewall allow?','TCP 22|TCP 23|TCP 443 only|UDP 3389','SSH normally uses TCP 22 for encrypted shell access.|Telnet on 23 is cleartext.|HTTPS is web traffic and is not the requested shell service.|RDP is remote desktop, not the requested SSH shell.'),
('A rule permits a public web service encrypted with TLS. Which traditional mapping fits?','TCP 443|TCP 80|TCP 22|TCP 3389','HTTPS traditionally uses TCP 443.|HTTP on 80 does not itself provide TLS.|22 is normally SSH.|3389 is normally RDP.'),
('A legacy appliance is managed through Telnet. What is the BEST improvement among these options?','Replace Telnet with SSH and restrict management sources|Move Telnet to port 443|Allow TCP 23 from anywhere|Use HTTP for passwords','SSH encrypts the management session; restricting sources also limits exposure.|A new port does not encrypt Telnet.|Broadening cleartext management access increases risk.|HTTP does not protect credentials in transit.')])
P('Names, addressing, and trustworthy time','4.5','53|67|68|123',
'DNS uses UDP and TCP 53; TCP is needed for operations such as zone transfers and may also carry normal responses. DHCP uses UDP 67 at the server and UDP 68 at the client. NTP uses UDP 123. Correct time supports meaningful logs and time-sensitive authentication. Secure network design restricts these services to approved infrastructure.',
'DHCP gives configuration|DNS resolves the name|Client connects to service|NTP keeps timestamps aligned',
'A new workstation broadcasts for DHCP configuration, queries its DNS resolver, and synchronizes its clock. Blocking all TCP 53 can break valid DNS operations even when many simple queries still work.',
'DNS is not UDP-only. DHCP does not, by itself, prove that a host has a working route to the internet.',[
('A DNS zone transfer fails after a firewall allows only UDP 53. Which additional conventional rule is required between the authorized DNS servers?','TCP 53|TCP 123|UDP 68|TCP 443','DNS zone transfers normally use TCP 53.|NTP uses UDP 123 and does not transfer zones.|UDP 68 is the DHCP client port.|HTTPS is not the conventional zone-transfer transport.'),
('Which pair correctly maps DHCP server and client ports?','Server UDP 67, client UDP 68|Server TCP 67, client TCP 68|Server UDP 68, client UDP 67|Server UDP 53, client UDP 123','DHCP uses UDP 67 on servers and UDP 68 on clients.|The conventional DHCP exchange uses UDP, not TCP.|These server and client assignments are reversed.|Those numbers identify DNS and NTP.'),
('Security logs from separate hosts have inconsistent times. Which service should be checked?','NTP on UDP 123|DNS on TCP 53|DHCP on UDP 67|SSH on TCP 22','NTP synchronizes system clocks.|DNS resolves names.|DHCP supplies network configuration.|SSH supplies secure remote shell access.')])
P('Transfer files without exposing credentials','4.5','20|21|22|69|445',
'FTP traditionally uses TCP 21 for control and TCP 20 for active-mode data; passive data uses negotiated ports. FTP alone does not encrypt credentials. SFTP is a separate SSH-based protocol on TCP 22, not FTP with TLS. TFTP uses UDP 69 for the initial request and has no built-in authentication or encryption. SMB uses TCP 445 for file sharing; modern SMB protection depends on configuration.',
'Identify data sensitivity|Select secure transfer|Scope access to trusted peers|Verify encryption and permissions',
'A switch needs an image from an isolated provisioning server using TFTP. Keep that limited path separate from everyday sensitive file transfer, for which SFTP is a better choice when supported.',
'FTP data does not always use port 20. SFTP and FTPS are different protocols.',[
('A job must securely transfer files over SSH. Which destination port normally fits?','TCP 22|TCP 21|UDP 69|TCP 20','SFTP runs over SSH, conventionally TCP 22.|21 is FTP control, not SFTP.|TFTP on 69 is not encrypted SSH transfer.|20 is associated with FTP active data.'),
('An appliance uses TFTP to download a boot image. Which initial destination mapping is expected?','UDP 69|TCP 69|TCP 445|UDP 21','TFTP sends its initial request to UDP 69.|TFTP uses UDP rather than TCP.|445 is SMB.|FTP control uses TCP 21, not this UDP mapping.'),
('A Windows file server should accept SMB only from an approved subnet. Which destination port is the main modern mapping?','TCP 445|TCP 139 only|UDP 161|TCP 23','Direct-hosted SMB uses TCP 445; restrict allowed sources.|139 is legacy SMB over NetBIOS, not the main modern direct-hosted mapping.|161 is normally SNMP monitoring.|23 is Telnet.')])
P('Send mail versus read mail','4.5','25|465|587|110|995|143|993',
'SMTP (Simple Mail Transfer Protocol) sends mail: server relay commonly uses TCP 25; client submission commonly uses TCP 587 with STARTTLS or 465 with implicit TLS. POP3 (Post Office Protocol version 3) retrieves mail on 110, or 995 with implicit TLS. IMAP (Internet Message Access Protocol) synchronizes mailboxes on 143, or 993 with implicit TLS. STARTTLS must be negotiated and enforced where used.',
'Client submits: 587 or 465|Servers relay: 25|Client synchronizes: 993|Validate TLS and server identity',
'A phone synchronizes folders using IMAPS on 993, while outgoing submission goes to 587 with required STARTTLS. A firewall rule for SMTP alone does not enable mailbox reading.',
'SMTP sends; IMAP and POP3 retrieve. Port 587 does not guarantee encryption unless STARTTLS is actually required and used.',[
('A client must synchronize mailbox folders using implicit TLS. Which is BEST?','TCP 993|TCP 995|TCP 25|TCP 110','IMAPS on 993 provides IMAP mailbox synchronization with implicit TLS.|995 is POP3S, a different retrieval protocol.|25 is SMTP relay.|110 is conventional POP3 without implicit TLS.'),
('An email client submits outgoing messages with required STARTTLS. Which common port is expected?','TCP 587|TCP 143|TCP 993|TCP 53','587 is commonly used for authenticated submission with STARTTLS.|143 is IMAP access.|993 is IMAP over implicit TLS.|53 is DNS, not email submission.'),
('A POP3 service is moving to implicit TLS. Which destination replaces its conventional port 110?','TCP 995|TCP 465|TCP 993|TCP 25','POP3S uses TCP 995.|465 is SMTP submission with implicit TLS.|993 is IMAPS.|25 is SMTP relay.')])
P('Directories, monitoring, and logs','4.5','389|636|161|162|514',
'LDAP accesses directories, commonly on TCP 389; TLS may be negotiated with StartTLS. LDAPS uses TCP 636 for implicit TLS. SNMP (Simple Network Management Protocol) usually uses UDP 161 for queries and UDP 162 for notifications. Prefer SNMPv3 with appropriate authentication and privacy settings. Traditional syslog uses UDP 514; TLS-protected syslog commonly uses TCP 6514.',
'Authenticate directory access|Query device health|Receive event notifications|Centralize protected logs',
'A monitoring server queries a switch on 161 and receives its traps on 162. A directory client uses LDAPS on 636. Sending logs over traditional UDP 514 does not provide confidentiality or reliable delivery.',
'SNMPv3 does not automatically imply encryption: its security level must enable privacy. LDAP on 389 can use StartTLS when correctly configured.',[
('A directory connection requires implicit TLS. Which mapping fits?','TCP 636|UDP 161|TCP 389 without StartTLS|UDP 514','LDAPS conventionally uses TCP 636.|161 is SNMP queries.|Without StartTLS, the stated 389 connection is not protected by TLS.|514 is traditional syslog.'),
('A switch sends an unsolicited SNMP notification to a manager. Which destination is conventional?','UDP 162|UDP 161|TCP 636|TCP 389','162 is the usual SNMP trap/notification destination.|161 is used for SNMP queries to an agent.|636 is LDAPS.|389 is LDAP.'),
('A design sends sensitive event logs using traditional UDP 514. What improvement BEST protects transport?','Use authenticated TLS syslog, commonly TCP 6514|Rename the collector|Move UDP traffic to port 443 without TLS|Use SNMPv1 community strings','TLS syslog protects the transport when peers and certificates are validated.|A name change does not protect packets.|Port numbers alone do not add TLS.|SNMPv1 does not secure syslog transport.')])
P('Database, voice, and legacy exposure','4.5','1433|1521|3306|5060|5061|135|137|138|139',
'Database listeners commonly include Microsoft SQL Server TCP 1433, Oracle TCP 1521, and MySQL TCP 3306. Restrict them to required application hosts. SIP (Session Initiation Protocol) commonly uses TCP/UDP 5060 for voice signaling; SIPS uses TLS on TCP 5061. Media protection is separate. RPC and NetBIOS ports identify legacy or platform services; do not expose them broadly just because an application uses Windows.',
'Public client reaches front end|Application reaches database|Management stays restricted|Deny unnecessary legacy exposure',
'A web application needs MySQL access on 3306 from its application subnet. Internet clients should reach the front end, not the database listener. TLS on SIP signaling does not automatically encrypt the voice media stream.',
'A service’s port does not authenticate a user, guarantee encryption, or justify internet exposure.',[
('Only an application server should reach its MySQL backend. Which rule fits BEST?','Allow application host to database TCP 3306|Allow internet to database TCP 3306|Allow application host to TCP 1433|Allow all sources to UDP 5060','This matches the service and limits source and destination.|The source scope unnecessarily exposes the database.|1433 is the conventional Microsoft SQL Server mapping.|5060 is SIP signaling and the scope is excessive.'),
('A voice deployment requires SIP signaling over TLS. Which port is expected?','TCP 5061|UDP 5060|TCP 1521|UDP 138','SIPS conventionally uses TLS on TCP 5061.|5060 is conventional SIP without implicit TLS.|1521 is an Oracle listener.|138 is NetBIOS datagram service.'),
('A scan shows TCP 139. Which service is MOST closely associated?','NetBIOS session service|Modern direct-hosted SMB on 445|Oracle listener|RPC endpoint mapper on 135','TCP 139 is NetBIOS session service and can carry legacy SMB.|445 is a different port for direct-hosted SMB.|Oracle commonly uses 1521.|RPC endpoint mapping is associated with 135, not 139.')])
P('Authentication, VPN negotiation, and secure logs','4.5','88|49|1812|1813|500|4500|6514',
'Kerberos uses TCP/UDP 88 for ticket-based authentication. RADIUS commonly uses UDP 1812 for authentication and authorization and UDP 1813 for accounting. TACACS+ uses TCP 49 for device-administration AAA. IKE (Internet Key Exchange) uses UDP 500 to negotiate IPsec; NAT traversal commonly uses UDP 4500. TLS syslog commonly uses TCP 6514. ESP is IP protocol 50, not TCP or UDP port 50.',
'Authenticate the user or peer|Authorize only required access|Protect the session|Send protected accounting and logs',
'A VPN gateway negotiates IKE on UDP 500. When network address translation is present, NAT traversal uses UDP 4500. Its RADIUS access requests go to 1812, and accounting records go to 1813. Each rule serves a different step.',
'Do not confuse IP protocol numbers with port numbers. Allowing TCP port 50 does not permit ESP.',[
('A gateway authenticates remote users through RADIUS and sends separate accounting records. Which destination pair is conventional?','UDP 1812 and UDP 1813|TCP 49 and TCP 88|UDP 500 and UDP 4500|UDP 161 and UDP 162','RADIUS access uses 1812 and accounting uses 1813.|49 identifies TACACS+ and 88 identifies Kerberos.|These support IKE and IPsec NAT traversal.|These are SNMP queries and notifications.'),
('An IPsec tunnel must cross a device performing network address translation. Which port commonly carries NAT traversal traffic?','UDP 4500|TCP 50|UDP 1813|TCP 6514','IPsec NAT traversal commonly encapsulates traffic over UDP 4500.|ESP uses IP protocol number 50; it is not TCP port 50.|1813 is RADIUS accounting.|6514 is TLS syslog.'),
('A network switch uses TACACS+ for administrator AAA. Which conventional destination should be permitted to the AAA server?','TCP 49|UDP 1812|TCP 88|UDP 500','TACACS+ uses TCP 49.|1812 is RADIUS access, a different AAA protocol.|88 is Kerberos authentication.|500 is IKE negotiation.')])
# Explicit expansions for all protocol names introduced in this course.
expansions={'FTP':'File Transfer Protocol','SFTP':'SSH File Transfer Protocol','SCP':'Secure Copy Protocol','HTTP':'Hypertext Transfer Protocol','HTTPS':'Hypertext Transfer Protocol Secure','TLS':'Transport Layer Security','TCP':'Transmission Control Protocol','UDP':'User Datagram Protocol','SSH':'Secure Shell','RDP':'Remote Desktop Protocol','DNS':'Domain Name System','DHCP':'Dynamic Host Configuration Protocol','NTP':'Network Time Protocol','TFTP':'Trivial File Transfer Protocol','SMB':'Server Message Block','SMTP':'Simple Mail Transfer Protocol','POP3':'Post Office Protocol version 3','IMAP':'Internet Message Access Protocol','LDAP':'Lightweight Directory Access Protocol','SNMP':'Simple Network Management Protocol','SIP':'Session Initiation Protocol','RPC':'Remote Procedure Call','NetBIOS':'Network Basic Input/Output System','FTPS':'FTP over TLS','SIPS':'SIP over TLS','LDAPS':'LDAP over TLS','IMAPS':'IMAP over TLS','POP3S':'POP3 over TLS'}
root=Path(__file__).resolve().parents[1]
(root/'js/guided-data.js').write_text('window.GUIDED_COURSES = '+json.dumps(courses,ensure_ascii=False,indent=2)+';\nwindow.PROTOCOL_NAMES = '+json.dumps(expansions)+';\n')
print({k:len(v) for k,v in courses.items()})
